const assert=require('node:assert/strict');const {boot}=require('./scripts/career-test-fixture.cjs');const a=boot(),r=a.run;
r("startCareerWithClub('HV71');globalThis.club='Färjestad BK';rivalsClubState(club).coach.adaptability=18;globalThis.base=rivalPlan(club,'HV71');globalThis.ctx={seconds:1800,gf:1,ga:1,shots:12,againstShots:14,windowSeconds:600,recentShots:1,recentAgainst:9};");
assert.equal(r('aiCoachDecision(club,base,ctx).situation'),'pressure');
assert.equal(r('aiCoachDecision(club,base,{...ctx,windowSeconds:120}).situation'),'base');
r('globalThis.changed=aiCoachDecision(club,base,ctx)');
assert.equal(r('aiCoachDecision(club,base,{...ctx,seconds:1920,recentShots:9,recentAgainst:1,previous:changed}).situation'),'pressure');
assert.equal(r('aiCoachDecision(club,base,{...ctx,seconds:2500,recentShots:9,recentAgainst:1,previous:changed}).situation'),'base');
assert.equal(r('aiCoachDecision(club,base,{...ctx,seconds:3400,gf:1,ga:2,strength:-1}).situation'),'pk');
assert.equal(r('aiCoachDecision(club,base,{...ctx,strength:1}).situation'),'pp');
assert.equal(r('aiCoachDecision(club,base,{...ctx,energy:40}).rotation'),'rollFour');
assert.equal(r('aiCoachDecision(club,base,{...ctx,energy:80,linePoints:[0,3,0,0]}).hotLine'),1);
assert.equal(r('aiCoachDecision(club,base,{...ctx,energy:40,linePoints:[0,3,0,0]}).hotLine'),null);
r("rivalsClubState(club).coach.style='pressure';globalThis.bold=aiCoachDecision(club,base,{...ctx,seconds:2800,gf:1,ga:2});rivalsClubState(club).coach.style='counter';globalThis.cautious=aiCoachDecision(club,base,{...ctx,seconds:2800,gf:1,ga:2});");assert.equal(r('bold.situation'),'chase');assert.notEqual(r('cautious.situation'),'chase');
r('globalThis.observed={};for(let i=0;i<20;i++)aiObserveMatch(observed,{seconds:i*120,shots:i,againstShots:i*2});globalThis.before=JSON.stringify(observed);aiObserveMatch(observed,{seconds:2280,shots:19,againstShots:38})');assert.equal(r('JSON.stringify(observed)'),r('before'));assert.equal(r('observed.coachObservations.length'),7);
r("clubAIState(club).memory.HV71={meetings:[{year:2020,gf:0,ga:5,opponentStyle:'pressure'},{year:2020,gf:0,ga:5,opponentStyle:'pressure'}]}");assert.equal(r("aiMatchPlan(club,'HV71',{style:'control',tempo:'normal'}).matchup"),false);
r('save()');const b=boot(a.storage.value);assert.equal(b.run("JSON.stringify(aiCoachTraits('Färjestad BK'))"),r('JSON.stringify(aiCoachTraits(club))'));
console.log('PASS: recent pressure, patient response, manpower priority, fatigue, productive lines, coach risk, bounded/replay-safe observations, stale memory and saved identity.');
assert.throws(()=>r('validateAICoachSave({live:{aiTeam:{coachObservations:[{seconds:-1,shots:1,againstShots:2}]}}})'));
r('validateAICoachSave({live:{aiTeam:{}}})');
