const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');state.money=1e8;ensureRecruitment();ensureRivals();globalThis.club='Färjestad BK';globalThis.c=rivalsClubState(club);state.recruitment.ai[club].cash=2e8;state.recruitment.ai[club].wageLimit=2e8;for(const p of state.clubRosters[club].filter(p=>p.pos==='MV')){p.health.injury={remaining:30};}globalThis.before=state.recruitment.history.length;globalThis.all=()=>[...Object.values(state.clubRosters).flat(),...state.loans.external,...state.playerWorld.freeAgents].map(p=>String(p.id));globalThis.idsBefore=all().sort().join();rivalScoutMarket(club);`);
assert.equal(r('rivalRecruitNeeds(club)[0].kind'),'MV');
assert.ok(r('Object.values(c.scouting.reports).length')>0,'the AI identifies a scoutable goalkeeper');
assert.equal(r('state.recruitment.history.length'),r('before'),'no signing on the first observation');
r('globalThis.once=JSON.stringify(c.scouting);rivalScoutMarket(club)');assert.equal(r('JSON.stringify(c.scouting)'),r('once'));
r('for(let i=0;i<12&&state.recruitment.history.length===before;i++){state.recruitment.tick+=3;rivalScoutMarket(club)}');
assert.ok(r('state.recruitment.history.length')>r('before'),'a checked and affordable need leads to a signing');
assert.equal(r('state.recruitment.history[0].buyer'),r('club'));assert.equal(r('findPlayerAnywhere(state.recruitment.history[0].playerId).pos'),'MV');
assert.equal(r('all().sort().join()'),r('idsBefore'),'transfers preserve the complete identity set, including free agents');
assert.ok(r('state.recruitment.ai[club].cash')>=0);assert.ok(r('loanWageCost(club)<=state.recruitment.ai[club].wageLimit'));
r(`globalThis.game=state.schedule.find(g=>g.home!==managerClub()&&g.away!==managerClub());globalThis.result=rivalSimulate(game);game.homeGoals=result.homeGoals;game.awayGoals=result.awayGoals;rivalAfterFixture(game,result.rows,result.reports);globalThis.after=JSON.stringify(state.teamDynamics);rivalAfterFixture(game,result.rows,result.reports);`);
assert.equal(r('JSON.stringify(state.teamDynamics)'),r('after'),'background chemistry applied once');
assert.ok(r('Object.keys(dynamicsClub(game.home).pairs).length')>0);
r(`state.calendar.date=calendarTarget();startMatch();globalThis.e=studioEngine();state.live.period=3;state.live.minute=17;state.live.hv=3;state.live.opp=1;rivalLiveDecision();studioSyncPlans();`);
assert.equal(r('e.teams[1].posture'),'attack');assert.equal(r('e.teams[1].tempo'),'high');
console.log('PASS: positional AI scouting, two observations, idempotent scouting tick, needs-based signing, preserved player identities/budgets, background chemistry and live score-based coaching.');
