"use strict";
function ensureAnalysis(){
 if(!state.careerStarted)return;
 if(!state.analysis)state.analysis={version:1,nextId:1,matches:[],selected:'latest',window:'10',side:'all',compareA:null,compareB:null};
 const m=state.live;if(m&&!m.analysis&&!m.finished){
  m.analysis={id:`${state.season?.year||2026}-${state.round}-${state.analysis.nextId++}`,shots:[],events:[],units:{},players:{},partial:Boolean(m.minute||m.second||m.period>1||m.shotsHV||m.shotsOpp),saved:false};
  for(const p of managerRoster())m.analysis.players[String(p.id)]={id:p.id,name:p.name,pos:p.pos,seconds:0,shots:0,goals:0,assists:0,pim:0,startAttributes:{...p.attributes}};
 }
 ensureLeagueLive();
}
function analysisClock(){const m=state.live;return (m.period<=3?(m.period-1)*1200:3600+((m.overtimePeriods||1)-1)*1200)+m.minute*60+m.second;}
function analysisSituation(){const m=state.live;return m.penaltiesOpp.length>m.penaltiesHV.length?'pp':m.penaltiesHV.length>m.penaltiesOpp.length?'pk':m.period===4&&!isPlayoffMatch()?'ot':'even';}
function analysisUnits(){
 const m=state.live;if(!m)return [];
 const situation=analysisSituation(),skaters=[...currentLinePlayers(),...currentDefensePlayers()];
 if(situation!=='even'){const n=(m.rotationIndex||0)%2+1;return [{kind:situation,label:situation==='ot'?'Förlängning':`${situation.toUpperCase()} ${n}`,players:skaters}];}
 return [{kind:'forward',label:`Kedja ${m.currentLine+1}`,players:currentLinePlayers()},{kind:'defense',label:`Backpar ${m.currentDefensePair+1}`,players:currentDefensePlayers()}];
}
function analysisUnitRecord(unit){
 const a=state.live.analysis,key=JSON.stringify([unit.kind,...unit.players.map(p=>String(p.id)).sort()]);
 if(!a.units[key])a.units[key]={key,kind:unit.kind,label:unit.label,names:unit.players.map(p=>p.name),ids:unit.players.map(p=>p.id),seconds:0,shotsFor:0,shotsAgainst:0,dangerFor:0,dangerAgainst:0,goalsFor:0,goalsAgainst:0};
 return a.units[key];
}
function analysisPlayer(p){const a=state.live.analysis;return a.players[String(p.id)]||(a.players[String(p.id)]={id:p.id,name:p.name,pos:p.pos,seconds:0,shots:0,goals:0,assists:0,pim:0,startAttributes:{...p.attributes}});}
function analysisIce(players,seconds){
 ensureAnalysis();if(!state.live?.analysis||state.live.finished||seconds<=0)return;
 for(const unit of analysisUnits())analysisUnitRecord(unit).seconds+=Math.max(0,Math.min(seconds,...unit.players.map(p=>medicalLimit(p)-(state.live.iceTime?.[p.id]||0))));
 for(const p of players)analysisPlayer(p).seconds+=Math.max(0,Math.min(seconds,medicalLimit(p)-(state.live.iceTime?.[p.id]||0)));
}
// Positions are generated by this shot model and modify the same probability used for its outcome.
function shotLocation(dangerous){const x=dangerous?76+Math.random()*14:46+Math.random()*40,y=dangerous?38+Math.random()*24:12+Math.random()*76;return {x,y,factor:Math.max(.8,Math.min(1.15,1+(x-70)/150-Math.abs(y-50)/200))};}
function recordAnalysisShot(side,name,id,dangerous,location,probability,result,override=null){
 ensureAnalysis();const a=state.live?.analysis;if(!a)return;
 const outcome=override||(result<probability?'goal':result<probability+.12?'post':result<probability+.28?'rebound':'save');
 const shot={time:analysisClock(),side,name,id,dangerous:Boolean(dangerous),x:location.x,y:location.y,probability,outcome,situation:analysisSituation()};
 a.shots.push(shot);
 leagueTrackShot(side,id,name,outcome);
 for(const unit of analysisUnits()){const u=analysisUnitRecord(unit);u[side==='own'?'shotsFor':'shotsAgainst']++;if(dangerous)u[side==='own'?'dangerFor':'dangerAgainst']++;}
 if(side==='own'){const p=playerById(id);if(p)analysisPlayer(p).shots++;}
}
function analysisEvent(type,side,text,id=null){
 ensureAnalysis();const a=state.live?.analysis;if(!a)return;
 a.events.push({time:analysisClock(),type,side,text,situation:analysisSituation()});
 if(type==="goal"||type==="penalty")leagueTrackEvent(type,side,id);
 if(type==='goal'){
  for(const unit of analysisUnits())analysisUnitRecord(unit)[side==='own'?'goalsFor':'goalsAgainst']++;
  if(side==='own'){const p=playerById(id);if(p)analysisPlayer(p).goals++;}
 }
 if(type==='penalty'&&side==='own'){const p=playerById(id);if(p)analysisPlayer(p).pim+=2;}
}
function analysisAssist(p){ensureAnalysis();leagueTrackEvent("assist","own",p.id);if(state.live?.analysis)analysisPlayer(p).assists++;}
function analysisSnapshot(){
 const m=state.live,a=m?.analysis;if(!a)return null;
 return {id:a.id,year:state.season?.year||2026,round:state.round,date:state.calendar?.date,friendly:Boolean(m.friendly),club:managerClub(),opponent:m.opponent,home:state.schedule.find(g=>g.round===state.round&&(g.home===managerClub()||g.away===managerClub()))?.home===managerClub(),stage:m.friendly?'Träningsmatch':state.season?.phase==='playoffs'?SEASON_STAGES[state.schedule.find(g=>g.round===state.round&&(g.home===managerClub()||g.away===managerClub()))?.stage||state.season.stage]:'Grundserie',own:m.hv,against:m.opp,finished:m.finished,hockey:m.rink?.hockey?{counts:m.rink.hockey.counts,stops:m.rink.hockey.stops}:null,partial:a.partial,shootout:Boolean(m.analysisShootout),abandoned:Boolean(m.analysisAbandoned),shots:a.shots,events:a.events,units:Object.values(a.units),players:Object.values(a.players).map(p=>{const current=playerById(p.id);return {...p,endAttributes:{...(current?.attributes||p.startAttributes)}};})};
}
function finishAnalysis(){
 ensureAnalysis();leagueCommitLive();const a=state.live?.analysis;if(!a||a.saved||!state.live.finished)return;
 const snapshot=analysisSnapshot();a.saved=true;state.analysis.matches.unshift(JSON.parse(JSON.stringify(snapshot)));trimAnalysisArchive();state.analysis.selected='latest';
 managerMessage(`analysis:${a.id}`,'Matchanalysen är klar',`${snapshot.club} ${snapshot.own}–${snapshot.against} ${snapshot.opponent}. Skott, formationer och spelarnas minuter finns under Statistik & analys.`,'Matchanalytiker',{link:'statistics'});
}
function trimAnalysisArchive(){
 const a=state.analysis;a.matches=a.matches.slice(0,80);
 let size=JSON.stringify(a.matches).length;
 while(size>1200000&&a.matches.length>1){size-=JSON.stringify(a.matches.pop()).length+1;}
}
function analysisSelection(){const s=state.analysis;if(s.selected==='live')return analysisSnapshot();return s.matches.find(m=>m.id===s.selected)||s.matches[0]||analysisSnapshot();}
function analysisSamples(){const s=state.analysis,matches=s.matches.filter(m=>m.club===managerClub()&&!m.friendly);return s.window==='season'?matches.filter(m=>m.year===(state.season?.year||2026)):s.window==='all'?matches:matches.slice(0,Number(s.window)||10);}
function analysisRate(n,seconds){return seconds>0?(n*3600/seconds).toFixed(1):'—';}
function analysisTime(seconds){return `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;}
function analysisAggregateUnits(matches){const units={};for(const m of matches)for(const u of m.units){if(!units[u.key])units[u.key]={...u,seconds:0,shotsFor:0,shotsAgainst:0,dangerFor:0,dangerAgainst:0,goalsFor:0,goalsAgainst:0,matches:0};const row=units[u.key];row.matches++;for(const k of ['seconds','shotsFor','shotsAgainst','dangerFor','dangerAgainst','goalsFor','goalsAgainst'])row[k]+=u[k];}return Object.values(units).sort((a,b)=>b.seconds-a.seconds);}
function analysisAggregatePlayers(matches){const players={};for(const m of [...matches].reverse())for(const p of m.players){if(!players[p.id])players[p.id]={id:p.id,name:p.name,pos:p.pos,games:0,seconds:0,shots:0,goals:0,assists:0,pim:0,start:p.startAttributes,end:p.endAttributes};const row=players[p.id];if(p.seconds>0)row.games++;for(const key of ['seconds','shots','goals','assists','pim'])row[key]+=p[key];row.end=p.endAttributes;}return Object.values(players).filter(p=>p.games).sort((a,b)=>(b.goals+b.assists)-(a.goals+a.assists)||b.seconds-a.seconds);}
function analysisSet(key,value){if(!['selected','window','side','compareA','compareB'].includes(key))return;state.analysis[key]=value;save();render();}
function analysisShotMap(match){
 const shots=match.shots.filter(s=>state.analysis.side==='all'||s.side===state.analysis.side);
 return `<section class="analysis-map"><header><h2>Skottkarta</h2><label>Visa<select onchange="analysisSet('side',this.value)">${[['all','Båda lagen'],['own',match.club],['opponent',match.opponent]].map(([key,label])=>`<option value="${key}" ${state.analysis.side===key?'selected':''}>${trainingSafe(label)}</option>`).join('')}</select></label></header><svg viewBox="0 0 600 320" role="img" aria-label="Registrerade skottlägen, båda lagens anfall åt höger"><rect x="5" y="5" width="590" height="310" rx="65" fill="#e7f1f4" stroke="#617c8b" stroke-width="3"/><path d="M300 5v310 M150 8v304 M440 8v304" stroke="#4e8fbc" stroke-width="3"/><circle cx="300" cy="160" r="45" fill="none" stroke="#b06b73" stroke-width="2"/><path d="M555 115v90h15v-90z" fill="none" stroke="#b94954" stroke-width="3"/>${shots.map(s=>`<circle cx="${s.x*5.7}" cy="${s.y*3.1}" r="${s.outcome==='goal'?7:4}" fill="${s.side==='own'?'#215c4c':'#b54158'}" stroke="${s.outcome==='goal'?'#141f2a':'white'}" stroke-width="${s.outcome==='goal'?2:1}"><title>${analysisTime(s.time)} · ${trainingSafe(s.name)} · ${({goal:'Mål',post:'Ramträff',rebound:'Retur',save:'Räddning',wide:'Utanför'})[s.outcome]}</title></circle>`).join('')}</svg><p>Grönt: ${trainingSafe(match.club)} · Rött: ${trainingSafe(match.opponent)}. Stor punkt med mörk kant: mål. Båda lagens anfall visas åt höger. Skottlägena kommer från spelets avslutsmodell; ramträffar ingår i avsluten.</p><details><summary>Alla registrerade avslut (${shots.length})</summary>${shots.map(s=>`<div class="analysis-event"><span>${analysisTime(s.time)}</span><span>${trainingSafe(s.name)} · ${s.side==='own'?match.club:match.opponent}</span><strong>${({goal:'Mål',post:'Ramträff',rebound:'Retur',save:'Räddning',wide:'Utanför'})[s.outcome]}${s.dangerous?' · farligt läge':''}</strong></div>`).join('')||'<p>Inga registrerade avslut.</p>'}</details></section>`;
}
function analysisUnitTable(units){return units.length?`<div class="analysis-scroll"><table><thead><tr><th>Formation & spelare</th><th>Istid</th><th>Skott för / emot</th><th>Farliga lägen för / emot</th><th>Mål för / emot</th><th>Skott / 60 min</th></tr></thead><tbody>${units.map(u=>`<tr><td><strong>${u.label}</strong><small>${u.names.map(trainingSafe).join(' · ')}</small></td><td>${analysisTime(u.seconds)}</td><td>${u.shotsFor} / ${u.shotsAgainst}</td><td>${u.dangerFor} / ${u.dangerAgainst}</td><td>${u.goalsFor} / ${u.goalsAgainst}</td><td>${analysisRate(u.shotsFor,u.seconds)} / ${analysisRate(u.shotsAgainst,u.seconds)}</td></tr>`).join('')}</tbody></table></div>`:'<p>Formationernas statistik börjar registreras när matchen spelas.</p>';}
function analysisAdvice(matches){
 if(!matches.length)return ['Spela en match för att få ett underlag.'];const units=analysisAggregateUnits(matches),advice=[];
 if(matches.length<3)advice.push('Underlaget omfattar färre än tre matcher. Vänta med stora slutsatser och följ samma formationer över fler matcher.');
 const regular=units.filter(u=>u.kind==='forward'&&u.seconds>=600),worst=[...regular].sort((a,b)=>(b.dangerAgainst-b.dangerFor)/b.seconds-(a.dangerAgainst-a.dangerFor)/a.seconds)[0];
 if(worst&&worst.dangerAgainst>worst.dangerFor)advice.push(`${worst.names.join(', ')} har släppt till ${worst.dangerAgainst} farliga lägen och skapat ${worst.dangerFor} på ${Math.round(worst.seconds/60)} minuter. Granska rollfördelning och matchplan; siffrorna visar inte ensamma orsaken.`);
 const productive=[...regular].sort((a,b)=>b.shotsFor/b.seconds-a.shotsFor/a.seconds)[0];if(productive)advice.push(`${productive.names.join(', ')} har flest registrerade skott per 60 minuter bland forwardskombinationer med minst tio minuters underlag: ${analysisRate(productive.shotsFor,productive.seconds)}.`);
 const pp=units.filter(u=>u.kind==='pp'),ppTime=pp.reduce((n,u)=>n+u.seconds,0),ppGoals=pp.reduce((n,u)=>n+u.goalsFor,0);if(ppTime>=600&&!ppGoals)advice.push(`Powerplay har inte gjort mål under ${Math.round(ppTime/60)} registrerade minuter. Jämför enheternas avslut och farliga lägen innan du ändrar spelarna.`);
 if(matches.some(m=>m.partial))advice.push('Minst en match har delvis registrerad statistik. Äldre händelser i den matchen har inte återskapats.');return advice.length?advice:['Följ fler matcher för att se om skillnaderna mellan formationerna håller i sig.'];
}
function analysisPlayerTable(players){return players.length?`<div class="analysis-scroll"><table><thead><tr><th>Spelare</th><th>Matcher med istid</th><th>Min / match</th><th>Mål</th><th>Assist</th><th>Skott</th><th>Utvisningsminuter</th></tr></thead><tbody>${players.map(p=>`<tr><td>${trainingSafe(p.name)}<small>${p.pos}</small></td><td>${p.games}</td><td>${(p.seconds/60/p.games).toFixed(1)}</td><td>${p.goals}</td><td>${p.assists}</td><td>${p.shots}</td><td>${p.pim}</td></tr>`).join('')}</tbody></table></div>`:'<p>Inga spelarminuter registrerade ännu.</p>';}
function analysisComparison(players,matches){
 const s=state.analysis,a=players.find(p=>String(p.id)===String(s.compareA))||players[0],b=players.find(p=>String(p.id)===String(s.compareB))||players[1];if(!a||!b)return '<p>Två spelare behöver registrerad istid för att kunna jämföras.</p>';
 const select=(key,p)=>`<label>Spelare<select onchange="analysisSet('${key}',this.value)">${players.map(q=>`<option value="${q.id}" ${q.id===p.id?'selected':''}>${trainingSafe(q.name)} · ${q.pos}</option>`).join('')}</select></label>`;
 return `<section class="analysis-comparison"><h2>Spelarjämförelse & utveckling</h2><div class="analysis-compare-picks">${select('compareA',a)}${select('compareB',b)}</div><div class="analysis-compare-grid">${[a,b].map(p=>{const fields=p.pos==='MV'?GOALIE_ATTRIBUTES:SKATER_ATTRIBUTES,changes=Object.keys(p.end).filter(k=>p.start[k]!==undefined&&p.end[k]!==p.start[k]);return `<article><h3>${trainingSafe(p.name)}</h3><p>${p.games} matcher · ${(p.seconds/60/p.games).toFixed(1)} min/match · ${p.goals+p.assists} poäng</p><p>Attributförändringar under urvalet: ${changes.map(k=>`${fields[k]} ${p.end[k]-p.start[k]>0?'+':''}${p.end[k]-p.start[k]}`).join(', ')||'Inga registrerade förändringar.'}</p><h4>Senaste fem registrerade matcher</h4>${matches.filter(m=>m.players.some(q=>q.id===p.id&&q.seconds>0)).slice(0,5).map(m=>{const q=m.players.find(q=>q.id===p.id);return `<div class="analysis-event"><span>${trainingSafe(m.opponent)}</span><span>${analysisTime(q.seconds)}</span><strong>${q.goals}+${q.assists}</strong></div>`;}).join('')}</article>`;}).join('')}</div><p>Attributförändringar följer dina egna spelares registrerade värden mellan matcherna. Olika roller och special teams påverkar produktionen; poäng är inte ett allmänt formbetyg.</p></section>`;
}
function statisticsView(){
 ensureAnalysis();const s=state.analysis,match=analysisSelection(),samples=analysisSamples(),units=analysisAggregateUnits(samples),players=analysisAggregatePlayers(samples);
 return `<section class="analysis-page"><header class="daily-heading"><div><span class="career-eyebrow">MATCHANALYTIKERN</span><h1>Förstå vad som händer.</h1><p>Matchhändelser, verklig istid och spelarna bakom formationerna.</p></div><button class="btn secondary" onclick="trainingOpen('match')">Till matchen</button></header><section class="analysis-report"><label>Matchrapport<select onchange="analysisSet('selected',this.value)">${state.live?.analysis&&!state.live.finished?`<option value="live" ${s.selected==='live'||!s.matches.length?'selected':''}>Pågående · ${state.live.opponent}</option>`:''}${s.matches.map((m,i)=>`<option value="${m.id}" ${s.selected===m.id||(s.selected==='latest'&&i===0)?'selected':''}>${seasonLabel(m.year)} · ${m.stage} · ${m.club} ${m.own}–${m.against} ${m.opponent}</option>`).join('')}</select></label>${match?`<h2>${trainingSafe(match.club)} ${match.own}–${match.against} ${trainingSafe(match.opponent)}</h2><p>${seasonLabel(match.year)} · ${match.stage} · ${match.finished?'Avslutad':'Pågår'}${match.partial?' · Delvis registrerad statistik':''}${match.shootout?' · Avgörande på straffar (straffarna ingår inte i skottkartan)':''}${match.abandoned?' · Avbruten match; slutresultatet innehåller administrativt tilldelade mål':''}</p><div class="analysis-metrics">${[['Registrerade avslut',match.shots.filter(s=>s.side==='own').length,match.shots.filter(s=>s.side==='opponent').length],['Farliga avslut',match.shots.filter(s=>s.side==='own'&&s.dangerous).length,match.shots.filter(s=>s.side==='opponent'&&s.dangerous).length],['Utvisningar',match.events.filter(e=>e.type==='penalty'&&e.side==='own').length,match.events.filter(e=>e.type==='penalty'&&e.side==='opponent').length]].map(([label,a,b])=>`<div><span>${label}</span><strong>${a} – ${b}</strong></div>`).join('')}</div>${match.hockey?`<p>Offside ${match.hockey.counts.offside.own}–${match.hockey.counts.offside.opponent} · Icing ${match.hockey.counts.icing.own}–${match.hockey.counts.icing.opponent} · Rensningar ${match.hockey.counts.clear.own}–${match.hockey.counts.clear.opponent}</p>`:''}${analysisShotMap(match)}<h2>Mål, utvisningar & avgöranden</h2>${match.events.map(e=>`<div class="analysis-event"><span>${analysisTime(e.time)}</span><strong>${e.type==='goal'?'MÅL':e.type==='penalty'?'UTVISNING':'AVGÖRANDE'}</strong><span>${trainingSafe(e.text)}</span></div>`).join('')||'<p>Inga registrerade händelser.</p>'}<details><summary>Formationer i den här matchen</summary>${analysisUnitTable(match.units)}</details>`:'<div class="analysis-empty"><h2>Statistiken börjar vid nästa nedsläpp</h2><p>Äldre matcher saknar detaljerade händelser och får inga påhittade rapporter. Pågående matcher registreras från uppdateringen.</p></div>'}</section><section><div class="analysis-section-heading"><h2>Trender över flera matcher</h2><label>Underlag<select onchange="analysisSet('window',this.value)">${[['5','Senaste fem'],['10','Senaste tio'],['season','Aktuell säsong'],['all','Alla sparade matcher']].map(([v,label])=>`<option value="${v}" ${s.window===v?'selected':''}>${label}</option>`).join('')}</select></label></div><p>${samples.length} avslutade matcher för ${managerClub()} i urvalet. Enskilda matchrapporter från tidigare klubbar finns kvar i arkivet. Upp till 80 matchrapporter sparas; äldre rapporter rensas tidigare om arkivet blir stort. Grundserie och slutspel ingår.</p><div class="analysis-advice"><h2>Assistentens observationer</h2>${analysisAdvice(samples).map(text=>`<p>${trainingSafe(text)}</p>`).join('')}</div><h2>Kedjor & backpar</h2><p>Varje rad följer en faktisk spelarkombination. Forwardskedjan och backparet delar samma laghändelser; summera därför inte raderna till lagtotaler. Kort istid gör siffror per 60 minuter osäkra.</p>${analysisUnitTable(units.filter(u=>['forward','defense'].includes(u.kind)))}<h2>Powerplay, boxplay & förlängning</h2><p>Enheternas minuter och händelser registreras i respektive spelform. Mål från straffläggning ingår inte.</p>${analysisUnitTable(units.filter(u=>!['forward','defense'].includes(u.kind)))}<h2>Spelarstatistik</h2>${analysisPlayerTable(players)}${analysisComparison(players,samples)}</section></section>`;
}
