"use strict";
// Club decisions use the existing finances, staff contracts and career simulation.
const clubDeskViewState={};
const CLUB_DESK_IMPACTS={assistant:'Leder A-lagets utespelarträning.',scout:'Bedömer värvningar. Förmågebedömning 16 eller högre ger ett extra scoutuppdrag.',goalie:'Leder målvaktsträningen och bedömer målvakter.',junior:'Leder juniorernas träning i den egna klubben.',physio:'Påverkar beredskap och belastningsåterhämtning under rehabilitering.'};
function clubDeskCapture(){
 const root=document.querySelector('.club-desk');if(!root?.dataset){clubDeskViewState.page=null;return;}
 clubDeskViewState.page=root.dataset.context;clubDeskViewState.scroll=Array.from(root.querySelectorAll('[data-cd-scroll]')).map(el=>[el.dataset.cdScroll,el.scrollTop]);
 const d=document.getElementById('club-dialog');clubDeskViewState.dialog=d?.open?d.dataset.context:null;
 if(d?.open){clubDeskViewState.top=d.scrollTop;clubDeskViewState.focus=Array.from(d.querySelectorAll('button,input,select,summary')).indexOf(document.activeElement);}
}
function clubDeskRestore(){
 const root=document.querySelector('.club-desk');if(!root?.dataset)return;
 if(root.dataset.context===clubDeskViewState.page)for(const [key,top] of clubDeskViewState.scroll||[]){const el=root.querySelector(`[data-cd-scroll="${key}"]`);if(el)el.scrollTop=top;}
 const d=document.getElementById('club-dialog');if(d){d.showModal();if(d.dataset.context===clubDeskViewState.dialog){d.scrollTop=clubDeskViewState.top||0;d.querySelectorAll('button,input,select,summary')[clubDeskViewState.focus]?.focus({preventScroll:true});}}
}
function clubDeskOpen(drawer){if(!['tickets','forecast','profile','renewal'].includes(drawer))return;clubDeskViewState.returnText=document.activeElement?.textContent;clubUI.drawer=drawer;render();}
function clubDeskClose(){
 if(state.page==='staff'&&state.clubOffice.offer){state.clubOffice.offer=null;save();}
 if(state.page==='manager'&&state.managerCareer.interview){state.managerCareer.interview=null;save();}
 clubUI.drawer=null;render();
 const buttons=Array.from(document.querySelectorAll('button'));(buttons.find(b=>b.textContent===clubDeskViewState.returnText)||document.querySelector('.cd-selected button'))?.focus?.();
}
function clubDeskPick(key,value){if(!['staffPerson','goal','policy','job'].includes(key))return;clubUI[key]=value;render();}
function clubDeskStaffSort(key){if(!['name','role','coaching','ability','potential','salary','expires'].includes(key))return;clubUI.staffDirection=clubUI.staffSort===key?-clubUI.staffDirection:['coaching','ability','potential'].includes(key)?-1:1;clubUI.staffSort=key;render();}
function clubDeskStaffSearch(form){clubUI.query=form.elements.query.value;render();}
function clubDeskTicketPreview(form){const ticket=Number(form.elements.ticket.value),gate=clubGate(false,ticket),out=form.querySelector('output');if(out)out.textContent=`Beräknad publik: ${gate.attendance.toLocaleString('sv-SE')} / ${state.clubOffice.capacity.toLocaleString('sv-SE')}. Bruttointäkt: ${money(gate.revenue)} per hemmamatch.`;}
function clubDeskTicketSave(value){if(!managerEmployed()||clubLocked())return clubSetPolicy('ticket',value);clubUI.drawer=null;clubSetPolicy('ticket',value);}
function clubDeskProfileSave(form){clubUI.drawer=null;managerProfile(form.elements.managerName.value,form.elements.identity.value);}
function clubDeskHeading(title,subtitle){return `<header class="cd-heading"><div><span class="cd-eyebrow">${trainingSafe(managerClub())} · ${seasonLabel()}</span><h1>${title}</h1><p>${subtitle}</p></div><div class="cd-watermark" aria-hidden="true">${clubCrest(managerClub(),'large')}</div></header>`;}
function clubDeskMetrics(items){return `<div class="cd-metrics">${items.map(([label,value,note,warn])=>`<div class="${warn?'cd-warning':''}"><span>${label}</span><strong>${value}</strong><small>${note||''}</small></div>`).join('')}</div>`;}
function clubDeskNotice(text){return text?`<p class="cd-notice" role="status">${trainingSafe(text)}</p>`:'';}
function clubDeskFrame(title,subtitle,metrics,body){return `<section class="club-workspace club-desk" data-context="${state.page}:${state.page==='finance'?clubUI.finance:state.page==='staff'?clubUI.staff:state.page==='manager'?clubUI.manager:'board'}">${clubDeskHeading(title,subtitle)}${clubDeskMetrics(metrics)}${body}${clubDeskDialog()}</section>`;}
function clubDeskMeter(label,used,limit,reserved=0){const percent=limit>0?Math.max(0,Math.min(100,used/limit*100)):100,total=used+reserved;return `<div class="cd-meter"><div><strong>${label}</strong><span>${careerMoney(used)} / ${careerMoney(limit)}</span></div><div class="cd-track" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="${Math.max(limit,total,1)}" aria-valuenow="${Math.max(0,total)}" aria-valuetext="${money(used)} samt ${money(reserved)} reserverat av ${money(limit)}"><i style="width:${percent}%"></i><b style="width:${Math.max(0,Math.min(100-percent,limit>0?reserved/limit*100:0))}%"></b></div><small>${reserved?`${money(reserved)} reserverat · `:''}${total>limit?'Överskrider med '+money(total-limit):money(limit-total)+' kvar'} / år</small></div>`;}
function clubDeskFinanceRows(){
 const o=state.clubOffice,f=clubForecast(),games=f.games;
 return [
  {id:'tickets',label:'Matchbiljetter',basis:`${f.homes} hemmamatcher × aktuell publikprognos`,annual:null,remaining:f.homes*clubGate().revenue},
  {id:'sponsor',label:'Sponsor & centrala avtal',basis:'Avtal med säsongens satsning inräknad',annual:o.sponsor*clubPriorityValue('sponsor')},
  {id:'players',label:'Spelarlöner',basis:'Nuvarande trupp och löneandelar i lån',annual:-annualWageCost()},
  {id:'staff',label:'Personallöner',basis:'Nuvarande personalavtal',annual:-clubStaffCost()},
  {id:'manager',label:'Huvudtränarens lön',basis:managerEmployed()?'Ditt aktiva tränaravtal':'Inget aktivt tränaravtal',annual:-managerSalary()},
  {id:'operations',label:'Klubbdrift',basis:'Drift med säsongens satsning inräknad',annual:-o.operations*clubPriorityValue('operations')},
  {id:'priority',label:'Säsongens satsning',basis:CLUB_PRIORITIES[o.priority].name,annual:-CLUB_PRIORITIES[o.priority].cost},
  {id:'matchday',label:'Matcher & resor',basis:`${f.homes} hemma · ${games-f.homes} borta`,annual:null,remaining:-f.homes*150000-(games-f.homes)*90000}
 ].map(row=>({...row,posted:o.totals[row.id]||0,remaining:row.remaining??row.annual*games/52}));
}
function clubDeskFinanceTable(){const rows=clubDeskFinanceRows(),f=clubForecast();return `<section class="cd-panel cd-table-panel"><header><div><h2>Intäkter, drift & prognos</h2><p>Återstående ${f.games} grundseriematcher · ${f.homes} hemma</p></div><button class="cd-link" onclick="clubDeskOpen('forecast')">Så räknas prognosen →</button></header><div class="cd-scroll" data-cd-scroll="finance"><table class="cd-table cd-finance-table"><thead><tr><th scope="col">Post</th><th scope="col">Årsnivå</th><th scope="col">Bokfört i år</th><th scope="col">Återstår · prognos</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${r.label}<small>${trainingSafe(r.basis)}</small></th><td>${r.annual===null?'Per match':money(r.annual)}</td><td class="${r.posted>0?'cd-positive':''}">${money(r.posted)}</td><td class="${r.remaining>0?'cd-positive':''}">${money(Math.round(r.remaining))}</td></tr>`).join('')}</tbody></table></div><footer><span>Prognosen bygger på oförändrad trupp och dagens publiknivå.</span><button class="cd-link" onclick="clubWorkspaceSet('finance','ledger')">Se transaktioner →</button></footer></section>`;}
function clubDeskBudgetAside(){const b=managerRecruitmentBudget(),o=state.clubOffice;return `<aside class="cd-aside"><header><h2>Utrymme att agera</h2><small>Åtaganden efter pågående bud</small></header><div data-cd-scroll="aside">${clubDeskMeter('Spelarlöner',annualWageCost(),wageBudget(),b.salaryReserved)}<dl class="cd-facts"><dt>Reserverade köpbud</dt><dd>${money(b.fees)}</dd><dt>Kassa efter köpbud</dt><dd>${money(b.availableCash)}</dd><dt>Reserverade köp- och lånelöner</dt><dd>${money(b.salaryReserved)}/år</dd><dt>Nästa säsongs löneutrymme</dt><dd>${money(b.futureRoom)}/år</dd></dl><button class="cd-outline" onclick="deskNavigate('transfers','deals')">Granska bud & avtal →</button>${clubDeskMeter('Personallöner',clubStaffCost(),o.staffLimit)}<button class="cd-link" onclick="deskNavigate('staff')">Se personalavtal →</button></div><footer>Reserverade bud är ännu inga bokförda utgifter. Nästa säsong räknar med kända avtal, bud och återvändande lån.</footer></aside>`;}
function clubDeskFinanceFooter(){const o=state.clubOffice,a=clubArena(),gate=clubGate(),p=CLUB_PRIORITIES[o.priority];return `<footer class="cd-inspector"><div><span class="cd-eyebrow">HEMMAARENAN</span><h2>${trainingSafe(a?.name||'Klubbens arena')}</h2><p>${o.capacity.toLocaleString('sv-SE')} platser · ${o.ticket} kr per biljett</p><small>${gate.attendance.toLocaleString('sv-SE')} beräknade åskådare vid aktuell efterfrågan</small></div><div><h3>NÄSTA HEMMAMATCH · PROGNOS</h3><p class="cd-large">${money(gate.revenue)}</p><small>Bruttointäkt från biljetter före matchkostnader.</small><button class="cd-link" onclick="clubDeskOpen('tickets')">Arena & biljettpris →</button></div><div><h3>SÄSONGENS SATSNING</h3><p><b>${p.name}</b> · ${careerMoney(p.cost)}/säsong</p><small>${o.priorityLockedYear===clubYear()?'Beslutad för hela säsongen.':'Välj inriktning och granska kostnaden innan du beslutar.'}</small><button class="cd-link" onclick="clubWorkspaceSet('finance','policy')">${o.priorityLockedYear===clubYear()?'Se satsningen':'Välj satsning'} →</button></div></footer>`;}
function clubDeskLedger(){
 const o=state.clubOffice,rows=o.ledger.filter(r=>clubUI.ledgerCategory==='all'||r.category===clubUI.ledgerCategory),sorted=clubUI.ledgerDirection===1?rows.slice().reverse():rows;
 return `<div class="cd-main"><section class="cd-panel cd-table-panel"><header><div><h2>Senaste transaktionerna</h2><p>${rows.length} sparade poster · senaste 240 i liggaren</p></div><label>Kategori<select onchange="clubWorkspaceSet('ledgerCategory',this.value)">${recruitOptions({all:'Alla poster',...CLUB_CATEGORIES},clubUI.ledgerCategory)}</select></label></header><div class="cd-scroll" data-cd-scroll="ledger"><table class="cd-table"><thead><tr><th><button onclick="clubUI.ledgerDirection*=-1;render()">Säsong / omgång ${clubUI.ledgerDirection===-1?'▾':'▴'}</button></th><th>Händelse</th><th>Belopp</th><th>Kassa efteråt</th></tr></thead><tbody>${sorted.map(e=>`<tr><td>${seasonLabel(e.year)}<small>Omgång ${e.round}</small></td><th scope="row">${trainingSafe(e.label)}<small>${CLUB_CATEGORIES[e.category]||trainingSafe(e.category)}</small></th><td class="${e.amount>0?'cd-positive':''}">${e.amount>0?'+':''}${money(e.amount)}</td><td>${money(e.balance)}</td></tr>`).join('')||'<tr><td colspan="4" class="cd-empty">Inga bokförda poster i urvalet. Inga historiska affärer återskapas.</td></tr>'}</tbody></table></div><footer>Liggaren visar registrerade händelser. Omgång är inte ett kalenderdatum.</footer></section><aside class="cd-aside"><header><h2>Säsongens bokföring</h2></header><div data-cd-scroll="aside"><dl class="cd-facts">${Object.entries(o.totals).map(([k,n])=>`<dt>${CLUB_CATEGORIES[k]||trainingSafe(k)}</dt><dd>${money(n)}</dd>`).join('')||'<dt>Inga transaktioner ännu.</dt>'}</dl>${o.archives.length?`<h3>Tidigare ekonomiår</h3>${o.archives.map(a=>`<p>${seasonLabel(a.year)}<small>${money(a.opening)} → ${money(a.closing)}</small></p>`).join('')}`:'<p>Tidigare ekonomiår visas efter säsongsövergången.</p>'}</div><footer>Säsongssummorna omfattar alla bokförda poster, även när äldre rader inte längre ryms i liggaren.</footer></aside></div>`;
}
function clubDeskPolicy(){const o=state.clubOffice,ids=clubPriorityChoices(),selected=ids.includes(clubUI.policy)?clubUI.policy:o.priority,p=CLUB_PRIORITIES[selected],locked=o.priorityLockedYear===clubYear();return `<div class="cd-main"><section class="cd-panel cd-table-panel"><header><div><h2>Välj klubbens satsning</h2><p>${locked?'Säsongens beslut är låst.':'Markera ett förslag för att granska effekten och kostnaden.'}</p></div></header><div class="cd-scroll" data-cd-scroll="policy"><table class="cd-table"><thead><tr><th>Satsning</th><th>Effekt i verksamheten</th><th>Kostnad / säsong</th></tr></thead><tbody>${ids.map(id=>`<tr class="${selected===id?'cd-selected':''}"><th scope="row"><button aria-pressed="${selected===id}" onclick="clubDeskPick('policy','${id}')">${CLUB_PRIORITIES[id].name}</button>${o.priority===id?'<small>Nuvarande inriktning</small>':''}</th><td>${CLUB_PRIORITIES[id].text}</td><td>${money(CLUB_PRIORITIES[id].cost)}</td></tr>`).join('')}</tbody></table></div><footer>Säsongens tillgängliga förslag bestäms inför varje nytt verksamhetsår.</footer></section><aside class="cd-aside"><header><h2>${p.name}</h2><small>${selected===o.priority?'Nuvarande satsning':'Förslag att ta ställning till'}</small></header><div data-cd-scroll="aside"><p>${p.text}</p><dl class="cd-facts"><dt>Extra kostnad / säsong</dt><dd>${money(p.cost)}</dd><dt>Fördelning per grundserieomgång</dt><dd>${money(Math.round(p.cost/52))}</dd><dt>Kostnad för återstående grundserie</dt><dd>${money(Math.round(p.cost*clubForecast().games/52))}</dd></dl><p>Beslutet låser inriktningen för hela säsongen. Kostnaden bokförs löpande, inte som en betalning nu.</p><button class="cd-primary" onclick="clubSetPolicy('priority','${selected}')" ${locked||clubLocked()||!managerEmployed()?'disabled':''}>${locked?'Låst för säsongen':'Bekräfta säsongens satsning'}</button></div><footer>Aktuell kassa och reserverade bud kontrolleras när du bekräftar.</footer></aside></div>`;}
function clubDeskFinance(){ensureClub();const o=state.clubOffice,f=clubForecast(),b=managerRecruitmentBudget();return clubDeskFrame('Klubbekonomi','Planera klubbens resurser med dagens åtaganden som grund.',[['Klubbkassa',careerMoney(state.money),'Bokförda pengar',state.money<0],['Prognos vid grundseriens slut',careerMoney(f.cash),`${f.games} matcher kvar · efter reserverade köpbud`,f.cash<0],['Ledigt löneutrymme',careerMoney(b.wageRoom),'/ år · efter reserverade spelarbud',b.wageRoom<0],['Personalutrymme',careerMoney(o.staffLimit-clubStaffCost()),'/ år · efter nuvarande personalavtal',o.staffLimit<clubStaffCost()]],`${clubWorkspaceTabs('finance',{budget:'Budget & intäkter',policy:'Säsongens satsning',ledger:'Transaktioner'})}${clubDeskNotice(o.message)}${clubUI.finance==='policy'?clubDeskPolicy():clubUI.finance==='ledger'?clubDeskLedger():`<div class="cd-main">${clubDeskFinanceTable()}${clubDeskBudgetAside()}</div>${clubDeskFinanceFooter()}`}`);}
function clubDeskStaffRows(){const o=state.clubOffice,key=clubUI.staffSort,query=clubUI.query.toLocaleLowerCase('sv');return (clubUI.staff==='candidates'?o.market.filter(s=>!o.taken.includes(s.personId)):state.staff).filter(s=>(clubUI.role==='all'||s.id===clubUI.role)&&(!query||`${s.name} ${CLUB_ROLES[s.id]} ${s.specialty}`.toLocaleLowerCase('sv').includes(query))).slice().sort((a,b)=>{const v=s=>key==='role'?CLUB_ROLES[s.id]:key==='expires'?s.expires??clubYear()+s.minYears:s[key];return clubUI.staffDirection*(typeof v(a)==='string'?v(a).localeCompare(v(b),'sv'):(v(a)||0)-(v(b)||0))||a.name.localeCompare(b.name,'sv');});}
function clubDeskStaffInspector(s){
 if(!s)return '<footer class="cd-inspector cd-empty"><h2>Ingen person i urvalet</h2><p>Bredda urvalet för att granska personal och avtal.</p></footer>';
 const candidate=clubUI.staff==='candidates',current=state.staff.find(p=>p.id===s.id),link={assistant:['Arbetsfördelning',"deskNavigate('staffReview')"],scout:['Scoutkontoret',"deskNavigate('transfers','missions')"],goalie:['Målvaktsuttagning',"deskNavigate('lines')"],junior:['Juniorverksamheten',"deskNavigate('juniors')"],physio:['Medicinskt team',"deskNavigate('medical')"]}[s.id];
 return `<footer class="cd-inspector"><div class="cd-person"><span class="cd-avatar" aria-hidden="true">${trainingSafe(s.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><div><span class="cd-eyebrow">${CLUB_ROLES[s.id]}</span><h2>${trainingSafe(s.name)}</h2><small>${trainingSafe(s.specialty)} · ${candidate?'Ledig kandidat':s.salary?'Avtal till sommaren '+s.expires:'Tillförordnad'}</small></div></div><div><h3>PÅVERKAN I KLUBBEN</h3><p>${CLUB_DESK_IMPACTS[s.id]}</p><small>${candidate?`Ersätter ${trainingSafe(current.name)} i samma roll.`:`Träning/rehab ${s.coaching}/20 · förmåga ${s.ability}/20 · potential ${s.potential}/20`}</small><button class="cd-link" onclick="${link[1]}">${link[0]} →</button></div><div><h3>AVTAL & NÄSTA STEG</h3><p><b>${s.salary?money(s.salary)+'/år':'Ingår i klubbdriften'}</b></p><small>${candidate?`Minst ${s.minYears} säsong${s.minYears>1?'er':''}. Avgångsersättning granskas före beslut.`:s.salary?'Förlängning är möjlig under avtalets sista säsong.':'Rekrytera en ersättare för att höja kompetensen.'}</small><div class="cd-actions">${candidate?`<button class="cd-outline" onclick="clubOpenOffer('${s.personId}')" ${clubLocked()||!managerEmployed()?'disabled':''}>Granska anställning</button>`:s.salary?`<button class="cd-outline" onclick="clubRenew('${s.id}')" ${s.expires>clubYear()+1||clubLocked()||!managerEmployed()?'disabled':''}>Förläng avtal</button><button class="cd-link" onclick="clubRelease('${s.id}')" ${clubLocked()||!managerEmployed()?'disabled':''}>Granska avslut →</button>`:`<button class="cd-outline" onclick="clubUI.role='${s.id}';clubUI.query='';clubWorkspaceSet('staff','candidates')">Hitta ersättare</button>`}</div></div></footer>`;
}
function clubDeskStaff(){
 ensureClub();const o=state.clubOffice,rows=clubDeskStaffRows(),candidate=clubUI.staff==='candidates',selected=rows.find(s=>s.personId===clubUI.staffPerson)||rows[0];clubUI.staffPerson=selected?.personId||null;
 const th=(key,label)=>`<th scope="col" aria-sort="${clubUI.staffSort===key?clubUI.staffDirection===1?'ascending':'descending':'none'}"><button onclick="clubDeskStaffSort('${key}')">${label} <span aria-hidden="true">${clubUI.staffSort===key?clubUI.staffDirection===1?'▴':'▾':'↕'}</span></button></th>`;
 const body=`${clubWorkspaceTabs('staff',{team:'Nuvarande personal',candidates:'Lediga kandidater'})}${clubDeskNotice(o.message)}<div class="cd-main cd-staff-main"><section class="cd-panel cd-table-panel"><header><h2>${candidate?'Hitta rätt kompetens':'Ditt tränarteam'}</h2><form class="cd-search" onsubmit="event.preventDefault();clubDeskStaffSearch(this)"><input name="query" type="search" aria-label="Sök personal" placeholder="Sök namn eller specialisering…" value="${trainingSafe(clubUI.query)}"><button type="submit">Sök</button></form><label><span class="cd-sr">Personalroll</span><select aria-label="Personalroll" onchange="clubWorkspaceSet('role',this.value)">${recruitOptions({all:'Alla roller',...CLUB_ROLES},clubUI.role)}</select></label></header><div class="cd-scroll" data-cd-scroll="staff"><table class="cd-table cd-staff-table"><thead><tr>${th('name','Person')}${th('role','Roll')}${th('coaching','Träning / rehab')}${th('ability','Förmågebedömning')}${th('potential','Potentialbedömning')}${th('salary','Årslön')}${th('expires','Avtal')}</tr></thead><tbody>${rows.map(s=>`<tr class="${selected===s?'cd-selected':''}" data-staff-id="${s.personId}"><th scope="row"><button class="cd-person-name" aria-pressed="${selected===s}" onclick="clubDeskPick('staffPerson','${s.personId}')">${trainingSafe(s.name)}</button><small>${trainingSafe(s.specialty)}</small></th><td>${CLUB_ROLES[s.id]}</td><td><span class="cd-skill" style="--skill:${s.coaching*5}%">${s.coaching}<small>/20</small></span></td><td>${s.ability}<small class="cd-inline">/20</small></td><td>${s.potential}<small class="cd-inline">/20</small></td><td>${s.salary?money(s.salary):'Ingår i drift'}</td><td>${candidate?'Minst '+s.minYears+' säsonger':s.salary?'Till '+s.expires:'Tillförordnad'}</td></tr>`).join('')||'<tr><td colspan="7" class="cd-empty">Inga personer matchar urvalet. <button class="cd-link" onclick="clubUI.role=\'all\';clubUI.query=\'\';render()">Rensa urval</button></td></tr>'}</tbody></table></div><footer><span>${rows.length} personer · fiktiv personal · kompetens 1–20</span><span>Markera en person för ansvar och avtalsbeslut.</span></footer></section></div>${clubDeskStaffInspector(selected)}`;
 return clubDeskFrame('Personal','Rätt kompetens runt laget. Tydligt ansvar och hållbara avtal.',[['Personallöner',careerMoney(clubStaffCost()),'/ år'],['Personalbudget',careerMoney(o.staffLimit),'/ år'],['Ledigt utrymme',careerMoney(o.staffLimit-clubStaffCost()),'/ år',o.staffLimit<clubStaffCost()],['Avtal att se över',state.staff.filter(s=>!s.salary||s.expires<=clubYear()+1).length,'Sista avtalsåret eller tillförordnad']],body);
}
function clubDeskConfidence(){const c=state.managerCareer,band=managerPressureBand(),recent=c.confidenceHistory.filter(h=>h.club===managerClub()).slice(0,4);return `<aside class="cd-aside"><header><h2>Styrelsens förtroende</h2><small>${managerEmployed()?'Ditt aktuella uppdrag':'Senast registrerade förtroende'}</small></header><div data-cd-scroll="aside"><div class="cd-confidence ${c.confidence<50?'cd-warning':''}"><strong>${c.confidence}<small>/100</small></strong><span>${band.label}</span></div><progress max="100" value="${c.confidence}" aria-label="Styrelseförtroende"></progress><p>${band.detail}</p>${c.pressure?.active?`<article class="cd-alert"><h3>Ultimatum</h3><p>${c.pressure.points||0} av ${c.pressure.targetPoints} poäng · ${c.pressure.played||0} av ${c.pressure.matches} matcher.</p><small>Registrerade ligamatcher avgör uppföljningen.</small></article>`:''}<h3>Senaste avstämningarna</h3>${recent.map(h=>`<div class="cd-checkin"><span>${h.date?calText(h.date):seasonLabel(h.year)}<small>${h.played} spelade matcher</small></span><b>${h.confidence}<small>${h.delta>0?'+':''}${h.delta}</small></b></div>`).join('')||'<p>Ingen avstämning registrerad ännu. Första ordinarie avstämningen sker efter fyra nya grundseriematcher.</p>'}<button class="cd-link" onclick="clubUI.manager='history';deskNavigate('manager')">Läs styrelsens besked →</button></div><footer>Förtroendet följs var fjärde grundseriematch. Resultat, form, ekonomi, talangutveckling och truppstöd påverkar.</footer></aside>`;}
function clubDeskGoalAction(g){return {league:['Granska tabellen',"deskNavigate('table')"],youth:['Planera laguttagningen',"deskNavigate('lines')"],finance:['Granska ekonomin',"deskNavigate('finance')"]}[g?.id]||['Granska ekonomin',"deskNavigate('finance')"];}
function clubDeskBoard(){
 ensureManager();const goals=boardProgress(),c=state.managerCareer,g=goals.find(g=>g.id===clubUI.goal)||goals[0],a=clubDeskGoalAction(g),identity=careerIdentity(managerClub()),young=Object.entries(state.boardPlan.youthAppearances).sort((a,b)=>b[1].games-a[1].games);
 const body=`${clubDeskNotice(c.pressure?.active?'Styrelsen har ställt ett ultimatum. Följ poängkravet och antalet återstående matcher.':'')}<div class="cd-main"><section class="cd-panel cd-table-panel"><header><div><h2>Säsongens uppdrag</h2><p>Markera ett mål för underlag och nästa steg.</p></div><small>${seasonLabel()}</small></header><div class="cd-scroll" data-cd-scroll="board"><table class="cd-table cd-goals-table"><thead><tr><th>Mål & prioritet</th><th>Läget just nu</th><th>Status</th></tr></thead><tbody>${goals.map(goal=>`<tr class="${g===goal?'cd-selected':''}"><th scope="row"><button aria-pressed="${g===goal}" onclick="clubDeskPick('goal','${goal.id}')">${trainingSafe(goal.title)}</button><small>${trainingSafe(goal.category)} · ${trainingSafe(goal.priority)}</small></th><td>${trainingSafe(goal.detail)}<progress max="1" value="${goal.progress}" aria-label="${trainingSafe(goal.title)}"></progress></td><td><span class="cd-status ${goal.met?'cd-positive':''}">${trainingSafe(goal.status)}</span></td></tr>`).join('')}</tbody></table><div class="cd-goal-underlay"><h3>${trainingSafe(identity.title)}</h3><p>${trainingSafe(identity.pitch)}</p>${g?.id==='youth'?`<h3>Talanger som fått istid</h3><p>Minst fem minuters registrerad istid krävs för att en match ska räknas.</p><table class="cd-table"><thead><tr><th>Spelare</th><th>Räknade matcher</th><th>Mål per spelare</th></tr></thead><tbody>${young.map(([id,p])=>`<tr><th>${playerReference(id,p.name)}</th><td>${p.games}</td><td>${state.boardPlan.offer.youthGames}</td></tr>`).join('')||'<tr><td colspan="3">Ingen kvalificerande match registrerad ännu.</td></tr>'}</tbody></table>`:''}</div></div><footer>Målen utvärderas vid grundseriens slut. Förtroendet följs även under säsongen.</footer></section>${clubDeskConfidence()}</div><footer class="cd-inspector"><div><span class="cd-eyebrow">VALT UPPDRAG</span><h2>${trainingSafe(g?.title||'Styrelsens mål')}</h2><small>${trainingSafe(g?.priority||'')}</small></div><div><h3>VAD STYRELSEN FÖRVÄNTAR SIG</h3><p>${trainingSafe(g?.text||'Inga mål registrerade.')}</p><small>${trainingSafe(g?.detail||'')}</small></div><div><h3>NÄSTA STEG</h3><p>${g?.id==='youth'?'Planera verklig matchtid för talangerna.':g?.id==='finance'?'Väg nya åtaganden mot kassa och löneutrymme.':'Jämför din placering med säsongens uppdrag.'}</p><button class="cd-outline" onclick="${a[1]}">${a[0]} →</button></div></footer>`;
 return clubDeskFrame('Styrelsens uppdrag','Följ målen, förstå förväntningarna och se vad du kan påverka.',[['Mål på rätt väg',goals.filter(g=>g.met).length+' / '+goals.length,'Aktuell status · inte en slututvärdering'],['Styrelseförtroende',c.confidence+' / 100',managerPressureBand().label,c.confidence<50],['Truppstöd',managerSquadSupport()+' / 100','Bygger på trivsel och lagmoral'],['Nuvarande avtal',managerEmployed()?'Till '+c.expires:'Inget aktivt',managerEmployed()?money(c.salary)+'/år':'Din karriär fortsätter']],body);
}
function clubDeskJobMarketOpen(){return state.season.phase==='preseason'||state.season.phase==='regular'&&!managerEmployed();}
function clubDeskManagerProfile(){const c=state.managerCareer,e=managerEvaluation(),form=managerRecentForm(5),support=managerSquadSupport();return `<div class="cd-main"><section class="cd-panel cd-table-panel"><header><div><h2>Så bedöms ditt arbete</h2><p>${trainingSafe(c.name)} · ${MANAGER_IDENTITIES[c.identity]}</p></div><button class="cd-outline" onclick="clubDeskOpen('profile')">Ändra tränarprofil</button></header><div class="cd-scroll cd-reading" data-cd-scroll="manager"><h3>Underlag vid nästa avstämning</h3><table class="cd-table"><thead><tr><th>Underlag</th><th>Läget nu</th><th>Vikt i löpande avstämning</th></tr></thead><tbody><tr><th>Styrelsens säsongsmål<small>Resultat 50 %, talangutveckling 20 %, ekonomi 30 % inom målbedömningen</small></th><td>${e.score} / 100</td><td>55 %</td></tr><tr><th>Form senaste fem ligamatcherna<small>${form.games?form.wins+' segrar · '+form.losses+' förluster på '+form.games+' matcher':'Inget matchunderlag ännu · neutral utgångspunkt används'}</small></th><td>${form.games?form.score+' / 100':'Ej bedömt'}</td><td>30 %</td></tr><tr><th>Truppstöd<small>Trivsel och lagmoral</small></th><td>${support} / 100</td><td>15 %</td></tr></tbody></table><p>Förtroendet uppdateras var fjärde grundseriematch och förändras stegvis. Vid säsongsslutet väger måluppfyllelse och eventuellt mästerskap in i slutbedömningen.</p><div class="cd-callout"><h3>Vad händer om förtroendet sjunker?</h3><p>Under 30 kan styrelsen ge ett femmatchersultimatum när minst åtta matcher har spelats i uppdraget. Under 15 kan uppdraget avslutas när minst tolv matcher har spelats. Ett aktivt ultimatum följer sina registrerade matcher och poängkrav.</p></div><h3>Ditt uppdrag</h3><p>${managerEmployed()?`${trainingSafe(managerClub())} · avtal till sommaren ${c.expires} · ${money(c.salary)}/år.`:c.status==='awaiting'?'Ditt tidigare avtal har löpt ut. Ta ställning till förlängningen eller sök ett nytt jobb.':'Du är tillgänglig för ett nytt uppdrag.'}</p>${c.decision&&managerEmployed()?'<p class="cd-alert">Styrelsen har beslutat att ditt uppdrag avslutas vid försäsongen.</p>':''}<p>Din tränaridentitet påverkar intervjuer. Rykte tjänas genom resultat över flera säsonger; namn och profilval ger inga extra meriter.</p></div><footer><button class="cd-link" onclick="deskNavigate('board')">Granska uppdragets mål →</button><button class="cd-link" onclick="clubWorkspaceSet('manager','jobs')">Till jobbmarknaden →</button></footer></section>${clubDeskConfidence()}</div>`;}
function clubDeskManagerJobs(){
 const c=state.managerCareer,open=clubDeskJobMarketOpen(),rows=open?c.jobs:[],j=rows.find(j=>j.id===clubUI.job)||rows[0],offer=j&&managerJobOffer(j.club);clubUI.job=j?.id||null;
 return `<div class="cd-main"><section class="cd-panel cd-table-panel"><header><div><h2>Lediga tränarjobb</h2><p>${open?'Granska klubben innan du möter styrelsen.':'Jobbmarknaden öppnar vid försäsongen eller när du står utan uppdrag under grundserien.'}</p></div>${open?`<button class="cd-outline" onclick="managerJobWeek()" ${c.moveYear===clubYear()?'disabled':''}>Uppdatera jobbmarknaden</button>`:''}</header><div class="cd-scroll" data-cd-scroll="jobs"><table class="cd-table"><thead><tr><th>Klubb</th><th>Bakgrund</th><th>Rykte · riktmärke</th><th>Status</th></tr></thead><tbody>${rows.map(job=>`<tr class="${j===job?'cd-selected':''}"><th scope="row"><button aria-pressed="${j===job}" onclick="clubDeskPick('job',${trainingSafe(JSON.stringify(job.id))})">${trainingSafe(job.club)}</button><small>${leagueName(job.club)} · senaste placering ${job.rank}</small></th><td>${trainingSafe(job.reason)}</td><td>${job.min} / 100</td><td>${{open:'Öppet uppdrag',rejected:'Avslag',filled:'Tillsatt'}[job.status]||trainingSafe(job.status)}</td></tr>`).join('')||'<tr><td colspan="4" class="cd-empty">Inga tillgängliga jobb att granska just nu.</td></tr>'}</tbody></table></div><footer>Du kan tillträda ett nytt jobb en gång per säsong. Världens trupper och historia fortsätter.</footer></section><aside class="cd-aside"><header><h2>${j?trainingSafe(j.club):'Nästa uppdrag'}</h2><small>${j?leagueName(j.club):'Din karriär fortsätter'}</small></header><div data-cd-scroll="aside">${j?`${clubCrest(j.club,'large')}<p>${trainingSafe(offer.pitch)}</p><dl class="cd-facts"><dt>Klubbkassa</dt><dd>${careerMoney(offer.cash)}</dd><dt>Lönebudget / år</dt><dd>${careerMoney(offer.wageLimit)}</dd><dt>Truppstorlek</dt><dd>${state.clubRosters[j.club]?.length||0} spelare</dd></dl><p>En intervju som passar klubbens inriktning kan väga upp ett lägre rykte. Du granskar avtalet innan du tillträder.</p><button class="cd-outline" onclick="managerInterview(${trainingSafe(JSON.stringify(j.id))})" ${j.status!=='open'||c.moveYear===clubYear()||clubLocked()?'disabled':''}>Möt styrelsen →</button>`:'<p>Avsluta ditt nuvarande uppdrag eller vänta till nästa försäsong för att söka vidare.</p>'}</div><footer>Klubbresurser och väntande spelarbud kontrolleras igen innan ett klubbyte genomförs.</footer></aside></div>`;
}
function clubDeskManagerHistory(){const c=state.managerCareer;return `<div class="cd-main"><section class="cd-panel cd-table-panel"><header><h2>Styrelsens besked</h2><small>${c.reviews.length} sparade avstämningar</small></header><div class="cd-scroll cd-reading" data-cd-scroll="reviews">${c.reviews.map(r=>`<details class="cd-review"><summary><span>${trainingSafe(r.title)}</span><small>${seasonLabel(r.year)} · ${trainingSafe(r.club)} · förtroende ${r.confidence}/100</small></summary><p>${trainingSafe(r.text).replace(/\n/g,'<br>')}</p></details>`).join('')||'<p class="cd-empty">Första avstämningen kommer efter fyra nya grundseriematcher.</p>'}</div></section><aside class="cd-aside"><header><h2>Din karriärväg</h2></header><div data-cd-scroll="aside">${c.history.map(h=>`<article class="cd-timeline"><small>${seasonLabel(h.year)}</small><h3>${trainingSafe(h.club)}</h3><p>${h.kind==='season'?`Plats ${h.position} · ${h.goals}/${h.total} mål uppnådda${h.champion?' · Mästare':''}`:h.kind==='appointment'?`Tillträdde från ${trainingSafe(h.from)}. Avtal till ${h.expires}.`:trainingSafe(h.reason)}</p></article>`).join('')||'<p>Din historia börjar här. Tidigare säsonger finns kvar under Säsong & historik.</p>'}</div><footer><button class="cd-link" onclick="deskNavigate('season')">Säsongsarkivet →</button></footer></aside></div>`;}
function clubDeskManager(){
 ensureManager();ensureClub();const c=state.managerCareer,employed=managerEmployed();
 return clubDeskFrame('Min karriär',`${trainingSafe(c.name)} · ${employed?'Huvudtränare i '+trainingSafe(managerClub()):c.status==='awaiting'?'Avtalsbeslut väntar':'Tillgänglig för nytt uppdrag'}`,[['Rykte',c.reputation+' / 100',managerLabel()],['Styrelseförtroende',c.confidence+' / 100',managerPressureBand().label,c.confidence<50],['Tränaravtal',employed?'Till '+c.expires:'Inget aktivt',employed?money(c.salary)+'/år':'Sök ett nytt uppdrag'],['Tränaridentitet',MANAGER_IDENTITIES[c.identity],'Används i anställningsintervjuer']],`${clubDeskNotice(c.message)}${c.renewal&&!c.decision?`<div class="cd-offer-banner"><span><strong>Erbjudande från ${trainingSafe(managerClub())}</strong> · förlängning till ${c.renewal.expires} · ${money(c.renewal.salary)}/år</span><button class="cd-outline" onclick="clubDeskOpen('renewal')">Granska förlängning →</button></div>`:''}${clubWorkspaceTabs('manager',{profile:'Profil & uppdrag',jobs:'Jobbmarknad',history:'Besked & historik'})}${clubUI.manager==='jobs'?clubDeskManagerJobs():clubUI.manager==='history'?clubDeskManagerHistory():clubDeskManagerProfile()}`);
}
function clubDeskDialog(){
 const kind=state.page==='staff'&&state.clubOffice?.offer?'offer':state.page==='manager'&&state.managerCareer?.interview?'interview':clubUI.drawer;if(!kind)return '';
 const o=state.clubOffice,c=state.managerCareer;let title='',body='';
 if(kind==='offer'){title='Granska personalavtal';body=clubDeskNotice(o.message)+clubOfferView();}
 else if(kind==='interview'){title='Anställningsintervju';body=clubDeskNotice(c.message)+managerInterviewView();}
 else if(kind==='tickets'){const gate=clubGate();title='Arena & biljettpris';body=`${arenaDetails()}<form oninput="clubDeskTicketPreview(this)" onsubmit="event.preventDefault();clubDeskTicketSave(this.elements.ticket.value)"><label>Biljettpris<select name="ticket">${recruitOptions({160:'160 kr',220:'220 kr',280:'280 kr',340:'340 kr'},o.ticket)}</select></label><output>Beräknad publik: ${gate.attendance.toLocaleString('sv-SE')} / ${o.capacity.toLocaleString('sv-SE')}. Bruttointäkt: ${money(gate.revenue)} per hemmamatch.</output><p>Högre pris minskar efterfrågan. Publiken påverkas också av klubbens supportrar, tabellplacering och säsongens satsning. Arenans kapacitet sätter taket.</p><button class="cd-primary" ${clubLocked()||!managerEmployed()?'disabled':''}>Spara biljettpris</button></form>`;}
 else if(kind==='forecast'){const f=clubForecast();title='Så räknas prognosen';body=`<dl class="cd-facts"><dt>Klubbkassa nu</dt><dd>${money(state.money)}</dd><dt>Återstående intäkter</dt><dd>+${money(Math.round(f.income))}</dd><dt>Återstående kostnader</dt><dd>−${money(Math.round(f.cost))}</dd><dt>Reserverade köpbud</dt><dd>−${money(f.reserved)}</dd><dt>Prognos vid grundseriens slut</dt><dd>${money(f.cash)}</dd></dl><p>Oförändrad trupp, publiknivå och satsning antas under de återstående ${f.games} grundseriematcherna. Framtida slutspel, nya värvningar och styrelsetilldelning ingår inte. Budens framtida löner ingår först när spelaren ansluter.</p><p>Årslöner, drift och sponsoravtal fördelas över 52 grundserieomgångar. Slutspel tillför separata matchintäkter och matchkostnader. Prognosen är ett planeringsunderlag, ingen garanterad kassa.</p>`;}
 else if(kind==='profile'){title='Din tränarprofil';body=`<form onsubmit="event.preventDefault();clubDeskProfileSave(this)"><label>Namn<input name="managerName" maxlength="40" value="${trainingSafe(c.name)}"></label><label>Tränaridentitet<select name="identity">${recruitOptions(MANAGER_IDENTITIES,c.identity)}</select></label><p>Identiteten används i intervjuer. Profilval ändrar inte dina meriter eller spelarnas attribut.</p><button class="cd-primary">Spara profil</button></form>`;}
 else if(kind==='renewal'){if(!c.renewal||c.decision)return '';title='Ditt nya tränaravtal';body=`<h3>${trainingSafe(managerClub())}</h3><dl class="cd-facts"><dt>Avtal till</dt><dd>Sommaren ${c.renewal.expires}</dd><dt>Årslön</dt><dd>${money(c.renewal.salary)}</dd></dl><p>Lönen betalas av klubben. Förlängningen kan undertecknas vid säsongsavslutet eller under försäsongen.</p><button class="cd-primary" onclick="clubUI.drawer=null;managerAcceptRenewal()" ${!['review','preseason'].includes(state.season.phase)||clubLocked()?'disabled':''}>Acceptera förlängningen</button>`;}
 else return '';
 return `<dialog id="club-dialog" class="cd-dialog" aria-labelledby="cd-dialog-title" data-context="${kind}:${kind==='offer'?o.offer.personId+':'+o.offer.type:kind==='interview'?c.interview.id+':'+c.interview.stage:''}" oncancel="event.preventDefault();clubDeskClose()"><header><h2 id="cd-dialog-title">${title}</h2><button aria-label="Stäng dialog" onclick="clubDeskClose()">×</button></header><div class="cd-dialog-body">${body}</div></dialog>`;
}
