const test=require('node:test');
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');

test('fixture results open recorded reports and preserve report and club context',()=>{
 const {run,get}=boot();
 run('startCareerWithClub("HV71");globalThis.fixture=state.schedule.find(g=>[g.home,g.away].includes(managerClub()));globalThis.other=fixture.home===managerClub()?fixture.away:fixture.home;fixture.played=true;fixture.homeGoals=4;fixture.awayGoals=2;globalThis.report={id:"club-report",date:fixture.date,club:managerClub(),opponent:other,friendly:false,finished:true,year:state.season.year,stage:"Grundserie",own:fixture.home===managerClub()?4:2,against:fixture.home===managerClub()?2:4,shots:[],events:[],units:[],players:[]};state.analysis.matches.unshift(report,{...report,id:"second-report"});openClubContext(other);');
 assert.match(get('#content').innerHTML,/#match\/club-report/);
 assert.match(get('#content').innerHTML,/>4–2<\/a>/);
 const date=run('state.calendar.date');
 run('matchesOpenReport("club-report");matchesUI.analysis="events";matchesOpenReport("second-report");deskBack();');
 assert.equal(run('state.analysis.selected'),'club-report');
 assert.equal(run('matchesUI.analysis'),'events');
 run('deskBack();');
 assert.equal(run('state.page'),'clubDetail');
 assert.equal(run('state.clubBrowser.club'),run('other'));
 assert.equal(run('state.calendar.date'),date);
 run('state.analysis.matches=[];render();');
 assert.match(get('#content').innerHTML,/Detaljrapport saknas/);
 assert.doesNotMatch(get('#content').innerHTML,/#match\/club-report/);
 run('matchesUI.calendar="fixtures";matchesUI.fixtures="played";deskNavigate("calendar");');
 assert.match(get('#content').innerHTML,/#club\//);
 run('state.analysis.matches=[report];render();');
 assert.match(get('#content').innerHTML,/#match\/club-report/);
});

test('club links preserve working context and historical evidence without hidden information',()=>{
 const app=boot(),{run,get}=app;
 run('startCareerWithClub("HV71");deskNavigate("leagueStats");leagueStatsUI.query="center";leagueStatsUI.sort="age";globalThis.year=state.season.year;');
 get('#content').scrollTop=420;
 run('openClubContext("Luleå Hockey");');
 assert.equal(run('state.page'),'clubDetail');
 assert.match(get('#content').innerHTML,/Spelartrupp/);
 assert.match(get('#content').innerHTML,/data-player-id/);
 const roster=run('JSON.stringify(state.clubRosters["Luleå Hockey"])');
 run('globalThis.id=state.clubRosters["Luleå Hockey"][0].id;deskOpenPlayer(id);deskBack();');
 assert.equal(run('state.clubBrowser.club'),'Luleå Hockey');
 assert.equal(run('state.page'),'clubDetail');
 assert.equal(run('JSON.stringify(state.clubRosters["Luleå Hockey"])'),roster);
 run('openClubContext("HV71");deskBack();');
 assert.equal(run('state.clubBrowser.club'),'Luleå Hockey');
 run('deskBack();');
 assert.equal(run('leagueStatsUI.query'),'center');
 assert.equal(run('leagueStatsUI.sort'),'age');
 assert.equal(get('#content').scrollTop,420);
 run('state.leagueStatistics.archives.unshift({year:year-1,rows:{old:{id,name:"Historisk spelare",pos:"C",club:"Luleå Hockey",league:"HA",stage:"regular",games:9}},recorded:{regular:{HA:1}},missing:{HA:0}});state.world.membership["Luleå Hockey"]="SHL";openClubContext("Luleå Hockey",{year:year-1});');
 assert.match(get('#content').innerHTML,/Historisk spelare/);
 assert.match(get('#content').innerHTML,/Hockeyallsvenskan/);
 assert.doesNotMatch(get('#content').innerHTML,/Serieschema|Aktuell klubb/);
 run('openLeagueContext("HA",year-1,"Luleå Hockey");');
 assert.equal(run('leagueStatsUI.league'),'HA');
 assert.equal(run('leagueStatsUI.year'),String(run('year-1')));
 assert.equal(run('leagueStatsUI.club'),'Luleå Hockey');
 run('deskBack();');
 assert.equal(run('state.clubBrowser.year'),run('year-1'));
 assert.equal(run('openLeagueContext("SHL",1900)'),false);
 run('openClubContext("Luleå Hockey",{year:1900});');
 assert.match(get('#content').innerHTML,/Ligatillhörighet ej registrerad/);
 assert.doesNotMatch(get('#content').innerHTML,/Serieschema|data-player-id/);
 assert.equal(run('clubReference("<okänd klubb>")'),'&lt;okänd klubb&gt;');
 // Public club view does not depend on scout knowledge, hidden health or attributes.
 run('openClubContext("Luleå Hockey");globalThis.before=clubContextView();state.clubRosters["Luleå Hockey"][0].morale=3;state.clubRosters["Luleå Hockey"][0].potential=99;');
 assert.equal(run('clubContextView()'),run('before'));
 run('state.clubRosters["Luleå Hockey"]=state.clubRosters["Luleå Hockey"].filter(p=>p.id!==id);render();');
 assert.ok(!get('#content').innerHTML.includes('data-player-id="'+run('id')+'"'));
 run('save();');
 const loaded=boot(app.storage.value);
 assert.equal(loaded.run('state.clubBrowser.club'),'Luleå Hockey');
 assert.equal(loaded.run('state.page'),'clubDetail');
});
