const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot();const run=app.run;
run(`startCareerWithClub('HV71');ensureAnalysis();globalThis.sample=(id,n=8)=>({id,year:state.season.year,club:managerClub(),opponent:'Testlag',finished:true,units:[],players:[],shots:Array.from({length:n},()=>({dangerous:true,side:'opponent',x:80,y:50,time:60,name:'Test',outcome:'save'})),events:[]});state.analysis.matches=[sample('base'),{...sample('partial',100),partial:true}];coachAdopt('defense');`);
assert.equal(run('coachFocus().baseline.length'),1);
assert.equal(run('coachFocus().baseline[0].value'),8);
run(`state.training.plan=[{type:'recovery',intensity:'light'},{type:'skills',intensity:'normal'},{type:'matchprep',intensity:'light'}];state.training.day=0;calendarTrainingPlan=()=>{};coachPlan();`);
assert.equal(run('state.training.plan[0].type'),'recovery');
assert.equal(run('state.training.plan[1].type'),'tactics');
assert.equal(run('state.training.plan[2].type'),'matchprep');
assert.equal(run('state.calendar.plans[coachFocus().planned].type'),'tactics');
run(`coachTrainingDone({date:state.calendar.date,type:'skills',trained:20});coachTrainingDone({date:state.calendar.date,type:'tactics',trained:20,resting:5});coachTrainingDone({date:state.calendar.date,type:'tactics',trained:20});`);
assert.equal(run('coachFocus().sessions.length'),1);
run(`coachMatchDone(sample('base'));coachMatchDone({...sample('partial'),partial:true});coachMatchDone({...sample('friendly'),friendly:true});coachMatchDone({...sample('other'),club:'Other'});coachMatchDone(sample('one',4));coachMatchDone(sample('one',4));`);
assert.equal(run('coachFocus().results.length'),1);
run(`coachMatchDone(sample('two',6));coachMatchDone(sample('three',5));coachMatchDone(sample('four',1));save();`);
assert.equal(run('coachFocus().results.length'),3);
assert.match(run('coachCycleView()'),/5.0/);
assert.match(run('managerDeskView()'),/3\/3 matcher/);
const resumed=boot(app.storage.value);
assert.equal(resumed.run('coachFocus().results.length'),3);
assert.equal(resumed.run('coachFocus().sessions.length'),1);
resumed.run('state.season.year++');assert.equal(resumed.run('coachFocus()'),null);
assert.ok(!run('trainingView()+statisticsView()').includes('NaN'));
console.log('PASS: evidence exclusions, protected calendar days, persisted plan, actual-session tracking, deduplicated three-match review, dashboard, save/reload and season isolation.');
const daily=boot();daily.run(`startCareerWithClub('HV71');ensureAnalysis();state.analysis.matches=[{id:'baseline',finished:true,club:managerClub(),year:state.season.year,shots:[],events:[]}];coachAdopt('attack');setTrainingSession(state.training.day,'type','skills');`);
assert.equal(daily.run('runTrainingSession()'),true);
assert.equal(daily.run('coachFocus().sessions.length'),1);
assert.ok(daily.run('coachFocus().sessions[0].trained')>0);
daily.run('save()');assert.equal(boot(daily.storage.value).run('coachFocus().sessions.length'),1);
console.log('PASS: advancing a real training day records participating players and persists progress.');
