const assert=require('node:assert/strict');const {boot}=require('./scripts/career-test-fixture.cjs');const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');state.calendar.date=calendarTarget();startMatch();pauseMatch();
 globalThis.unit=analysisUnitRecord(analysisUnits()[0]);Object.assign(unit,{seconds:240,dangerFor:1,dangerAgainst:4});
 globalThis.base=JSON.parse(JSON.stringify(analysisSnapshot()));base.finished=true;
 globalThis.samples=[0,1,2].map(i=>({...JSON.parse(JSON.stringify(base)),id:'coach-evidence-'+i,units:[{...unit}]}));`);
assert.ok(r('analysisAdvice(samples).some(t=>t.includes("i 3 av 3 matcher"))'));
r('samples[1].units[0].dangerFor=6;samples[2].units[0].dangerFor=6;samples[0].units[0].dangerAgainst=99');
assert.ok(!r('analysisAdvice(samples).some(t=>t.includes("har släppt till fler"))'),'one extreme match cannot drive a recurring-deficit recommendation');
r('samples[0].strengthPartial=true;samples[1].partial=true;samples[2].abandoned=true');
assert.ok(r('analysisAdvice(samples).includes("Inga kompletta tävlingsmatcher att bedöma ännu.")'));
r('state.live.finished=true;state.analysis.matches=samples;coachAdopt("defense")');
assert.equal(r('coachFocus()'),null,'ineligible evidence cannot initiate focus');
r('samples.forEach(m=>{m.strengthPartial=false;m.partial=false;m.abandoned=false;});state.analysis.matches=[...samples,samples[0]];coachAdopt("defense")');
assert.equal(r('coachFocus().baseline.length'),3,'duplicate report excluded from baseline');
r('globalThis.next={...JSON.parse(JSON.stringify(base)),id:"followup",strengthPartial:true};coachMatchDone(next)');
assert.equal(r('coachFocus().results.length'),0,'partial strength exposure does not advance follow-up');
r('next.strengthPartial=false;coachMatchDone(next);coachMatchDone(next);coachTrainingDone({date:state.calendar.date,trained:15,resting:3,type:"tactics"});save()');
assert.equal(r('coachFocus().results.length'),1);assert.equal(r('coachFocus().sessions.length'),1);
const loaded=boot(app.storage.value);assert.equal(loaded.run('JSON.stringify(coachFocus())'),r('JSON.stringify(coachFocus())'));
console.log('PASS: consistent recurring advice, outlier rejection, incomplete evidence exclusion, deduplicated real focus adoption, follow-up, training log and persistence.');
