const test=require('node:test');
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');

test('news identities, match links, contextual performance, save/load and legacy text',()=>{
 const app=boot(),{run,get}=app;
 run('startCareerWithClub("HV71");globalThis.a=managerRoster()[0];globalThis.b=managerRoster()[1];b.name=a.name;globalThis.aId=a.id;globalThis.bId=b.id;');
 run('feedbackNews("named-report",managerClub(),"development",playerHeadline(a," följs upp"),[playerMention(a)," och ",playerMention(b)," deltog."]);deskNavigate("news");');
 const html=get('#content').innerHTML;
 assert.ok(html.includes('data-player-id="'+run('aId')+'"'));
 assert.ok(html.includes('data-player-id="'+run('bId')+'"'));
 assert.equal(run('state.managerFeedback.news[0].title'),run('a.name+" följs upp"'));
 assert.equal(run('state.managerFeedback.news[0].bodyParts[2].playerId'),run('bId'));
 run('managerMessage("structured-test",playerHeadline(b," behöver besked"),[playerMention(b)," har en fråga."],"Assistent",{playerId:bId,link:"player"});openManagerMessage(state.training.messages[0].id);');
 assert.ok(get('#content').innerHTML.includes('data-player-id="'+run('bId')+'"'));
 run('rivalEvent("Luleå","injury",playerHeadline(b," saknas"),[playerMention(b)," följs av läkare."]);');
 assert.equal(run('state.rivals.events[0].titleParts[0].playerId'),run('bId'));
 assert.equal(run('typeof state.rivals.events[0].title'),'string');

 run('globalThis.event={type:"goal",scorerId:aId,scorer:a.name,assists:[{id:bId,name:b.name}],own:1,against:0,text:a.name};');
 const goal=run('matchEventReference(event)');
 assert.ok(goal.includes('data-player-id="'+run('aId')+'"'));
 assert.ok(goal.includes('data-player-id="'+run('bId')+'"'));
 assert.match(goal,/1–0/);
 assert.equal(run('matchEventReference({type:"goal",text:"Gammal målnotering"})'),'Gammal målnotering');
 assert.match(run('matchEventReference({type:"goal",text:"Målskytt saknas",assists:[{id:bId,name:b.name}]})'),/data-player-id=/);
 run('globalThis.originalLive=state.live;state.live={analysis:{events:[event]}};');
 const scoreboard=run('matchScoringView()');
 assert.ok(scoreboard.includes('data-player-id="'+run('aId')+'"'));
 assert.ok(scoreboard.includes('data-player-id="'+run('bId')+'"'));
 run('state.live=originalLive;');

 run('state.analysis.matches.unshift({id:"saved-evidence",finished:true,shots:[],events:[],units:[],tacticalReviews:[],year:2026,date:"2026-09-02",club:"Historisk klubb",opponent:"Luleå",own:2,against:1,stage:"Grundserie",players:[{id:aId,name:a.name,pos:a.pos,seconds:840,goals:1,assists:0,shots:2}],performance:{rows:[{id:aId,name:a.name,pos:a.pos,club:"Historisk klubb",seconds:840,goals:1,assists:0,shots:2,stars:4}]}});');
 const profile=run('playerPerformanceView(aId)');
 assert.match(profile,/Historisk klubb/);
 assert.match(profile,/saved-evidence/);
 assert.match(profile,/Matchbetyg 4 av 5/);
 assert.match(profile,/14:00/);
 assert.match(run('playerPerformanceView("unknown-id")'),/Inga matchrapporter/);
 run('deskOpenPlayer(aId);profileWorkspace.tab="performance";render();');
 assert.match(get('#content').innerHTML,/Senaste registrerade matcher/);
 run('matchesOpenReport("saved-evidence");');
 assert.equal(run('state.analysis.selected'),'saved-evidence');
 run('deskBack();');
 assert.equal(run('profileWorkspace.tab'),'performance');
 // Drop only this synthetic report before save validation; fixture lacks full match schema.
 run('state.analysis.matches=[];state.analysis.selected="latest";save();');
 const loaded=boot(app.storage.value);
 assert.equal(loaded.run('state.managerFeedback.news.find(n=>n.key==="named-report").bodyParts[2].playerId'),run('bId'));
 assert.match(loaded.run('feedbackNewsView()'),/data-player-id=/);
 assert.equal(loaded.run('playerReferenceText("Äldre fritext utan ID")'),'Äldre fritext utan ID');
 assert.equal(loaded.run('playerReferenceText([null,{text:"<script>"}])'),'&lt;script&gt;');
 run('deskOpenPlayer(aId);profileWorkspace.tab="development";globalThis.beforeLines=JSON.stringify(state.lines);playerLineupContext(aId);');
 assert.equal(run('state.page'),'lines');
 assert.equal(run('lineupUI.slot.type'),'goalie');
 assert.equal(run('JSON.stringify(state.lines)'),run('beforeLines'));
 run('deskBack()');
 assert.equal(run('state.selectedPlayer'),run('aId'));
 assert.equal(run('profileWorkspace.tab'),'development');
 run('managerMessage("medical-context","Medicinsk bedömning","Underlag","Läkare",{playerId:aId,link:"medical"});messageOpenContext(state.training.messages[0].id);');
 assert.equal(run('profileWorkspace.tab'),'development');
 assert.equal(run('state.selectedPlayer'),run('aId'));
 run('globalThis.prospect=Object.values(state.clubAI.clubs).flatMap(c=>c.academy.roster)[0];globalThis.prospectId=prospect.id;nhlUI.tab="board";nhlUI.query=prospect.name;deskOpenPlayer(prospectId);');
 assert.equal(run('playerIdentity(prospectId).restricted'),true);
 assert.equal(run('findPlayerAnywhere(prospectId)'),null);
 assert.match(get('#content').innerHTML,/ingår inte i seniorernas rekryteringsmarknad/);
 assert.doesNotMatch(get('#content').innerHTML,/developmentCeiling|attributeGrowth|hubTransferForm/);
 run('deskBack()');
 assert.equal(run('nhlUI.tab'),'board');
 assert.equal(run('nhlUI.query'),run('prospect.name'));
});
