const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r("startCareerWithClub('HV71');deskNavigate('lines');ensureLines();");
let html=r('lineupBoardView()');
assert.ok(html.includes('fm-workspace')&&html.includes('fm-roster-table')&&html.includes('lineup-rink'));
assert.ok(!html.includes('chemistry-table-scroll'),'long analysis is outside the selection workspace');
r("lineupSelectUnit('line',3);lineupPickSlot('forwards',9);globalThis.before=state.lines.forwards.slice();lineupPlace(state.lines.forwards[0]);");
assert.equal(r('state.lines.forwards[9]'),r('before[0]'));
assert.equal(r('state.lines.forwards[0]'),r('before[9]'));
assert.equal(r('new Set([...state.lines.forwards,...state.lines.defense]).size'),18);
r("globalThis.pick=state.lines.forwards[9];selectPlayer(pick)");
assert.ok(r("playerView().includes('fm-attributes')"));
r("profileWorkspace.tab='contract';openContractNegotiation(pick)");
assert.ok(r("playerView().includes('renewalSalary')"));
r("cancelContractNegotiation();profileWorkspace.tab='development'");
assert.ok(r("playerView().includes('individual-training')"));
r("deskBack('lines')");assert.equal(r('state.page'),'lines');assert.equal(r('lineupUI.line'),3);
r("desktopOrder('tempo','high');desktopOrder('shiftLength','short');desktopOrder('shotChoice','patient');save()");
const loaded=boot(app.storage.value);
assert.equal(loaded.run('state.tacticalPlan.tempo'),'high');
assert.equal(loaded.run('state.tacticalPlan.shiftLength'),'short');
assert.equal(loaded.run('state.lines.forwards[9]'),r('pick'));
r("desktopOrder('shiftLength','invalid')");assert.equal(r('state.tacticalPlan.shiftLength'),'short');
r("state.calendar.date=calendarTarget();startMatch();globalThis.clock=state.live.clock;desktopOrder('tempo','low')");
assert.equal(r('state.live.running'),false);assert.equal(r('state.live.clock'),r('clock'));
r("lineupWorkspace='analysis';deskNavigate('lines')");assert.ok(r("lineupBoardView().includes('chemistry-table-scroll')"));
console.log('PASS: unified selection, actual swaps, saved orders and roster, profile contract/development actions, back navigation and live pause.');
