const assert=require('node:assert/strict');const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;r(`startCareerWithClub('HV71');globalThis.p=managerRoster().find(p=>p.pos==='C');globalThis.original=JSON.stringify(p.attributes);delete p.developmentModel;ensureDevelopment(p);`);
assert.equal(r('JSON.stringify(p.attributes)'),r('original'));
r(`globalThis.cap=JSON.stringify(p.developmentModel.ceiling);globalThis.key='shooting';for(let i=0;i<2000;i++)developmentAdvance(p,key,100);`);
assert.equal(r('p.attributes.shooting'),r('p.developmentModel.ceiling.shooting'));
assert.equal(r('p.trainingProgress.shooting'),0);assert.equal(r('JSON.stringify(p.developmentModel.ceiling)'),r('cap'));
r('save()');const loaded=boot(app.storage.value);assert.equal(loaded.run(`JSON.stringify(managerRoster().find(q=>q.id===${JSON.stringify(r('p.id'))}).developmentModel)`),r('JSON.stringify(p.developmentModel)'));
r(`globalThis.j=createJunior('C',true);ensureDevelopment(j);globalThis.jcap=JSON.stringify(j.developmentModel.ceiling);delete j.academy;ensureDevelopment(j);`);assert.equal(r('JSON.stringify(j.developmentModel.ceiling)'),r('jcap'));
r(`globalThis.make=()=>({id:'curve-test',name:'Test',pos:'C',age:24,attributes:Object.fromEntries(Object.keys(SKATER_ATTRIBUTES).map(k=>[k,10])),attributeGrowth:6,trainingProgress:{}});globalThis.s=make();ensureDevelopment(s);s.developmentModel.ceiling.shooting=16;s.attributes.shooting=10;globalThis.fast=developmentRate(s,'shooting');s.attributes.shooting=15;`);assert.ok(r('developmentRate(s,"shooting")')<r('fast'));
r(`globalThis.v=make();v.age=35;ensureDevelopment(v);v.developmentModel.peakOffset=0;globalThis.beforeAge=v.age;state.season.year++;developmentBirthday(v);globalThis.after=JSON.stringify(v);developmentBirthday(v);`);assert.equal(r('JSON.stringify(v)'),r('after'));assert.equal(r('v.age'),r('beforeAge+1'));assert.ok(r('v.attributes.acceleration')<10);assert.equal(r('v.attributes.decisions'),10);
r(`globalThis.g={...make(),id:'keeper',pos:'MV',age:29,attributes:Object.fromEntries(Object.keys(GOALIE_ATTRIBUTES).map(k=>[k,10]))};ensureDevelopment(g);g.developmentModel.peakOffset=0;s.developmentModel.peakOffset=0;`);assert.ok(r('developmentPeak(g,"movement")')>r('developmentPeak(s,"acceleration")'));
r(`for(let i=0;i<20;i++){state.season.year++;developmentBirthday(v);for(const key of Object.keys(v.attributes))developmentAdvance(v,key,50);}`);assert.equal(r('Object.entries(v.attributes).every(([k,n])=>n>=1&&n<=v.developmentModel.ceiling[k])'),true);assert.ok(r('v.developmentModel.history.length')<=24);
// Verify the two actual training entry points share the same cap and accumulator.
r(`globalThis.a=make();globalThis.b=make();a.developmentModel=JSON.parse(JSON.stringify(ensureDevelopment(a)));b.developmentModel=JSON.parse(JSON.stringify(a.developmentModel));a.attributes.shooting=b.attributes.shooting=a.developmentModel.ceiling.shooting-1;b.aiTrainingKey='shooting';trainingGrowth(a,'shooting',50);rivalGrow(b,50,'Färjestad BK');`);assert.equal(r('a.trainingProgress.shooting'),r('b.trainingProgress.shooting'));
assert.equal(r('a.attributes.shooting'),r('b.attributes.shooting'));
// Match development now depends on environment, role fit and meaningful exposure.
r(`globalThis.pathPlayer=make();pathPlayer.age=19;ensureDevelopment(pathPlayer);globalThis.good=developmentMatchContext(pathPlayer,1200,{level:matchAttributeRating(pathPlayer),roleFit:1,environment:'junior',coach:15});globalThis.bad=developmentMatchContext(pathPlayer,300,{level:20,roleFit:.6,environment:'senior',coach:10});developmentPathRecord(pathPlayer,good,1200,'Kontrollerad miljö')`);
assert.ok(r('good.factor')>r('bad.factor'),'appropriate role, level and minutes should create a better development environment');
assert.equal(r('pathPlayer.developmentModel.pathHistory[0].environment'),'junior');
assert.equal(r('pathPlayer.developmentModel.pathHistory.length'),1);
r("globalThis.rolePlayer=make();rolePlayer.id='role-creator';state.clubRosters[managerClub()].push(rolePlayer);rolePlayer.pos='C';rolePlayer.developmentFocus='Balanserad';rolePlayer.trainingProgress={passing:40,vision:20,decisions:30};setDevelopmentRolePlan(rolePlayer.id,'creator');globalThis.rolePlan=developmentRoleProgress(rolePlayer)");
assert.equal(r('rolePlayer.developmentRolePlan'),'creator');assert.match(r('rolePlan.plan.name'),/spelfördelare/);assert.ok(['passing','vision','decisions'].includes(r("trainingTarget(rolePlayer,'skills')")));
// Role development plans guide balanced training without replacing explicit individual focus.
r(`globalThis.roleDev=make();roleDev.id='role-first-pass';state.clubRosters[managerClub()].push(roleDev);roleDev.club=managerClub();roleDev.pos='B';roleDev.developmentFocus='Balanserad';roleDev.trainingProgress={passing:40,vision:70,decisions:80};setDevelopmentRolePlan(roleDev.id,'firstPass');globalThis.roleProgress=developmentRoleProgress(roleDev);globalThis.roleTarget=trainingTarget(roleDev,'skills')`);
assert.equal(r('roleDev.developmentRolePlan'),'firstPass');assert.ok(r("['passing','vision','decisions'].includes(roleTarget)"));assert.equal(r('roleProgress.plan.name'),'Bli uppspelsback');
r("roleDev.developmentFocus='Skott'");assert.equal(r("trainingTarget(roleDev,'skills')"),'shooting','explicit focus overrides the role plan');
r("globalThis.veteran=make();veteran.age=34;veteran.pos='B';Object.assign(veteran.attributes,{skating:9,passing:15,vision:15,decisions:16,positioning:16,checking:15,puckControl:11});globalThis.roleRec=veteranRoleRecommendation(veteran)");
assert.ok(r('roleRec&&DEVELOPMENT_ROLE_PLANS[roleRec.to]'));assert.ok(r("roleRec.value>=12"));
r("globalThis.young=make();young.age=21;young.pos='C';young.developmentRolePlan='puckWinner';young.developmentReview={baseline:{...young.attributes}};Object.assign(young.attributes,{passing:16,vision:16,decisions:16,puckControl:15});globalThis.youngRec=youngRoleRecommendation(young)");
assert.ok(r("youngRec&&DEVELOPMENT_ROLE_PLANS[youngRec.to]&&youngRec.growth>=2"));
console.log('PASS: migration preserves attributes; immutable ceilings; plateau; save/reload; promotion; deterministic birthdays; differentiated ageing; 20-year bounds; same AI/own growth kernel.');
const career=boot();career.run(`startCareerWithClub('HV71');globalThis.ages=Object.fromEntries([...Object.values(state.clubRosters).flat(),...state.juniors.roster,...state.playerWorld.freeAgents].map(p=>[p.id,p.age]));state.season.phase='review';state.season.boardResult=[];beginPreseason();`);
assert.equal(career.run(`Object.values(state.clubRosters).flat().concat(state.juniors.roster,state.playerWorld.freeAgents).filter(p=>ages[p.id]!==undefined).every(p=>p.age===ages[p.id]+1)`),true);
console.log('PASS: actual preseason transition ages retained senior, junior and free-agent players exactly once.');
