const assert=require('node:assert/strict');const {boot}=require('./scripts/career-test-fixture.cjs');const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');state.calendar.date=calendarTarget();startMatch();pauseMatch();
 globalThis.unit=analysisUnitRecord(analysisUnits()[0]);unit.seconds=240;unit.dangerFor=1;unit.dangerAgainst=3;
 globalThis.base=JSON.parse(JSON.stringify(analysisSnapshot()));base.finished=true;
 globalThis.samples=[0,1,2].map(i=>({...structuredClonePlaceholder(base),id:'evidence-'+i,date:calAdd(state.calendar.date,-i),units:[{...unit,label:'Kedja '+(i+1)}]}));`.replace('structuredClonePlaceholder(base)','JSON.parse(JSON.stringify(base))'));
assert.equal(r('formationEvidence(samples).rows.length'),1,'same players combine despite different line numbers');
assert.equal(r('formationEvidence(samples).rows[0].signal'),'Återkommande underskott');
assert.equal(r('formationEvidence(samples).rows[0].seconds'),720);
r(`samples[0].units[0]={...unit,dangerFor:0,dangerAgainst:30};samples[1].units[0]={...unit,dangerFor:3,dangerAgainst:1};samples[2].units[0]={...unit,dangerFor:3,dangerAgainst:1};`);
assert.equal(r('formationEvidence(samples).rows[0].signal'),'Blandat utfall','one bad outlier cannot establish recurrent deficit');
r('samples[0].partial=true');assert.equal(r('formationEvidence(samples).excluded'),1);assert.equal(r('formationEvidence(samples).rows[0].signal'),'Mer underlag behövs');
r(`samples[0].partial=false;samples[0].abandoned=true;samples[1].strengthPartial=true;samples[2].finished=false;`);
assert.equal(r('formationEvidence(samples).rows.length'),0);
r(`samples=samples.map((m,i)=>({...m,partial:false,abandoned:false,strengthPartial:false,finished:true,units:[{...unit,seconds:i===0?30:240}]}));`);
assert.equal(r('formationEvidence(samples).rows[0].measured'),2);
assert.equal(r('formationEvidence(samples).rows[0].signal'),'Mer underlag behövs');
r(`samples=samples.map(m=>({...m,units:[{...unit},{...unit,key:'pk-combination',kind:'pk',dangerFor:0,dangerAgainst:2}]}));state.analysis.matches=JSON.parse(JSON.stringify(samples));save();`);
assert.equal(r('formationEvidence(samples).rows.length'),2,'PK is a separate combination');
assert.equal(r('formationEvidence([...samples,samples[0]]).rows[0].games.length'),3,'duplicate report does not inflate evidence');
const reload=boot(app.storage.value);assert.equal(reload.run('JSON.stringify(formationEvidence(analysisSamples()))'),r('JSON.stringify(formationEvidence(analysisSamples()))'));
r("matchesUI.analysis='trends';globalThis.before=JSON.stringify(state);globalThis.html=matchesAnalysisView();");
assert.equal(r('JSON.stringify(state)'),r('before'),'reading trends is side effect free');
assert.ok(r('html.includes("Återkommer matchbilden?")&&html.includes("matchesOpenReport")'));
r("matchesOpenReport('evidence-1')");assert.equal(r('state.analysis.selected'),'evidence-1');assert.equal(r('matchesUI.analysis'),'overview');
console.log('PASS: actual formation record integration, repeated results versus outliers, exposure thresholds, incomplete report exclusion, strength grouping, persistence and report navigation.');
