'use strict';
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;r("startCareerWithClub('HV71');globalThis.p=state.juniors.roster[0];juniorSet(p.id,'path','guest');juniorSet(p.id,'load','rest')");
r("juniorTraining({type:'skills',intensity:'hard'},'rest');juniorTraining({type:'skills',intensity:'hard'},'rest');");
assert.equal(r('state.juniors.aTraining[p.id].sessions'),0);
assert.equal(r('state.juniors.aTraining[p.id].restSessions'),1);
assert.equal(r('state.juniors.aTraining[p.id].hardSessions'),0);
r("juniorSet(p.id,'load','normal');juniorTraining({type:'recovery',intensity:'light'},'recovery');juniorTraining({type:'skills',intensity:'hard'},'participated');save()");
assert.equal(r('state.juniors.aTraining[p.id].sessions'),1);
assert.equal(r('state.juniors.aTraining[p.id].recoverySessions'),1);
assert.equal(r('state.juniors.aTraining[p.id].hardSessions'),1);
const loaded=boot(app.storage.value);loaded.run("juniorTraining({type:'skills',intensity:'hard'},'participated')");assert.equal(loaded.run('state.juniors.aTraining[state.juniors.roster[0].id].sessions'),1);
r("managerJ20PathSet(p.id,'balanced');state.juniors.matches=Array.from({length:5},(_,i)=>({year:state.season.year,j20:true,date:state.calendar.date,players:[{id:p.id,seconds:3600,goals:0,assists:0}]}))");
assert.equal(r("managerJ20PathStatus(p).milestones[0].done"),true,'goalies need meaningful match exposure, not scoring');
assert.doesNotMatch(r('managerJ20PathStatus(p).milestones[0].detail'),/p\/match/);
r('state.juniors.matches.forEach(m=>m.players[0].seconds=60)');assert.equal(r('managerJ20PathStatus(p).milestones[0].done'),false,'token appearances do not qualify');
r("state.juniors.aTraining[p.id]={sessions:30,profileGain:1};");
assert.equal(r('managerJ20PathStatus(p).milestones[1].done'),false,'unverified legacy attendance is not a training milestone');
r("juniorTraining({type:'skills',intensity:'normal'},'migrated')");
assert.equal(r('state.juniors.aTraining[p.id].legacySessions'),30);
assert.equal(r('state.juniors.aTraining[p.id].sessions'),1);
// Opening an individual must select the player view, even after reading reports.
r("juniorOpenWorkspace('history');deskNavigate('home');juniorSelect(p.id)");
assert.equal(r('developmentUI.juniorTab'),'players');assert.equal(r('state.juniors.selected'),r('p.id'));
assert.doesNotMatch(r('developmentJuniorsView()'),/class="dv-panel junior-world"/);
r("juniorOpenWorkspace('lineup')");assert.match(r('developmentJuniorsView()'),/J20-kedjor & matchtrupp/);assert.doesNotMatch(r('developmentJuniorsView()'),/J20-poängliga/);
r("juniorOpenWorkspace('calendar')");assert.match(r('developmentJuniorsView()'),/J20-kalender/);assert.doesNotMatch(r('developmentJuniorsView()'),/J20-kedjor & matchtrupp/);
r("juniorOpenWorkspace('league')");assert.match(r('developmentJuniorsView()'),/J20-poängliga/);assert.doesNotMatch(r('developmentJuniorsView()'),/J20-kalender/);
console.log('PASS: real attendance/rest/injury-safe evidence, idempotence/reload, positional milestones, legacy evidence and distinct junior workspaces.');
