const assert=require('node:assert/strict');const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');state.calendar.date=calendarTarget();startMatch();pauseMatch();
 globalThis.old=state.lines.forwards[0];globalThis.replacement=state.lines.forwards[3];
 state.live.minute=5;state.live.analysis.strengthSeconds.even=240;
 state.live.analysis.shots=[{side:'own',situation:'even',dangerous:true},{side:'opponent',situation:'pk',dangerous:true}];
 matchReplace('forwards',0,replacement);`);
assert.equal(r('state.live.tacticalReviews.length'),1);
assert.equal(r('state.lines.forwards[0]'),r('replacement'));
assert.equal(r('state.lines.forwards[3]'),r('old'));
assert.equal(r('tacticalReviewLineupChanges(state.live.tacticalReviews[0].before.lineup,state.live.tacticalReviews[0].after.lineup).length'),2,'both affected chains captured');
assert.equal(r('state.live.tacticalReviews[0].baseline.against'),0,'boxplay excluded');
r(`matchReplace('forwards',0,replacement);changeLinePlayer('forwards',99,old);`);
assert.equal(r('state.live.tacticalReviews.length'),1,'no-op and invalid changes do not add decisions');
r(`matchOrder('forecheck','passive');globalThis.keeper=goalies().find(p=>!samePlayerId(p.id,state.lines.goalie)&&medicalAvailable(p));changeGoalie(keeper.id);`);
assert.equal(r('state.live.tacticalReviews.length'),1,'one stoppage is one combined decision');
assert.equal(r('state.live.tacticalReviews[0].after.goalie'),undefined);
assert.equal(r('state.live.tacticalReviews[0].after.lineup.goalie.id'),r('String(keeper.id)'));
r(`state.live.minute=9;state.live.analysis.strengthSeconds.even=420;state.live.analysis.shots.push({side:'opponent',situation:'even',dangerous:true});
 globalThis.view=tacticalReviewView(tacticalReviewSnapshot());`);
assert.ok(r('view.includes("Målvakt:")&&view.includes("Kedja 1:")&&view.includes("Forecheck:")'));
assert.ok(r('view.includes("hela laget vid lika styrka")'));
assert.equal(r('tacticalReviewSnapshot()[0].result.seconds'),180);
assert.equal(r('tacticalReviewSnapshot()[0].result.dangerAgainst'),1);
r('save()');const restored=boot(app.storage.value);
assert.equal(restored.run('JSON.stringify(tacticalReviewSnapshot())'),r('JSON.stringify(tacticalReviewSnapshot())'));
r(`state.live.finished=true;globalThis.report=JSON.parse(JSON.stringify(analysisSnapshot()));globalThis.archived=tacticalReviewView(report.tacticalReviews);
 playerById(replacement).name='Ändrat namn';`);
assert.equal(r('tacticalReviewView(report.tacticalReviews)'),r('archived'),'archive retains names and decision context');
assert.equal(r("tacticalReviewLineupChanges(undefined,tacticalReviewLineup()).length"),0,'legacy reports gain no fabricated changes');
// Real production continuation: submitted lineup reaches engine plans and the recorded interval grows.
const live=boot(),q=live.run;q(`startCareerWithClub('HV71');state.calendar.date=calendarTarget();startMatch();pauseMatch();
 globalThis.next=state.lines.forwards[3];matchReplace('forwards',0,next);startMatch();
 for(let i=0;i<300&&state.live.running;i++)liveStep();`);
assert.equal(q('studioEngine().teams[0].plan.forwards[0]'),q('next'));
assert.ok(q('tacticalReviewSnapshot()[0].result.seconds')>0);
assert.equal(q('tacticalReviewSnapshot()[0].result.for'),q("state.live.analysis.shots.filter(s=>s.side==='own'&&s.situation==='even').length"));
console.log('PASS: real substitutions, grouped orders/keeper change, strength accounting, engine continuation and persistent decision history.');
