'use strict';
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r("startCareerWithClub('HV71');ensureSpecialTeams();globalThis.ids=state.lines.forwards.slice(0,3);globalThis.p=playerById(ids[0]);globalThis.q=playerById(ids[1]);q.name=p.name;specialUI={unit:'pp1',slot:0,query:''};specialPlace(p.id);save();");
assert.equal(r('state.specialTeams.pp1[0]'),r('p.id'));
assert.match(r('lineupWorkload(p)'),/PP1/);
// Start the production engine; selection uses the same stored special teams.
r('state.calendar.date=calendarTarget();startMatch();pauseMatch();globalThis.clock=JSON.stringify([state.live.minute,state.live.second,state.live.running]);');
assert.match(r('lineupWorkload(p)'),/Ork nu .*Istid/);
assert.equal(r('studioEngine().teams[0].plan.pp1[0]'),r('p.id'));
assert.match(r('specialBoardView()'),/Sorterat efter/);
r('lineupRinkView();specialBoardView();');
assert.equal(r('JSON.stringify([state.live.minute,state.live.second,state.live.running])'),r('clock'));
r('globalThis.steps=0;while(!state.live.finished&&steps++<65000){if(!state.live.running){while(medicalPending())medicalDecisionAccept();startMatch();}studioStep();}');
assert.equal(r('state.live.finished'),true);
assert.equal(r('state.live.analysis.saved'),true);
assert.ok(r('Object.values(state.live.analysis.players).some(p=>p.roleUsage?.some(s=>s>0))'), 'production shifts record role placement');
assert.ok(r('state.analysis.history[state.analysis.matches[0].id].ratings.length>0'), 'numeric grades are archived with the actual game');
assert.doesNotMatch(r('lineupWorkload(p)'),/Ork nu/,'finished-match energy must not masquerade as current energy');
assert.ok(r('state.analysis.matches[0].units.length')>0);
r('save()');const reload=boot(app.storage.value);
assert.equal(reload.run('JSON.stringify(state.specialTeams)'),r('JSON.stringify(state.specialTeams)'));
assert.equal(reload.run('lineupCombinationEvidence("forward",state.lines.forwards.slice(0,3),"Kedja 1")'),r('lineupCombinationEvidence("forward",state.lines.forwards.slice(0,3),"Kedja 1")'));
// Controlled evidence boundaries: identical names stay separate; only matching IDs combine.
r(`globalThis.key=JSON.stringify(['forward',...ids.map(String).sort()]);
globalThis.unit={key,kind:'forward',ids:[...ids],names:ids.map(id=>playerById(id).name),seconds:240,dangerFor:1,dangerAgainst:3};
globalThis.sample=i=>({id:'sample-'+i,club:managerClub(),year:state.season.year,date:calAdd(state.calendar.date,-i),finished:true,units:[{...unit,label:'Kedja '+(i+1)}]});
state.analysis.matches=[sample(0),sample(1),sample(2)];`);
assert.match(r('lineupCombinationEvidence("forward",ids,"Kedja 1")'),/Återkommande underskott/);
assert.match(r('lineupCombinationEvidence("forward",ids,"Kedja 1")'),/12:00/);
assert.ok(r('formationEvidenceView(state.analysis.matches).includes("#player/"+encodeURIComponent(p.id))'));
assert.ok(r('formationEvidenceView(state.analysis.matches).includes("#player/"+encodeURIComponent(q.id))'));
r(`state.analysis.matches.push({...sample(0),id:'future',date:calAdd(state.calendar.date,1)},{...sample(0),id:'other',club:'Other'},{...sample(0),id:'old',year:state.season.year-1},{...sample(0),id:'partial',partial:true},sample(0));`);
assert.equal(r('lineupEvidenceSamples().length'),3);
r('state.analysis.matches.push(sample(3),sample(4),sample(5));');
assert.equal(r('lineupEvidenceSamples().length'),5);
assert.match(r('lineupCombinationEvidence("forward",[...ids.slice(0,2),"different-id"],"Ny kedja")'),/Ingen registrerad/);
r('state.analysis.matches[0].units[0]={...unit,ids:undefined,names:["<old>","same","same"]};');
assert.match(r('formationEvidenceView([state.analysis.matches[0]])'),/&lt;old&gt;/);
assert.doesNotMatch(r('formationEvidenceView([state.analysis.matches[0]])'),/#player\//,'legacy names without IDs must not be guessed');
r('globalThis.before=JSON.stringify(state);lineupCombinationEvidence("forward",ids,"Kedja 1");formationEvidenceView(state.analysis.matches);lineupWorkload(p);');
assert.equal(r('JSON.stringify(state)'),r('before'),'reading observations never simulates or alters saved data');
console.log('PASS: selection → production match → saved evidence → reload; current workload, ID links, historical boundaries and read-only views. Automated workflow, not visual playtesting.');
