'use strict';
// This workspace reads the career's existing social systems. Only their actions
// can change trust, roles, promises or relationships.
const LOCKER_TABS={situation:'Läget i gruppen',leadership:'Roller & ledarskap',promises:'Löften & samtal'};
const LOCKER_COLUMNS={name:'Spelare',role:'Roll i gruppen',mood:'Humör',trust:'Förtroende',attention:'Vad påverkar?'};
function lockerMainTab(){return lockerUI.tab==='relationships'?'leadership':lockerUI.tab==='history'?'promises':Object.hasOwn(LOCKER_TABS,lockerUI.tab)?lockerUI.tab:'situation';}
function lockerSet(key,value){
 const choices={tab:[...Object.keys(LOCKER_TABS),'relationships','history'],filter:['all','concerns'],group:['all','captain','leaders','young']};
 if(key==='player'){
  const p=managerRoster().find(p=>samePlayerId(p.id,value));if(!p)return;
  lockerUI.scroll=document.getElementById('locker-scroll')?.scrollTop||0;lockerUI.player=p.id;
 }else{if(!choices[key]?.includes(value))return;lockerUI[key]=value;lockerUI.scroll=0;lockerUI.detail=null;}
 render();queueInterfaceSave();
 if(key==='player')document.getElementById('locker-player-'+lockerUI.player)?.focus?.({preventScroll:true});
}
function lockerSearch(value,start){lockerUI.query=String(value).slice(0,100);lockerUI.scroll=0;render();const el=document.getElementById('locker-search');el?.focus?.();el?.setSelectionRange?.(start,start);queueInterfaceSave();}
function lockerReset(){Object.assign(lockerUI,{query:'',filter:'all',group:'all',sort:'attention',direction:-1,scroll:0});render();queueInterfaceSave();}
function lockerSort(key){if(!Object.hasOwn(LOCKER_COLUMNS,key))return;lockerUI.direction=lockerUI.sort===key?-lockerUI.direction:key==='name'||key==='role'?1:-1;lockerUI.sort=key;lockerUI.scroll=0;render();queueInterfaceSave();document.getElementById('locker-sort-'+key)?.focus?.();}
function lockerSelected(){return managerRoster().find(p=>samePlayerId(p.id,lockerUI.player))||lockerRows()[0]?.p||managerRoster()[0]||null;}
function lockerRole(p){
 if(samePlayerId(p.id,state.locker.captainId))return 'Lagkapten';
 if(relationshipLeaders().some(l=>l.p===p))return 'Informell ledare';
 if(state.relationships?.mentors.some(m=>m.status==='active'&&samePlayerId(m.mentorId,p.id)))return 'Fadder';
 return p.age<=23?'Ung spelare':'Truppspelare';
}
function lockerTrustLabel(n){return socialTrustText(n).replace(/ förtroende$/i,'');}
function lockerMood(p){const n=p.happiness??70;return {value:Math.round(n),text:n>=75?'Nöjd':n>=65?'Stabil':n>=45?'Missnöjd':'Mycket missnöjd',tone:n>=65?'good':'warning'};}
function lockerPlayerPromises(p){return lockerPromises().filter(x=>x.p===p&&!x.q.resolved);}
function lockerFactors(p){
 const items=[],requests=lockerRequests(p),conflict=state.relationships?.cases.find(c=>samePlayerId(c.playerId,p.id));
 if(requests.length)items.push({kind:'Samtal',text:'Samtal väntar på ditt svar',detail:requests[0].title,action:'request',request:requests[0].id,priority:100});
 if(conflict)items.push({kind:'Rollkonflikt',text:conflict.status==='following'?'En plan för rollen följs upp':'Frågor om spelarens roll',detail:conflict.evidence,action:'relationships',priority:90+Math.min(9,Math.floor(conflict.tension/10))});
 for(const {q} of lockerPlayerPromises(p)){
  const rule=rolePromiseRule(q),left=Math.max(0,rule.total-(q.games||0)),need=Math.max(0,rule.required-(q.qualified||0));
  items.push({kind:'Löfte',text:need?'Ett istidslöfte följs upp':'Istidsmålet är nått',detail:rolePromiseProgress(q),action:'promise',priority:need>left?95:need===left&&need?85:need?70:30});
 }
 for(const reason of lockerConcerns(p))items.push({kind:reason.includes('istid')?'Istid':reason.includes('förtroende')?'Förtroende':'Trivsel',text:reason,detail:reason.includes('istid')?`${p.social.missed} missade rollförväntningar i följd. ${squadRoleExpectation(p,p.promisedRole||p.squadRole)}`:reason.includes('förtroende')?`Förtroende ${Math.round(p.social.trust)}/100. Läs tidigare samtal innan du ger ett nytt besked.`:`Trivsel ${lockerMood(p).value}/100. Ett enskilt samtal kan ge mer sammanhang.`,action:'talk',priority:reason.includes('istid')?80:60});
 return items.sort((a,b)=>b.priority-a.priority);
}
function lockerAttention(){return managerRoster().map(p=>({p,items:lockerFactors(p)})).filter(r=>r.items.length).sort((a,b)=>b.items[0].priority-a.items[0].priority||a.p.social.trust-b.p.social.trust||a.p.name.localeCompare(b.p.name,'sv'));}
function lockerRows(){
 const q=lockerUI.query.trim().toLocaleLowerCase('sv'),leaders=relationshipLeaders().map(l=>l.p);
 return managerRoster().map(p=>({p,role:lockerRole(p),mood:lockerMood(p),items:lockerFactors(p)})).filter(r=>(!q||r.p.name.toLocaleLowerCase('sv').includes(q))&&(lockerUI.filter!=='concerns'||r.items.length)&&(lockerUI.group==='all'||lockerUI.group==='captain'&&samePlayerId(r.p.id,state.locker.captainId)||lockerUI.group==='leaders'&&leaders.includes(r.p)||lockerUI.group==='young'&&r.p.age<=23)).sort((a,b)=>{
  const key=lockerUI.sort,cmp=key==='name'?a.p.name.localeCompare(b.p.name,'sv'):key==='role'?a.role.localeCompare(b.role,'sv'):key==='mood'?a.mood.value-b.mood.value:key==='trust'?a.p.social.trust-b.p.social.trust:(a.items[0]?.priority||0)-(b.items[0]?.priority||0);
  return cmp*lockerUI.direction||a.p.name.localeCompare(b.p.name,'sv');
 });
}
function lockerFilters(){return `<div class="ld-filters"><label class="ld-search">${deskIcon('search')}<input id="locker-search" type="search" maxlength="100" value="${trainingSafe(lockerUI.query)}" placeholder="Sök spelare" aria-label="Sök i omklädningsrummet" oninput="lockerSearch(this.value,this.selectionStart)"></label><select aria-label="Roll i gruppen" onchange="lockerSet('group',this.value)">${[['all','Alla i gruppen'],['captain','Lagkapten'],['leaders','Informella ledare'],['young','Unga spelare · ≤23 år']].map(([k,v])=>`<option value="${k}" ${lockerUI.group===k?'selected':''}>${v}</option>`).join('')}</select><button aria-pressed="${lockerUI.filter==='concerns'}" onclick="lockerSet('filter','${lockerUI.filter==='all'?'concerns':'all'}')">Behöver följas upp</button>${lockerUI.query||lockerUI.filter!=='all'||lockerUI.group!=='all'?'<button class="ld-link" onclick="lockerReset()">Återställ</button>':''}<span>${lockerRows().length} / ${managerRoster().length}</span></div>`;}
function lockerSituation(){
 const selected=lockerSelected(),rows=lockerRows();
 return `<div class="ld-roster">${lockerFilters()}<div class="ld-scroll" id="locker-scroll" onscroll="lockerUI.scroll=this.scrollTop"><table><colgroup><col style="width:25%"><col style="width:19%"><col style="width:13%"><col style="width:14%"><col style="width:29%"></colgroup><thead><tr>${Object.entries(LOCKER_COLUMNS).map(([k,v])=>`<th aria-sort="${lockerUI.sort===k?lockerUI.direction===1?'ascending':'descending':'none'}"><button id="locker-sort-${k}" onclick="lockerSort('${k}')">${v}<span>${lockerUI.sort===k?lockerUI.direction===1?'↑':'↓':'↕'}</span></button></th>`).join('')}</tr></thead><tbody>${rows.map(({p,role,mood,items})=>`<tr data-locker-player="${p.id}" class="${p===selected?'ld-selected':''}"><th scope="row"><button id="locker-player-${p.id}" aria-pressed="${p===selected}" onclick="lockerSet('player','${p.id}')"><strong>${trainingSafe(p.name)}</strong><small>${trainingSafe(p.pos)} · ${p.age} år</small></button></th><td>${role}</td><td><span class="ld-${mood.tone}" title="Trivsel ${mood.value}/100">${mood.text}</span></td><td><span class="${p.social.trust<50?'ld-warning':''}">${lockerTrustLabel(p.social.trust)}</span><small>${Math.round(p.social.trust)}/100</small></td><td>${items.length?trainingSafe(items[0].text):'<span class="ld-muted">Inga noterade problem</span>'}${items.length>1?`<small>+ ${items.length-1} till i spelarens underlag</small>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="ld-empty">Inga spelare i urvalet. Ändra sökningen eller återställ filtren.</td></tr>'}</tbody></table></div><footer class="ld-table-note">Humör visar trivsel i klubben. Förtroende gäller ditt ledarskap. Markera en spelare för underlaget.</footer></div>`;
}
function lockerCaptainStrip(){const p=managerRoster().find(p=>samePlayerId(p.id,state.locker.captainId));return `<footer class="ld-captain"><div><small>LAGKAPTEN</small><strong>${p?trainingSafe(p.name):'Ingen kapten utsedd'}</strong></div><p>${p?`Förtroende: ${lockerTrustLabel(p.social.trust).toLowerCase()} · ${Math.round(p.social.trust)}/100. ${p.social.lastResponse?trainingSafe(p.social.lastResponse):'Inget enskilt samtal registrerat ännu.'}`:'Utse en kapten under Roller & ledarskap.'}</p>${p?`<button class="ld-link" onclick="lockerOpenDetail('talk','${p.id}')">Prata med kaptenen →</button>`:''}</footer>`;}
function lockerAttentionView(){const rows=lockerAttention();return `<aside class="ld-attention"><header><h2>Behöver din uppmärksamhet</h2><span>${rows.length} spelare</span></header><div class="ld-attention-list">${rows.slice(0,8).map(({p,items})=>{const item=items[0];return `<article><small>${item.kind}</small><h3>${trainingSafe(p.name)}</h3><p>${trainingSafe(item.text)}</p><small class="ld-evidence">${trainingSafe(item.detail)}</small><button class="ld-link" onclick="lockerFollow('${p.id}')">${item.action==='request'?'Svara på samtalet':item.action==='promise'?'Följ upp löftet':item.action==='relationships'?'Följ konflikten':'Visa situationen'} →</button></article>`}).join('')||`<div class="ld-calm"><span aria-hidden="true">✓</span><h3>Inget behöver hanteras just nu</h3><p>Inga öppna samtal, löften eller noterade problem i truppen. Fortsätt följa hur roller och förtroende utvecklas.</p></div>`}${rows.length>8?`<button class="ld-link" onclick="lockerShowAttention()">Visa alla ${rows.length} spelare →</button>`:''}</div><footer>Uppföljningen bygger på spelarens faktiska situation. Ett samtal ersätter inte ett istidslöfte.</footer></aside>`;}
function lockerShowAttention(){Object.assign(lockerUI,{tab:'situation',query:'',group:'all',filter:'concerns',scroll:0,detail:null});render();queueInterfaceSave();}
function lockerFollow(id){const p=managerRoster().find(p=>samePlayerId(p.id,id));if(!p)return;const item=lockerFactors(p)[0];if(!item)return;lockerUI.player=p.id;if(item.action==='request')lockerOpenRequest(item.request);else if(item.action==='relationships')lockerSet('tab','relationships');else lockerOpenDetail(item.action,p.id);}
function lockerLeadership(){
 const roster=managerRoster().slice().sort((a,b)=>Number(samePlayerId(b.id,state.locker.captainId))-Number(samePlayerId(a.id,state.locker.captainId))||b.social.leadership-a.social.leadership||a.name.localeCompare(b.name,'sv')),leaders=relationshipLeaders();
 return `<section class="ld-leadership"><header><div><h2>Ansvar i gruppen</h2><p>Kapten, avtalade roller och relationer som byggts på isen.</p></div><button onclick="lockerOpenDetail('captain')">Utse kapten</button></header>${state.live&&!state.live.finished?'<p class="lw-lock">Kaptensbyte görs mellan matcher.</p>':''}<table><thead><tr><th>Spelare</th><th>Roll i gruppen</th><th>Avtalad roll</th><th>Etablerat samspel</th></tr></thead><tbody>${roster.map(p=>{const peers=roster.filter(q=>q!==p&&(socialPair(p.id,q.id)?.bond||0)>=45);return `<tr class="${p===lockerSelected()?'ld-selected':''}"><th><button onclick="lockerSet('player','${p.id}')">${trainingSafe(p.name)}</button></th><td>${lockerRole(p)}</td><td>${trainingSafe(p.promisedRole||p.squadRole||'Ej angiven')}</td><td title="${trainingSafe(peers.map(q=>q.name).join(', '))}">${peers.length?`${peers.length} lagkamrater`:'Inget registrerat ännu'}</td></tr>`}).join('')}</tbody></table><p class="ld-explanation">${leaders.length?`${leaders.length} informella ledare i gruppen.`:'Ingen tydlig informell ledare ännu.'} Relationer växer med verkligt samspel. För verkliga spelare utan underlag är personlighetsvärdena neutrala.</p></section>`;
}
function lockerHistory(){return `<section class="ld-history"><header><h2>Samtal & beslut</h2><p>Tidigare besked och registrerade reaktioner.</p></header>${state.locker.log.map(e=>`<article class="lw-event"><small>${seasonLabel(e.year)} · efter ${e.turn} matcher</small><h3>${playerReferenceText(e.titleParts||e.title)}</h3><p>${playerReferenceText(e.bodyParts||e.body)}</p></article>`).join('')||'<div class="ld-empty"><h3>Historiken börjar med ditt första samtal</h3><p>Spelarens svar och dina beslut sparas här.</p></div>'}${(state.training?.messages||[]).filter(m=>m.decisionType&&m.resolved&&managerRoster().some(p=>samePlayerId(p.id,m.playerId))).map(m=>`<article class="lw-event"><small>${m.date?calText(m.date):'Spelarsamtal'}</small><h3>${playerReference(m.playerId,m.title)}</h3><p>${trainingSafe(m.outcome||'Avslutat samtal')}</p></article>`).join('')}</section>`;}
function lockerInspector(){
 const p=lockerSelected();if(!p)return '<aside class="ld-inspector"><p>Ingen spelare i truppen.</p></aside>';
 const mood=lockerMood(p),items=lockerFactors(p),q=lockerPlayerPromises(p),captain=managerRoster().find(c=>samePlayerId(c.id,state.locker.captainId)),bond=captain&&captain!==p?socialPair(p.id,captain.id):null;
 return `<aside class="ld-inspector" id="locker-player-detail" aria-label="Vald spelare: ${trainingSafe(p.name)}"><div class="ld-identity">${squadPortrait(p)}<div><small>${p.age} år · ${trainingSafe(p.pos)} · ${lockerRole(p)}</small><h2>${trainingSafe(p.name)}</h2><p>Humör: <strong class="ld-${mood.tone}">${mood.text}</strong> <span>·</span> Förtroende: <strong>${lockerTrustLabel(p.social.trust)}</strong></p>${lockerMainTab()==='situation'&&!lockerRows().some(r=>r.p===p)?'<small class="ld-warning">Vald spelare ingår inte i aktuellt urval.</small>':''}</div></div><div class="ld-background"><h3>BAKGRUND</h3><p>${trainingSafe(items[0]?.text||'Inga noterade problem i nuläget.')}</p><small>${trainingSafe(p.promisedRole||p.squadRole||'Roll ej angiven')} · ${p.social.lastMinutes===null?'Ingen match registrerad':`Senaste istid ${p.social.lastMinutes.toFixed(1)} min`}</small><small>${q.length?`${q.length} aktiva löften · följ upp faktisk istid`:bond?`Samspel med kaptenen: ${Math.round(bond.bond)}/100`:'Relationer byggs genom registrerat samspel.'}</small>${items.length>1?`<button class="ld-link" onclick="lockerOpenDetail('talk','${p.id}')">Visa hela underlaget · ${items.length} punkter →</button>`:''}</div><div class="ld-next"><h3>NÄSTA STEG</h3><p>${q.length?'Ge det ansvar du har lovat. Följ utfallet efter matcherna.':items.length?'Ta ett enskilt samtal och följ upp spelarens situation.':'Stäm av rollen och håll en tydlig dialog.'}</p><div><button id="locker-talk" class="ld-primary" onclick="lockerOpenDetail('talk','${p.id}')">Prata med spelaren</button><button class="ld-link" onclick="lockerProfile()">Spelarprofil →</button></div></div></aside>`;
}
function lockerProfile(){const p=lockerSelected();if(!p)return;lockerUI.detail=null;selectPlayer(p.id);}
function lockerOpenDetail(kind,id){
 if(!['talk','promise','captain'].includes(kind))return;
 if(kind!=='captain'){const p=managerRoster().find(p=>samePlayerId(p.id,id));if(!p)return;lockerUI.player=p.id;}
 lockerUI.returnFocus=document.activeElement?.id||'locker-talk';lockerUI.detail=kind;render();queueInterfaceSave();
}
function lockerCloseDetail(){const focus=lockerUI.returnFocus;lockerUI.detail=null;render();queueInterfaceSave();document.getElementById(focus)?.focus?.({preventScroll:true});}
function lockerRestoreView(){const el=document.getElementById('locker-scroll');if(el)el.scrollTop=lockerUI.scroll||0;const dialog=document.getElementById('locker-dialog');if(lockerUI.detail&&dialog&&!dialog.open)dialog.showModal?.();}
function lockerDialog(){
 const kind=lockerUI.detail;if(!kind)return '';const p=managerRoster().find(p=>samePlayerId(p.id,lockerUI.player));if(kind!=='captain'&&!p)return '';
 const title=kind==='captain'?'Lagkapten & ansvar':kind==='promise'?'Uppföljning av löfte':'Enskilt spelarsamtal';
 const body=kind==='captain'?lockerCaptainView():kind==='promise'?`<h2>${trainingSafe(p.name)}</h2>${lockerPromiseTable(lockerPromises().filter(x=>x.p===p))}<p class="ld-explanation">Endast registrerade matcher visas. Medicinskt ursäktad frånvaro räknas inte.</p><button class="ld-primary" onclick="lockerUI.detail=null;deskNavigate('lines')">Till laguttagningen →</button>`:`${lockerFactors(p).length?`<div class="ld-context">${lockerFactors(p).map(i=>`<p><strong>${trainingSafe(i.text)}</strong><small>${trainingSafe(i.detail)}</small></p>`).join('')}</div>`:''}${lockerConversation(p)}`;
 return `<dialog id="locker-dialog" class="ld-dialog" aria-labelledby="locker-dialog-title" oncancel="event.preventDefault();lockerCloseDetail()"><header><h2 id="locker-dialog-title">${title}</h2><button autofocus aria-label="Stäng dialogen" onclick="lockerCloseDetail()">×</button></header>${state.locker.message?`<p role="status" class="lw-notice">${trainingSafe(state.locker.message)}</p>`:''}<div class="ld-dialog-body">${body}</div></dialog>`;
}
function lockerWorkspaceView(){
 ensureLocker();ensureRelationships();const roster=managerRoster(),r=state.locker,trust=Math.round(roster.reduce((n,p)=>n+p.social.trust,0)/Math.max(1,roster.length)),mood=Math.round(roster.reduce((n,p)=>n+(p.happiness??70),0)/Math.max(1,roster.length)),tab=lockerMainTab(),attention=lockerAttention();
 let body=tab==='situation'?lockerSituation():`<div class="ld-subnav" aria-label="${tab==='leadership'?'Ledarskapets vyer':'Uppföljningens vyer'}">${(tab==='leadership'?[['leadership','Ansvar & roller'],['relationships','Relationer & faddrar']]:[['promises','Aktiva & avslutade löften'],['history','Samtal & beslut']]).map(([k,v])=>`<button aria-pressed="${lockerUI.tab===k}" onclick="lockerSet('tab','${k}')">${v}</button>`).join('')}</div><div class="ld-scroll ld-content" id="locker-scroll" onscroll="lockerUI.scroll=this.scrollTop">${lockerUI.tab==='relationships'?relationshipView():lockerUI.tab==='history'?lockerHistory():tab==='leadership'?lockerLeadership():lockerPromiseView()}</div>`;
 return `<section class="locker-workspace locker-desk"><header class="ld-heading"><div><span class="desk-kicker">${trainingSafe(managerClub())} · ${seasonLabel()}</span><h1>Omklädningsrummet</h1><p>Förstå gruppen. Följ upp det du har lovat.</p></div><div class="ld-rink" aria-hidden="true"><i></i><b></b><i></i></div></header><div class="ld-summary"><span>Stämning: <strong class="${mood<65?'ld-warning':'ld-good'}" title="Genomsnittlig trivsel ${mood}/100">${mood>=75?'God':mood>=65?'Stabil':'Ansträngd'}</strong></span><span>Förtroende: <strong title="Genomsnitt ${trust}/100">${lockerTrustLabel(trust)}</strong></span><button class="ld-link" onclick="lockerShowAttention()">${attention.length?`${attention.length} spelare att följa upp`:'Inga öppna uppföljningar'}</button><button class="ld-team-talk" onclick="deskNavigate('match')" ${canTeamTalk()?'':'disabled title="Lagsnack hålls i matchvyn vid periodpaus eller efter match."'}>Lagsnack ${deskIcon('arrow')}</button></div><nav class="ld-tabs" aria-label="Omklädningsrummets vyer">${Object.entries(LOCKER_TABS).map(([k,v])=>`<button aria-pressed="${tab===k}" onclick="lockerSet('tab','${k}')">${v}</button>`).join('')}</nav>${r.message&&!lockerUI.detail?`<p class="ld-notice" role="status">${trainingSafe(r.message)}</p>`:''}<div class="ld-main"><div class="ld-main-left">${body}${lockerCaptainStrip()}</div>${lockerAttentionView()}</div>${lockerInspector()}${lockerDialog()}</section>`;
}
