const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r("startCareerWithClub('HV71');ensureJuniors();ensureTrainingData()");
const id=String(r("state.juniors.roster.find(p=>p.pos!=='MV').id"));
r(`juniorById(${JSON.stringify(id)}).academy.path='guest'`);
const startFatigue=r(`juniorById(${JSON.stringify(id)}).fatigue`);
r("juniorTraining({type:'skills',intensity:'normal'},'a-training:1')");
r("juniorTraining({type:'physical',intensity:'hard'},'a-training:2')");
r("juniorTraining({type:'tactics',intensity:'normal'},'a-training:3')");
assert.equal(r(`state.juniors.aTraining[${JSON.stringify(id)}].sessions`),3);
assert.equal(r(`state.juniors.aTraining[${JSON.stringify(id)}].hardSessions`),1);
assert.equal(r(`state.juniors.aTraining[${JSON.stringify(id)}].types.skills`),1);
assert.equal(r(`state.juniors.aTraining[${JSON.stringify(id)}].types.physical`),1);
assert.equal(r(`state.juniors.aTraining[${JSON.stringify(id)}].types.tactics`),1);
assert.ok(Number.isFinite(r(`state.juniors.aTraining[${JSON.stringify(id)}].lastProfile`)));
assert.equal(r(`state.juniors.aTraining[${JSON.stringify(id)}].netFatigue`),r(`juniorById(${JSON.stringify(id)}).fatigue`)-startFatigue);
const before=r('JSON.stringify(state)');
const html=r('managerJ20TrainingFollowupView()');
assert.match(html,/A-TRÄNING/);
assert.match(html,/3 A-pass/);
assert.equal(r('JSON.stringify(state)'),before,'rendering A-training follow-up must be read-only');
r(`juniorById(${JSON.stringify(id)}).fatigue=80`);
assert.equal(r('managerJ20TrainingFollowup().recommendation.level'),'Sänk belastningen');
assert.equal(r(`managerJ20TrainingAct(${JSON.stringify(id)},'light')`),true);
assert.equal(r(`juniorById(${JSON.stringify(id)}).trainingLoad`),'light');
r(`juniorById(${JSON.stringify(id)}).fatigue=25`);
assert.equal(r(`managerJ20TrainingAct(${JSON.stringify(id)},'junior')`),true);
assert.equal(r(`juniorById(${JSON.stringify(id)}).academy.path`),'junior');
assert.equal(r('managerJ20TrainingFollowup()'),null);
console.log('PASS: A-training uses real junior training sessions, records workload/development evidence, renders read-only staff follow-up and supports workload/J20 decisions.');
