const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const {run:r}=boot();
r("startCareerWithClub('HV71')");
const before=r('JSON.stringify(state)');
assert.match(r('managerOfficeView()'),/Dagens prioriteringar/);
assert.equal(r('JSON.stringify(state)'),before,'Office 2 view must not advance or mutate simulation');
const items=r('managerOffice2Items()');
assert.ok(Array.isArray(items)&&items.length>0);
for(let i=1;i<items.length;i++)assert.ok(items[i-1].score>=items[i].score,'priorities must be sorted');
r("managerRoster()[0].fatigue=60");
assert.equal(r("managerOffice2Items().some(x=>x.area==='training')"),true);
r("managerOffice2ToggleDelegation('training')");
assert.equal(r("managerOffice2Delegated('training')"),true);
assert.equal(r("managerOffice2VisibleItems().some(x=>x.area==='training'&&x.level!=='critical'&&!x.requiresDecision)"),false);
r("state.recruitment.incoming.push({id:991,name:'Testbud',buyer:'AIK',fee:100000,status:'pending',expires:state.recruitment.tick+2})");
assert.equal(r("managerOffice2Items().some(x=>x.requiresDecision&&x.action&&x.action.deal==='incoming:991')"),true);
r("managerOffice2ToggleDelegation('contracts');managerOffice2ToggleDelegation('medical');managerOffice2ToggleDelegation('scouting')");
assert.equal(r("managerOffice2VisibleItems().some(x=>x.requiresDecision&&x.action&&x.action.deal==='incoming:991')"),true,'delegation must never hide required manager decisions');
assert.match(r('managerOffice2View()'),/Staben bevakar/);
console.log('PASS: Office 2 prioritises real work, stays read-only, supports advisory delegation and never hides required decisions.');
