'use strict';
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');const r=boot().run;
r("startCareerWithClub('HV71');state.calendar.date=calendarTarget();state.tacticalPlan.attackStyle='counter';startMatch();pauseMatch();");
assert.equal(r('MatchWorld2.livePlan(studioEngine().teams[0]).style'),'counter');
r("state.tactic='attack';studioSyncPlans();");
assert.equal(r('MatchWorld2.livePlan(studioEngine().teams[0]).posture'),'attack');
assert.ok(r("MatchWorld2.tacticalIntent({shotChoice:'shoot'}).volume>MatchWorld2.tacticalIntent({shotChoice:'patient'}).volume"));
r("globalThis.attrs=Object.fromEntries(MatchWorld2.KEYS.map(k=>[k,12]));globalThis.context=choice=>MatchWorld2.backgroundShotContext({creation:12,resistance:12,attackAttributes:attrs,defenseAttributes:attrs,shooterPosition:'F',plan:{shotChoice:choice},opposition:{}},()=>.3);");
assert.ok(r("context('patient').d<context('shoot').d"),'patient choices trade frequency for closer chances');
r(`globalThis.report={finished:true,club:'HV71',opponent:'Test',own:2,against:1,strengthSeconds:{even:3000,pp:360,pk:240},shots:[{side:'own',situation:'even',outcome:'goal'},{side:'opponent',situation:'pk',outcome:'goal'},{side:'own',situation:'pp',outcome:'goal'},{side:'own',situation:'even',outcome:'block'},{side:'opponent',situation:'even',outcome:'save'}],events:[{type:'goal',side:'own',time:60,text:'1–0'},{type:'goal',side:'opponent',time:120,text:'1–1'},{type:'goal',side:'own',time:180,text:'2–1'}],units:[{kind:'forward',label:'Kedja 1',names:['<unsafe>'],seconds:600,dangerFor:2,dangerAgainst:5},{kind:'forward',label:'Kort byte',seconds:12,dangerFor:10,dangerAgainst:0},{kind:'defense',label:'Backpar',seconds:600,dangerFor:2,dangerAgainst:5}]};`);
assert.equal(r('analysisKeyFactors(report).decisive.time'),180);
assert.equal(r('analysisKeyFactors(report).units.length'),1);
assert.equal(r('analysisKeyFactors(report).saves[0].saves'),1);
assert.equal(r('analysisKeyFactors(report).strengths.find(x=>x.kind==="pp").goals[0]'),1);
assert.match(r('analysisKeyFactorsView(report)'),/&lt;unsafe&gt;/);
assert.equal(r('analysisKeyFactors({...report,partial:true})'),null);
assert.equal(r('analysisKeyFactors({...report,shootout:true}).decisive'),null);
assert.equal(r('analysisKeyFactors({...report,against:0}).decisive'),null,'incomplete goal ledger cannot name decisive event');
r('state.live=null');
assert.equal(r("rivalSimulate(state.schedule[0],{regulationOnly:true}).duration"),3600);
console.log('PASS: live tactical identity, shot-choice tradeoff, actual report evidence and regulation-only comparison.');
