'use strict';
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');state.calendar.date=calendarTarget();startMatch();pauseMatch();
 state.live.minute=5;state.live.second=0;state.live.analysis.strengthSeconds.even=300;
 state.live.analysis.shots=Array.from({length:6},(_,i)=>({time:250+i,side:'own',situation:'even',dangerous:false,outcome:'save'}));
 state.tacticalPlan.shotChoice='balanced';studioSyncPlans();save();`);
const baseline=app.storage.value;
assert.match(r('matchEvidenceBody()'),/Sök bättre lägen/);
const before=r('JSON.stringify([state.live.broadcast.rng,state.live.analysis,managerRoster().map(p=>p.morale)])');
r(`matchCoachChoose('quality','apply')`);
assert.equal(r('state.tacticalPlan.shotChoice'),'patient');
assert.equal(r('state.live.running'),false);
assert.equal(r('analysisClock()'),300);
assert.equal(r('state.live.tacticalReviews.length'),1);
assert.equal(r('JSON.stringify([state.live.broadcast.rng,state.live.analysis,managerRoster().map(p=>p.morale)])'),before,'decision must not manufacture an event, goal, energy or morale bonus');
assert.equal(app.get('#match-coach-followup').focused,true);
r(`matchCoachChoose('quality','apply')`);
assert.equal(r('state.live.tacticalReviews.length'),1,'repeat click cannot duplicate a decision');
assert.match(r('matchEvidenceBody()'),/Följer beslutet/);
r('matchCoachReview()');assert.equal(r('matchCoachCurrent()!==null'),true,'cannot re-prompt at the same pause');
// Actual production action selection responds to the order, from the same save.
r(`studioSyncPlans();globalThis.actor=studioEngine().skaters(0).find(a=>a.role!=='G');
 actor.x=47;actor.y=15;actor.controlledAt=studioEngine().time-2;
 studioEngine().owner=0;studioEngine().carrier=actor.id;studioEngine().puck={x:47,y:15};
 globalThis.patientShot=studioEngine().actionOptions(actor).find(a=>a.kind==='shoot').value;`);
const control=boot(baseline),q=control.run;
q(`matchCoachChoose('quality','keep');studioSyncPlans();globalThis.actor=studioEngine().skaters(0).find(a=>a.role!=='G');
 actor.x=47;actor.y=15;actor.controlledAt=studioEngine().time-2;
 studioEngine().owner=0;studioEngine().carrier=actor.id;studioEngine().puck={x:47,y:15};`);
assert.equal(q('state.tacticalPlan.shotChoice'),'balanced');
assert.ok(q("studioEngine().actionOptions(actor).find(a=>a.kind==='shoot').value")>r('patientShot')+.05,'same actor and situation, patient order changes real shot preference');
assert.equal(q('state.live.tacticalReviews[0].coachDecision.choice'),'keep');
// Strength-aware observation, then a new manual decision closes the interval.
r(`state.live.minute=9;state.live.analysis.strengthSeconds.pk=240;
 state.live.analysis.shots.push({time:400,side:'own',situation:'pp',dangerous:true,outcome:'goal'});`);
assert.equal(r('matchCoachCurrent().row.result.seconds'),0,'special-teams time cannot satisfy the observation');
assert.equal(r('matchCoachCurrent().row.result.dangerFor'),0);
r(`state.live.analysis.strengthSeconds.even=480;state.live.analysis.shots.push({time:530,side:'own',situation:'even',dangerous:true,outcome:'save'});`);
assert.equal(r('matchCoachOutcome(matchCoachCurrent().row).enough'),true);
assert.match(r('matchEvidenceBody()'),/Fler farliga lägen framåt/);
const readOnly=r('JSON.stringify(state)');r('matchEvidenceBody();matchEvidencePatch();tacticalReviewView(tacticalReviewSnapshot());');
assert.equal(r('JSON.stringify(state)'),readOnly,'all observation and report rendering is read-only');
r(`matchOrder('tempo','low');state.live.minute=10;state.live.analysis.strengthSeconds.even=540;`);
assert.equal(r('matchCoachCurrent().closed'),true);
assert.equal(r('matchCoachCurrent().row.result.seconds'),180,'frozen at the subsequent decision');
r('save()');const restored=boot(app.storage.value);
assert.equal(restored.run('JSON.stringify(matchCoachCurrent())'),r('JSON.stringify(matchCoachCurrent())'));
r(`state.live.finished=true;globalThis.report=analysisSnapshot();state.analysis.matches.unshift(JSON.parse(JSON.stringify(report)));`);
assert.equal(r('report.tacticalReviews[0].coachDecision.label'),'Sök bättre lägen');
assert.match(r('matchesAnalysisView()'),/Varför beslutet togs/);
assert.match(r('matchEvidenceView()'),/Ditt senaste matchbeslut/);
r(`matchCoachChoose('protect','apply')`);assert.equal(r('state.tactic'),'balanced','finished game cannot accept new decisions');
// Score/time opportunities and stale-button guards.
q(`state.live.tacticalReviews=[];state.live.period=3;state.live.minute=14;state.live.hv=1;state.live.opp=2;`);
assert.equal(q('matchEvidenceReport().advice[0].key'),'chase');
q(`state.live.hv=2;matchCoachChoose('chase','apply')`);
assert.equal(q('state.tactic'),'balanced','equalizer invalidates the old chase prompt');
assert.equal(q('state.live.tacticalReviews.length'),0);
q(`state.live.hv=1;matchCoachChoose('chase','apply');studioSyncPlans()`);
assert.equal(q('studioEngine().teams[0].posture'),'attack');
assert.equal(q('studioEngine().teams[0].tempo'),'high');
assert.equal(q('studioEngine().teams[0].forecheck'),'aggressive');
q(`state.live.tacticalReviews=[];state.live.hv=3;matchCoachChoose('protect','apply');studioSyncPlans()`);
assert.equal(q('studioEngine().teams[0].posture'),'defense');
assert.equal(q('studioEngine().teams[0].tempo'),'low');
assert.equal(q('studioEngine().teams[0].forecheck'),'passive');
assert.equal(q("matchCoachSituation(3800,{own:1,against:2},{})"),null,'regulation-time advice is not used in overtime');
assert.equal(q("matchCoachSituation(200,{own:1,against:2},{})"),null);
q(`state.live.tacticalReviews=[];state.live.period=1;state.live.minute=5;state.tacticalPlan.forecheck='aggressive';
 state.live.analysis.shots=Array.from({length:6},()=>({time:250,side:'opponent',situation:'even',dangerous:true}));
 matchCoachChoose('danger','apply');studioSyncPlans();`);
assert.equal(q('studioEngine().teams[0].forecheck'),'passive');
q(`matchOrder('tempo','normal')`);
assert.equal(q('state.live.tacticalReviews.length'),1);
assert.equal(q('state.live.tacticalReviews[0].coachDecision.additionalChanges'),true,'same-pause edits must not be attributed to the recommendation alone');
q(`state.live.tacticalReviews[0].partial=true`);
assert.equal(q('matchCoachOutcome(matchCoachCurrent().row).enough'),false);
// Separate speech workspace remains available, without stacking every control.
q(`state.live.socialStarted={[socialTalkSlot()]:true};matchCoachMode('talk')`);
assert.match(q('matchFeedbackView()'),/Din röst från bänken/);
assert.doesNotMatch(q('matchFeedbackView()'),/mc-decision-advice/);
q(`matchCoachMode('coach')`);
assert.doesNotMatch(q('matchFeedbackView()'),/Din röst från bänken/);
console.log('PASS: real tactical choice versus unchanged plan; score/time opportunities; stale and duplicate guards; exact strength-aware followup; manual edits; partial/legacy data; save/reload; archived report; compact speech access.');
