const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');globalThis.normal={passing:10,puckControl:10,vision:10,decisions:10,checking:10,strength:10,workRate:10};globalThis.balanced={forecheck:'balanced'},aggressive={forecheck:'aggressive'};`);
assert.equal(r('rivalInitiativeChance(normal,normal,balanced,balanced)'),.51);
assert.ok(r('rivalInitiativeChance({...normal,passing:18,puckControl:18,vision:18,decisions:18},normal,balanced,balanced)')>.6);
assert.ok(r('rivalInitiativeChance(normal,normal,balanced,balanced,5,4)')>.51);
assert.ok(r('rivalInitiativeChance({...normal,checking:18,strength:18,workRate:18},normal,aggressive,balanced)')>r('rivalInitiativeChance({...normal,checking:18,strength:18,workRate:18},normal,balanced,balanced)'));
assert.ok(r('rivalInitiativeChance({...normal,checking:4,strength:4,workRate:4},{...normal,puckControl:18,strength:18,decisions:18},aggressive,balanced)')<r('rivalInitiativeChance({...normal,checking:4,strength:4,workRate:4},{...normal,puckControl:18,strength:18,decisions:18},balanced,balanced)'));
r(`globalThis.g=state.schedule.find(g=>g.home!==managerClub()&&g.away!==managerClub());globalThis.trial=(skill,fatigue=0)=>{for(const p of state.clubRosters[g.home])if(p.pos!=='MV'){for(const k of ['passing','puckControl','vision','decisions'])p.attributes[k]=skill;p.fatigue=fatigue;}let attacks=0,total=0;for(let i=0;i<16;i++){const x=rivalSimulate({...g,round:100+i});const a=x.reports[0].initiative,b=x.reports[1].initiative;if(a.attacks+b.attacks!==a.total||a.evenAttacks+b.evenAttacks!==a.evenTotal)throw Error('opportunity conservation');if(a.total*20!==x.duration)throw Error('time conservation');attacks+=a.evenAttacks;total+=a.evenTotal;}return {attacks,total,share:attacks/total};};globalThis.weak=trial(4),strong=trial(18),tired=trial(18,100);`);
assert.ok(r('strong.share>weak.share+.12'),r('JSON.stringify({weak,strong})'));
assert.ok(r('strong.share>tired.share'),r('JSON.stringify({strong,tired})'));
console.log('Production initiative cohorts:',r('JSON.stringify({weak,strong,tired})'));
r('leagueBackground(g);globalThis.report=JSON.stringify(g.rivalReports);globalThis.before=JSON.stringify(state);rivalInitiativeReport(rivalsClubState(g.home).recent)');
assert.equal(r('JSON.stringify(state)'),r('before'),'report is read-only');
assert.match(r('rivalInitiativeReport(rivalsClubState(g.home).recent)'),/inte uppmätt puckinnehav/);
assert.match(r('rivalInitiativeReport(rivalsClubState(g.home).recent)'),/underlaget är ännu tunt/);
assert.doesNotMatch(r('rivalInitiativeReport([{partial:true,initiative:g.rivalReports[0].initiative}])'),/%/);
assert.doesNotMatch(r('rivalInitiativeReport([{shots:50}])'),/NaN|undefined|%/);
r('leagueBackground(g);save()');assert.equal(r('JSON.stringify(g.rivalReports)'),r('report'));
const loaded=boot(app.storage.value);assert.equal(loaded.run('JSON.stringify(state.schedule.find(g=>g.rivalsRecorded).rivalReports)'),r('report'));
assert.doesNotThrow(()=>loaded.run('validateSaveText(saveExportText())'));
console.log('PASS: initiative responds to puck skills, pressure matchups, manpower and real workload; opportunities reconcile with time, saved reports, idempotence and legacy/partial exclusions.');
