'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
global.StudioHockey=require('./match-simulation');
vm.runInThisContext(fs.readFileSync('match-rules-3.js','utf8'));
vm.runInThisContext(fs.readFileSync('match-engine-3.js','utf8'));
vm.runInThisContext(fs.readFileSync('match-engine-4.js','utf8'));
const rosters=require('./match-lab-rosters');
const m=new StudioHockey.Match(rosters,{seed:404});
const a=m.skaters(0)[0];m.owner=0;m.carrier=a.id;a.x=35;a.y=15;m.puck={x:a.x,y:a.y};
const mates=m.skaters(0).filter(b=>b.id!==a.id);mates[0].x=43;mates[1].x=44;
m.pressureAt=()=>.5;
let rows=m.actionOptions(a),carry=rows.find(r=>r.kind==='carry'),dump=rows.find(r=>r.kind==='dump');
assert.ok(dump,'blue-line pressure exposes a dump option');
assert.ok(carry.zoneReason?.includes('Väntar'),'carrier recognizes teammates beyond the blue line');
assert.ok(dump.zoneReason?.includes('taggar'),'deep puck is explicitly tied to tagging up');
const offsideCarry=carry.value,offsideDump=dump.value;
mates[0].x=36;mates[1].x=37;rows=m.actionOptions(a);carry=rows.find(r=>r.kind==='carry');dump=rows.find(r=>r.kind==='dump');
assert.ok(carry.value>offsideCarry,'an onside rush makes controlled entry more attractive');
assert.ok(dump.value<offsideDump,'with onside support the engine does not force the same dump');
console.log('PASS: Match Engine 4 reads blue-line pressure and offside support');