const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const a=boot(),r=a.run;
r("startCareerWithClub('HV71');globalThis.sample={shots:[],events:[],partial:false};globalThis.addShots=(n,side,dangerous,situation='even',time=240)=>{for(let i=0;i<n;i++)sample.shots.push({time,side,dangerous,situation,outcome:'save'})}");
assert.equal(r('coachEvidence(sample,20).advice.length'),0);
r("addShots(6,'opponent',true,'pk')");
assert.equal(r('coachEvidence(sample,300).advice.length'),0,'boxplay is not a five-on-five weakness');
r("addShots(6,'opponent',true,'even')");
assert.equal(r("coachEvidence(sample,300).advice[0].key"),'danger');
assert.equal(r("coachEvidence(sample,300,[],{forecheck:'passive'}).advice[0].tab"),'lineup');
assert.equal(r('coachEvidence(sample,100).advice.length'),0,'future events must never leak into advice');
assert.equal(r('coachEvidence(sample,600).advice.length'),0,'old pressure ages out of the rolling window');
r('sample.partial=true');
assert.equal(r('coachEvidence(sample,300).advice.length'),0,'partial recordings do not justify shot-pattern advice');
r("sample={shots:[],events:[],partial:false};addShots(6,'own',false)");
assert.equal(r("coachEvidence(sample,300).advice[0].key"),'quality');
assert.equal(r("coachEvidence(sample,300,[],{shotChoice:'patient'}).advice[0].tab"),'lineup');
r("sample.events=[{type:'penalty',side:'own',time:250},{type:'penalty',side:'own',time:290}]");
assert.equal(r("coachEvidence(sample,300).advice[1].key"),'discipline');
r("globalThis.players=[{name:'A',energy:40},{name:'B',energy:50}]");
assert.equal(r('coachEvidence(sample,300,players).advice.length'),2);
assert.equal(r('coachEvidence(sample,300,players).advice[0].key'),'energy');
r("state.calendar.date=calendarTarget();startMatch();state.live.analysis.shots=sample.shots;state.live.analysis.events=sample.events;state.live.minute=5;globalThis.before=JSON.stringify([state.live,state.tacticalPlan,state.lines]);globalThis.html=matchEvidenceView();matchEvidencePatch()");
assert.equal(r('JSON.stringify([state.live,state.tacticalPlan,state.lines])'),r('before'),'view and live patch cannot mutate the match');
assert.ok(r("html.includes('Assistentens observationer')"));
assert.ok(r("html.includes('Avvägning:')"));
r("globalThis.clock=analysisClock();globalThis.tactic=JSON.stringify(state.tacticalPlan);matchTab('tactics')");
assert.equal(r('state.live.running'),false);
assert.equal(r('analysisClock()'),r('clock'));
assert.equal(r('JSON.stringify(state.tacticalPlan)'),r('tactic'),'opening a recommendation never silently applies tactics');
assert.equal(a.get('#match-tab-tactics').focused,true);
r("save()");const b=boot(a.storage.value);
assert.equal(b.run('JSON.stringify(matchEvidenceReport().advice)'),r('JSON.stringify(matchEvidenceReport().advice)'));
console.log('PASS: evidence thresholds, strength separation, time-window expiry, partial/future data, current tactics, priority limits, read-only patch, pause/focus and saved advice continuity.');
