const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const a=boot(),r=a.run;
r(`startCareerWithClub('HV71');globalThis.p=managerRoster().find(p=>p.pos!=='MV'&&!playerLoan(p));p.social.lastTalk=-10;globalThis.role=p.promisedRole;globalThis.trust=p.social.trust;`);
assert.equal(r('playerChance(p.id)'),true);
assert.equal(r('p.promisedRole'),r('role'));
assert.equal(r('p.social.trust'),r('trust'));
assert.equal(r('playerChance(p.id)'),false);
assert.equal(r('p.recruitmentPromise.source'),'Samtalslöfte');
assert.equal(r('playerFollowupClose(p.id)'),false);
r('state.calendar.date=calAdd(state.calendar.date,14)');
assert.ok(r('managerAgendaItems(true).some(i=>i.action?.conversationPlayer===p.id&&i.due===state.calendar.date)'));
assert.equal(r('playerFollowupClose(p.id)'),true);
assert.equal(r('p.recruitmentPromise.resolved'),false);
assert.equal(r('playerFollowupClose(p.id)'),false);
r(`for(let n=1;n<=3;n++)followRecruitmentPromises({finished:true,analysis:{id:'chance:'+n},iceTime:{[p.id]:1000}})`);
assert.equal(r('p.recruitmentPromise.result'),'Uppfyllt');
r('save()');const b=boot(a.storage.value);
assert.equal(b.run('managerRoster().find(p=>p.id==='+JSON.stringify(r('p.id'))+').roleFollowup.closed'),r('p.roleFollowup.closed'));
assert.doesNotThrow(()=>r('validateSaveText(saveExportText())'));
r(`p.roleFollowup.club='AIK';globalThis.before=JSON.stringify(state);playerFollowupView(p);playerFollowupItems()`);
assert.equal(r('JSON.stringify(state)'),r('before'));
assert.equal(r('playerFollowupClose(p.id)'),false);
r(`p.recruitmentPromise.resolved=true;p.social.lastTalk=-10;injurePlayer(p,'träning',8)`);
assert.equal(r('playerChance(p.id)'),false);
console.log('PASS: actionable chance, no stacking or role rewrite, dated agenda, neutral calendar review, match outcome, reload and absence.');
