const test=require('node:test');
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');

test('player identity, profile context, retirement and knowledge boundaries',()=>{
 const app=boot(),{run,get}=app;
 run('startCareerWithClub("HV71");deskNavigate("squad");globalThis.own=managerRoster()[0];globalThis.other=state.playerWorld.freeAgents[0];other.name=own.name;globalThis.ownId=own.id;globalThis.otherId=other.id;');
 assert.notEqual(run('ownId'),run('otherId'));
 run('deskOpenPlayer(otherId)');
 assert.equal(run('state.selectedMarketPlayer'),run('otherId'));
 assert.equal(run('state.page'),'marketPlayer');
 run('deskOpenPlayer(ownId,true)');
 assert.equal(run('state.page'),'player');
 assert.equal(run('state.selectedPlayer'),run('ownId'));
 assert.equal(run('playerSearchResults(own.name).players.filter(p=>p.name===own.name).length'),2);
 assert.match(run('playerReference(otherId)'),/data-player-id=/);
 assert.match(run('playerReference(otherId,"<script>")'),/&lt;script&gt;/);
 assert.doesNotMatch(run('playerReferenceText("A <script>")'),/<script>/);
 assert.match(run('playerReferenceText([{text:"Spelare: "},{playerId:otherId,text:other.name}])'),/data-player-id=/);
 run('profileWorkspace.tab="contract";deskOpenPlayer(otherId);deskBack();');
 assert.equal(run('profileWorkspace.tab'),'contract');
 run('deskNavigate("transfers","search");state.recruitment.filters.query="Center";recruitHub.sort="name";scoutDesk.list="reports";scoutDesk.columns="contract";calendarUI.month="2027-01";calendarUI.date="2027-01-08";');
 get('#content').scrollTop=415;
 run('deskOpenPlayer(otherId);scoutingCompare(otherId);deskBack();');
 assert.equal(run('state.recruitment.filters.query'),'Center');
 assert.equal(run('recruitHub.sort'),'name');
 assert.equal(run('scoutDesk.columns'),'contract');
 assert.equal(run('calendarUI.month'),'2027-01');
 assert.equal(get('#content').scrollTop,415);
 assert.equal(run('scoutDesk.compare.some(id=>samePlayerId(id,otherId))'),true);
 run('deskOpenPlayer(ownId);scoutingCompare(ownId);profileWorkspace.tab="attributes";render()');
 assert.match(get('#content').innerHTML,/Granska jämförelsen/);
 run('setIndividualLoad(ownId,"rest")');
 assert.equal(run('own.trainingLoad'),'rest');
 assert.notEqual(run('other.trainingLoad'),'rest');
 run('medicalReport("Rapport","Underlag",ownId)');
 assert.match(run('messageActionView(state.training.messages[0])'),/data-player-id=/);
 run('deskOpenPlayer(otherId);profileWorkspace.tab="development";render()');
 assert.match(get('#content').innerHTML,/inte tillgängliga/);
 run('other.health={load:97,injury:{name:"SECRET INJURY",readiness:13,remaining:28}}');
 assert.doesNotMatch(run('medicalPlayerPanel(other)'),/SECRET|97|13|28/);
 run('state.leagueStatistics.rows.evidence={id:otherId,name:other.name,pos:other.pos,club:"Tidigare klubb",league:"SHL",stage:"regular",games:3,goals:2,assists:1,seconds:1800};worldRetire(other,"Tidigare klubb");worldRemoveFree(otherId);leagueStatsOpenPlayer(otherId);');
 assert.equal(run('findPlayerAnywhere(otherId)'),null);
 assert.match(get('#content').innerHTML,/Pensionerad/);
 assert.match(get('#content').innerHTML,/Tidigare klubb/);
 assert.doesNotMatch(get('#content').innerHTML,/hubTransferForm|scoutingDraft|SECRET INJURY/);
 run('save()');
 const loaded=boot(app.storage.value),id=JSON.stringify(run('otherId'));
 assert.equal(loaded.run('playerIdentity('+id+').active'),false);
 assert.equal(loaded.run('scoutDesk.compare.length'),2);
 assert.match(loaded.run('scoutingComparison()'),/Aktivt jämförelseunderlag saknas/);
 loaded.run('scoutingCompare('+id+')');
 assert.equal(loaded.run('scoutDesk.compare.length'),1);
 assert.match(loaded.run('historicalPlayerView('+id+')'),/Tidigare klubb/);
 loaded.run('delete state.playerArchive;state.playerWorld.events=[]');
 assert.equal(loaded.run('playerIdentity('+id+').player.name'),run('own.name'));
 assert.match(loaded.run('historicalPlayerView("missing-id")'),/Spelaruppgifter saknas/);
 // Simulated DOM, not a browser-layout test.
 run('globalThis.field={name:"salary",type:"number",value:"920000",checked:false};globalThis.form={getAttribute:()=>"submitDeal()",elements:[field]};globalThis.scroller={scrollTop:220,scrollLeft:45};document.querySelectorAll=selector=>selector==="#content form"?[form]:[scroller];globalThis.context=deskWorkspaceContext();field.value="1";scroller.scrollTop=0;scroller.scrollLeft=0;deskRestoreWorkspaceDOM(context);');
 assert.equal(run('field.value'),'920000');
 assert.equal(run('scroller.scrollTop'),220);
 assert.equal(run('scroller.scrollLeft'),45);
});
