"use strict";
const recruitHub={player:null,panel:'report',page:0,sort:'name',market:'all',deal:null,affairs:'open'};
function hubPick(id){if(!findPlayerAnywhere(id))return;recruitHub.player=id;recruitHub.panel='report';render();}
function hubPanel(panel){if(!['report','transfer','loan','future'].includes(panel))return;recruitHub.panel=panel;render();}
function hubReportSearch(){scoutUI.query=document.getElementById('hub-report-query')?.value||'';recruitHub.page=0;render();}
function hubScoutIds(){return hubCandidates(state.recruitment.tab).filter(p=>!isOwnPlayer(p)&&!scoutPending(p.id)&&(state.scoutReports[String(p.id)]?.visits||0)<3).map(p=>p.id);}
function hubPage(delta){recruitHub.page=Math.max(0,recruitHub.page+delta);render();}
function hubMarket(value){if(!['all','loan','own'].includes(value))return;recruitHub.market=value;recruitHub.page=0;recruitHub.player=null;render();}
function hubNeed(profile){deskNavigate('transfers','search');resetRecruitFilters();recruitFilters().profile=profile;recruitHub.market='all';recruitHub.page=0;recruitHub.player=null;save();render();}
function hubCandidates(tab){
 let list=recruitHub.market==='own'?managerRoster():recruitCandidates();
 if(tab==='shortlist')list=list.filter(p=>state.recruitment.shortlist.some(id=>samePlayerId(id,p.id)));
 if(tab==='missions')list=getTransferMarketPlayers().filter(p=>((state.scoutReports[String(p.id)]?.visits||0)>0||scoutPending(p.id))&&(!scoutUI.query||`${p.name} ${getPlayerClub(p.id)}`.toLocaleLowerCase('sv').includes(scoutUI.query.toLocaleLowerCase('sv'))));
 if(recruitHub.market==='loan'&&tab!=='missions')list=list.filter(p=>state.world.membership[getPlayerClub(p.id)]&&loanCanLeave(p,getPlayerClub(p.id)));
 if(recruitHub.market==='own'){const query=recruitFilters().query.toLocaleLowerCase('sv');list=list.filter(p=>!query||p.name.toLocaleLowerCase('sv').includes(query));}
 return list.slice().sort((a,b)=>recruitHub.sort==='fee'?recruitFee(a)-recruitFee(b):recruitHub.sort==='ability'?playerAssessment(b).current-playerAssessment(a).current:a.name.localeCompare(b.name,'sv'));
}
function hubHeader(){
 const r=state.recruitment,offers=r.deals.filter(d=>d.status==='pending'),reserved=offers.filter(d=>d.kind!=='future').reduce((n,d)=>n+d.fee,0);
 return `<header class="rh-header"><div><h1>Rekrytering</h1><span>${trainingSafe(managerClub())} · ${calendarDeadlineText()}</span></div><dl><div><dt>Klubbkassa</dt><dd>${careerMoney(state.money)}</dd></div><div><dt>Reserverat i köpbud</dt><dd>${careerMoney(reserved)}</dd></div><div><dt>Löneutrymme före bud / år</dt><dd>${careerMoney(wageBudget()-annualWageCost())}</dd></div><div><dt>Scoutuppdrag</dt><dd>${scoutActiveCount()} / ${clubMissionLimit()}</dd></div></dl></header>`;
}
function hubFilters(tab){
 const f=recruitFilters();
 if(recruitHub.market==='own'&&tab!=='missions')return `<aside class="rh-sidebar"><h2>Lån ut</h2><label>Rekryteringsväg<select onchange="hubMarket(this.value)">${recruitOptions({all:'Alla värvningar',loan:'Möjliga lån in',own:'Egna spelare · lån ut'},'own')}</select></label><label>Namn<input id="recruit-query" type="search" value="${trainingSafe(f.query)}" onkeydown="if(event.key==='Enter'){event.preventDefault();applyRecruitSearch()}"></label><button class="btn" onclick="applyRecruitSearch()">Sök spelare</button><p>Välj en egen spelare. Under Lån ut visas intresserade klubbar och lånevillkor.</p></aside>`;
 if(tab==='missions')return `<aside class="rh-sidebar"><h2>Scouting</h2><label>Sök rapport<input id="hub-report-query" type="search" value="${trainingSafe(scoutUI.query)}" onkeydown="if(event.key==='Enter'){event.preventDefault();hubReportSearch()}"></label><button class="rh-link" onclick="hubReportSearch()">Sök rapporter</button><h3>Pågående uppdrag</h3><p>Rapporter och observationer visas i spelarlistan. Markera en spelare för att läsa bedömningen.</p>${state.recruitment.missions.filter(m=>m.status==='active').map(m=>`<article><strong>${trainingSafe(m.filters.profile==='ALL'?'Bred sökning':m.filters.profile)}</strong><small>${m.players.length} spelare · ${m.observations}/3 observationer</small><small>Nästa rapport ${m.nextDate?calText(m.nextDate):'väntas'}</small><button class="rh-link" onclick="cancelScoutMission(${m.id})">Avsluta uppdrag</button></article>`).join('')||'<p>Inga gruppuppdrag pågår.</p>'}<button class="rh-link" onclick="deskNavigate('transfers','search')">Sök nya kandidater →</button></aside>`;
 return `<aside class="rh-sidebar"><h2>Urval</h2><label>Rekryteringsväg<select onchange="hubMarket(this.value)">${recruitOptions({all:'Alla värvningar',loan:'Möjliga lån in',own:'Egna spelare · lån ut'},recruitHub.market)}</select></label><label>Namn eller klubb<input id="recruit-query" type="search" value="${trainingSafe(f.query)}" onkeydown="if(event.key==='Enter'){event.preventDefault();applyRecruitSearch()}" placeholder="Sök spelare"></label><label>Spelarprofil<select onchange="setRecruitFilter('profile',this.value);recruitHub.page=0">${recruitOptions({ALL:'Alla roller',...Object.fromEntries(Object.keys(RECRUIT_PROFILES).map(k=>[k,k]))},f.profile)}</select></label><label>Avtalsstatus<select onchange="setRecruitFilter('availability',this.value)">${recruitOptions({all:'Alla avtal',free:'Kontraktslös'},f.availability||'all')}</select></label><label>Marknad<select onchange="setRecruitFilter('country',this.value)">${recruitOptions(RECRUIT_COUNTRIES,f.country)}</select></label><div class="rh-filter-pair"><label>Högsta ålder<input type="number" value="${f.maxAge}" min="18" max="60" onchange="setRecruitFilter('maxAge',this.value)"></label><label>Max pris<input type="number" value="${f.maxFee}" min="0" step="100000" onchange="setRecruitFilter('maxFee',this.value)"></label></div><details><summary>Attributkrav</summary><label>Attribut<select onchange="setRecruitFilter('attribute',this.value)">${recruitOptions({'':'Inget krav',...SKATER_ATTRIBUTES,...GOALIE_ATTRIBUTES},f.attribute||'')}</select></label><label>Minst<input type="number" min="1" max="20" value="${f.minAttribute||10}" onchange="setRecruitFilter('minAttribute',this.value)"></label></details><div class="rh-filter-actions"><button class="btn" onclick="applyRecruitSearch()">Sök spelare</button><button class="rh-link" onclick="resetRecruitFilters();recruitHub.market='all';recruitHub.page=0;render()">Återställ</button></div>${recruitHub.market==='own'?'<p>Egna spelare filtreras på namn. Välj en spelare för att planera ett lån ut.</p>':`<p>Utgå från bedömda egenskaper. Prisnivån är ingen garanti för att klubben säljer.</p><button class="rh-link" onclick="createScoutMission(hubScoutIds())" ${hubScoutIds().length?'':'disabled title="Inga nya kandidater kan scoutas i detta urval."'}>Scouta urval · ${money(clubMissionFee())}</button>`}</aside>`;
}
function hubPlayerTable(list,tab){
 const pages=Math.max(1,Math.ceil(list.length/20));recruitHub.page=Math.min(recruitHub.page,pages-1);const shown=list.slice(recruitHub.page*20,recruitHub.page*20+20);
 return `<section class="rh-list"><header><h2>${tab==='missions'?'Scoutrapporter':tab==='shortlist'?'Önskelista':'Spelare'} <small>${list.length}</small></h2><label>Sortera<select onchange="recruitHub.sort=this.value;recruitHub.page=0;render()">${recruitOptions({name:'Namn',ability:'Bedömd förmåga',fee:'Prisnivå'},recruitHub.sort)}</select></label></header><div class="rh-table-scroll"><table><thead><tr><th>Pos</th><th>Spelare</th><th>Ålder</th><th>Förmåga</th><th>Prisnivå</th><th>Kunskap</th></tr></thead><tbody>${shown.map(p=>{const a=playerAssessment(p);return `<tr class="${samePlayerId(p.id,recruitHub.player)?'selected':''}"><td>${p.pos}</td><td><button onclick="hubPick('${haEscape(p.id)}')" aria-pressed="${samePlayerId(p.id,recruitHub.player)}">${trainingSafe(p.name)}</button><small>${trainingSafe(getPlayerClub(p.id))}</small></td><td>${p.age}</td><td>${assessmentBadge(p)}</td><td>${careerMoney(recruitFee(p))}</td><td>${Math.round(a.familiarity*100)}%<small>${scoutPending(p.id)?'Rapport beställd':a.visits?`${a.visits}/3 obs.`:a.own?'Egen spelare':'Ej observerad'}</small></td></tr>`;}).join('')||`<tr><td colspan="6">${tab==='shortlist'?'Önskelistan är tom. Välj spelare under Spelare och lägg till dem här.':tab==='missions'?'Inga scoutrapporter ännu. Beställ en observation från spelarens bedömning eller scouta ett urval.':'Inga träffar. Bredda urvalet eller återställ filtren.'}</td></tr>`}</tbody></table></div><footer><button class="rh-link" onclick="hubPage(-1)" ${recruitHub.page===0?'disabled':''}>← Föregående</button><span>Sida ${recruitHub.page+1} / ${pages}</span><button class="rh-link" onclick="hubPage(1)" ${recruitHub.page===pages-1?'disabled':''}>Nästa →</button></footer></section>`;
}
function hubTransferForm(p){
 const w=recruitPlayerWishes(p),legacy=state.transferNegotiation&&samePlayerId(state.transferNegotiation.playerId,p.id)?state.transferNegotiation:null,pending=state.recruitment.deals.some(d=>samePlayerId(d.playerId,p.id)&&d.status==='pending');
 return `<h3>Köp · anslut direkt</h3><p>Prisnivå ${careerMoney(recruitFee(p))}. Spelaren önskar ${careerMoney(w.salary)}/år och rollen ${w.role.toLowerCase()}.</p><form onsubmit="event.preventDefault();submitRecruitOffer('${p.id}',this.elements.fee.value,this.elements.salary.value,this.elements.years.value,this.elements.role.value)"><label>Övergångssumma<input name="fee" type="number" min="${worldIsFree(p.id)?0:1}" required value="${legacy?.transferFee||recruitFee(p)}" ${worldIsFree(p.id)?'readonly':''}></label><label>Årslön<input name="salary" type="number" min="1" required value="${legacy?.salaryDemand||w.salary}"></label><label>Avtalslängd<select name="years">${recruitOptions({1:'1 år',2:'2 år',3:'3 år',4:'4 år',5:'5 år'},Math.min(3,w.maxYears))}</select></label><label>Utlovad roll<select name="role">${recruitOptions(Object.fromEntries(SQUAD_ROLES.map(k=>[k,k])),w.role)}</select></label><button class="btn" type="submit" ${pending?'disabled':''}>Skicka köpbud</button><p>${pending?'Ett bud väntar redan på besked. Hantera det under Affärer.':'Budet reserverar budget. Besked om två kalenderdagar.'}</p></form>`;
}
function hubLoanForm(p){
 const owner=getPlayerClub(p.id),own=owner===managerClub(),active=playerLoan(p);
 if(active)return `<h3>Aktivt lån</h3><p>${trainingSafe(active.owner)} → ${trainingSafe(active.borrower)} · till ${calText(active.until)}</p><p>${active.share*100}% av lönen betalas av mottagarklubben.</p><button class="rh-link" onclick="recruitHub.affairs='active';deskNavigate('transfers','deals')">Följ aktiva lån →</button>`;
 const destinations=own?Object.keys(state.world.membership).filter(c=>c!==owner&&loanFit(p,c).interested):state.world.membership[owner]?[managerClub()]:[];
 return `<h3>${own?'Lån ut':'Lån in'}</h3><p>${loanCanLeave(p,owner)?'Förhandla om roll, löneandel och återkallelse. Besked efter två dagar.':'Spelaren kan inte lånas just nu på grund av avtal, hälsa eller ägarklubbens truppbehov.'}</p><form onsubmit="event.preventDefault();loanSubmit('${p.id}',this.elements.destination.value,this.elements.days.value,this.elements.share.value,this.elements.role.value,this.elements.recall.value)"><label>Mottagarklubb<select name="destination">${destinations.map(c=>`<option value="${trainingSafe(c)}">${trainingSafe(c)}</option>`).join('')}</select></label><label>Längd<select name="days">${recruitOptions({28:'Fyra veckor',56:'Åtta veckor',0:'Säsongen ut'},28)}</select></label><label>Mottagarens löneandel<select name="share">${recruitOptions({0:'0 %',0.25:'25 %',0.5:'50 %',0.75:'75 %',1:'100 %'},.5)}</select></label><label>Planerad roll<select name="role">${recruitOptions(LOAN_ROLES,'regular')}</select></label><label>Återkallelse<select name="recall">${recruitOptions({day28:'Efter 28 dagar',anytime:'Mellan matcher'},'day28')}</select></label><button class="btn" type="submit" ${!destinations.length||!loanCanLeave(p,owner)?'disabled':''}>Skicka låneförslag</button></form>${!destinations.length?'<p>Ingen mottagarklubb är aktuell för den här spelaren.</p>':''}`;
}
function hubInspector(p){
 if(!p)return '<aside class="rh-inspector rh-empty"><h2>Spelarbedömning</h2><p>Markera en spelare i listan för att jämföra egenskaper, läsa rapporten och välja nästa steg.</p></aside>';
 const a=playerAssessment(p),own=isOwnPlayer(p),listed=state.recruitment.shortlist.some(id=>samePlayerId(id,p.id)),fields=p.pos==='MV'?GOALIE_ATTRIBUTES:SKATER_ATTRIBUTES,keys=Object.keys(fields).sort((x,y)=>a.estimated[y]-a.estimated[x]);
 return `<aside class="rh-inspector"><header><small>${p.pos} · ${p.age} år · ${trainingSafe(getPlayerClub(p.id))}</small><h2>${trainingSafe(p.name)}</h2><span>${assessmentBadge(p)} / ${assessmentBadge(p,true)}</span></header><nav class="rh-inspector-tabs" aria-label="Vald spelare">${[['report','Bedömning'],...(!own&&!playerLoan(p)?[['transfer','Köp'],...(p.futureContract||p.contractYears===1&&state.season.phase!=='preseason'?[['future','Nästa säsong']]:[])]:[]),...(state.world.membership[getPlayerClub(p.id)]?[['loan',playerLoan(p)?'Låneavtal':own?'Lån ut':'Lån in']]:[])].map(([key,label])=>`<button aria-pressed="${recruitHub.panel===key}" onclick="hubPanel('${key}')">${label}</button>`).join('')}</nav>${recruitHub.panel==='loan'?hubLoanForm(p):recruitHub.panel==='transfer'&&!own?hubTransferForm(p):recruitHub.panel==='future'&&!own?(calendarFuturePanel(p)||'<p>Avtal till nästa säsong kan erbjudas under säsongen när spelaren har ett kontraktsår kvar.</p>'):`<h3>${a.roles[0].name}</h3>${state.scoutReports[String(p.id)]?.dueDate?`<p>Nästa rapport: ${calText(state.scoutReports[String(p.id)].dueDate)}</p>`:''}<p>${trainingSafe(a.staff.name)} · ${Math.round(a.familiarity*100)}% kunskap</p><dl>${keys.slice(0,6).map(k=>`<dt>${fields[k]}</dt><dd>${attributeInterval(p,k,a)}</dd>`).join('')}</dl><p>Svagare sida: ${fields[keys.at(-1)].toLowerCase()}. Bedömningen blir säkrare med fler observationer.</p><dl><dt>Prisnivå</dt><dd>${careerMoney(recruitFee(p))}</dd><dt>Kontrakt kvar</dt><dd>${p.contractYears} år</dd><dt>Observationer</dt><dd>${a.visits}/3</dd></dl>${!own?`<button class="btn" onclick="requestScoutReport('${p.id}',true)">Beställ scoutrapport</button><button class="rh-link" onclick="toggleRecruitShortlist('${p.id}')">${listed?'Ta bort från önskelistan':'Lägg till i önskelistan'}</button>`:''}${state.page==='marketPlayer'?'':`<button class="rh-link" onclick="${own?'selectPlayer':'recruitOpen'}('${p.id}')">Fullständig spelarprofil →</button>`}`}</aside>`;
}
function hubAffairRows(){
 const r=state.recruitment;
 return [...r.deals.map(d=>({key:'transfer:'+d.id,type:d.kind==='future'?'Nästa säsong':'Köp',name:d.name,status:d.status,d})),...r.incoming.map(d=>({key:'incoming:'+d.id,type:'Försäljning',name:d.name,status:d.status,d})),...state.loans.offers.map(d=>({key:'loan:'+d.id,type:d.owner===managerClub()?'Lån ut':'Lån in',name:d.name,status:d.status,d})),...state.loans.active.filter(d=>[d.owner,d.borrower].includes(managerClub())).map(d=>({key:'active:'+d.id,type:'Aktivt lån',name:d.name,status:'active',d})),...state.loans.history.filter(d=>[d.owner,d.borrower].includes(managerClub())).map((d,i)=>({key:'ended:'+i,type:'Avslutat lån',name:d.name,status:'ended',d}))];
}
const HUB_STATUS={pending:'Inväntar besked',counter:'Motbud',signed:'Klar',future_signed:'Klar till nästa säsong',rejected:'Avslag',cancelled:'Återkallad',accepted:'Accepterad',agreed:'Överens',expired:'Utgången',active:'Pågående',ended:'Avslutat'};
function hubDealDetail(row){
 if(!row)return '<h2>Affärens detaljer</h2><p>Markera en affär för att läsa villkor, besked och tillgängliga beslut.</p>';
 const d=row.d,kind=row.key.split(':')[0],t=d.counter&&typeof d.counter==='object'?d.counter:d;
 let text='',actions='';
 if(kind==='transfer'){
 text=`<dl><dt>Övergångssumma</dt><dd>${careerMoney(d.fee)}</dd><dt>Årslön</dt><dd>${careerMoney(d.salary)}</dd><dt>Avtalslängd</dt><dd>${d.years} år</dd><dt>Roll</dt><dd>${d.role}</dd></dl>${d.rival?`<p>Konkurrens: ${trainingSafe(d.rival.club)} · ${careerMoney(d.rival.salary)}/år.</p>`:''}`;
 actions=d.status==='pending'?`${d.counter?`<button class="btn" onclick="acceptRecruitCounter(${d.id})">Acceptera motbud</button>`:''}<button class="rh-link" onclick="cancelRecruitOffer(${d.id})">Återkalla köpbud</button>`:'';
 }else if(kind==='incoming'){text=`<p>${trainingSafe(d.buyer)} erbjuder ${careerMoney(d.fee)}.</p>`;actions=d.status==='pending'?`<button class="btn" onclick="answerIncomingOffer(${d.id},true)">Acceptera försäljning</button><button class="rh-link" onclick="answerIncomingOffer(${d.id},false)">Avvisa bud</button>`:'';
 }else if(kind==='loan'){text=`<p>${trainingSafe(d.owner)} → ${trainingSafe(d.destination||d.borrower||'Mottagarklubb')}</p><dl><dt>Löneandel</dt><dd>${t.share*100}%</dd><dt>Längd</dt><dd>${t.days?t.days+' dagar':'Säsongen ut'}</dd><dt>Roll</dt><dd>${LOAN_ROLES[t.role]||t.role}</dd><dt>Återkallelse</dt><dd>${t.recall==='anytime'?'Mellan matcher':'Efter 28 dagar'}</dd></dl>`;actions=['pending','counter'].includes(d.status)?`${d.status==='counter'?`<button class="btn" onclick="loanAnswer(${d.id},true)">Acceptera lånevillkor</button>`:''}<button class="rh-link" onclick="loanAnswer(${d.id},false)">Återkalla låneförslag</button>`:'';
 }else{text=`<p>${trainingSafe(d.owner)} → ${trainingSafe(d.borrower)} · till ${calText(d.until)}</p><p>${d.games} matcher · ${Math.round(d.seconds/60)} min · ${loanProduction(d)}</p><p>${trainingSafe(d.roleReview||'Istid och utveckling följs under lånet.')}</p>`;actions=kind==='active'?`<button class="btn secondary" onclick="loanRecall(${d.id})">${d.owner===managerClub()?'Återkalla spelaren':'Avsluta lånet'}</button>`:'';}
 return `<small>${row.type} · ${HUB_STATUS[row.status]||row.status}</small><h2>${trainingSafe(row.name)}</h2>${text}<p>${trainingSafe(d.reason||'')}${d.dueDate?' Besked '+calText(d.dueDate):''}</p>${actions}<button class="rh-link" onclick="${getPlayerClub(d.playerId)===managerClub()?'selectPlayer':'recruitOpen'}('${d.playerId}')">Fullständig spelarprofil →</button>`;
}
function hubAffairs(tab){
 const mode=tab==='history'?'history':recruitHub.affairs,all=hubAffairRows(),rows=all.filter(x=>mode==='active'?x.status==='active':mode==='history'?!['pending','counter','active'].includes(x.status):['pending','counter'].includes(x.status));
 if(state.recruitment.focusDeal){const focus=all.find(x=>x.key==='transfer:'+state.recruitment.focusDeal);if(focus&&!rows.includes(focus))rows.unshift(focus);recruitHub.deal=focus?.key||recruitHub.deal;}
 const selected=rows.find(x=>x.key===recruitHub.deal)||rows[0];
 return `<div class="rh-affairs"><section class="rh-list"><header><h2>Affärer</h2><nav>${[['open','Pågående bud'],['active','Aktiva lån'],['history','Avslutade']].map(([key,label])=>`<button aria-pressed="${mode===key}" onclick="recruitHub.affairs='${key}';state.recruitment.focusDeal=null;state.recruitment.tab='deals';render()">${label}</button>`).join('')}</nav></header><div class="rh-table-scroll"><table><thead><tr><th>Spelare</th><th>Affär</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr class="${selected===x?'selected':''}"><td><button onclick="recruitHub.deal='${x.key}';state.recruitment.focusDeal=null;render()">${trainingSafe(x.name)}</button></td><td>${x.type}</td><td>${x.d.counter?'Motbud':HUB_STATUS[x.status]||x.status}</td></tr>`).join('')||'<tr><td colspan="3">Inga affärer i den här kategorin. Köp och lån startas från en vald spelare under Spelare.</td></tr>'}</tbody></table></div>${mode==='history'?`<details class="rh-market-history"><summary>Övergångar i omvärlden</summary>${recruitHistoryView()}</details>`:''}</section><aside class="rh-inspector">${tab==='loans'&&state.loans.selected?hubInspector(findPlayerAnywhere(state.loans.selected)).replace('<aside class="rh-inspector">','<div>').replace(/<\/aside>$/,'</div>'):hubDealDetail(selected)}</aside></div>`;
}
function recruitmentHubView(override){
 ensureRecruitment();ensureLoans();const tab=override||state.recruitment.tab,r=state.recruitment;
 let body;
 if(['deals','loans','history'].includes(tab)){const legacy=state.transferNegotiation&&findPlayerAnywhere(state.transferNegotiation.playerId);body=(legacy&&!isOwnPlayer(legacy)?`<p class="rh-notice">Påbörjad kontraktsdiskussion: ${trainingSafe(legacy.name)}. <button class="rh-link" onclick="recruitOpen('${legacy.id}')">Fortsätt diskussionen</button></p>`:'')+hubAffairs(tab);}
 else if(tab==='needs')body=`<div class="rh-planning"><section class="rh-list"><header><h2>Truppens rekryteringsplan</h2><span>Behov nu och nästa säsong</span></header><table><thead><tr><th>Roll</th><th>Tillgängliga</th><th>Måltal</th><th>Prioritet</th><th>Underlag</th></tr></thead><tbody>${recruitmentNeeds().map(n=>`<tr><td><button onclick="hubNeed('${n.name}')">${n.name} →</button></td><td>${n.count}</td><td>${n.target}</td><td>${n.priority}</td><td>${n.reasons.map(trainingSafe).join(' ')}</td></tr>`).join('')}</tbody></table></section><aside class="rh-inspector"><h2>Från behov till avtal</h2><ol><li>Välj en roll för att öppna ett relevant spelarurval.</li><li>Jämför spelare och beställ observationer.</li><li>Samla alternativen i önskelistan.</li><li>Välj köp eller lån i spelarens panel.</li></ol><p>Alla bud och aktiva lån följs under Affärer. Ett behov är ett beslutsunderlag; det är ingen automatisk värvningsorder.</p></aside></div>`;
 else{const list=hubCandidates(tab);recruitHub.page=Math.min(recruitHub.page,Math.max(0,Math.ceil(list.length/20)-1));const visible=list.slice(recruitHub.page*20,recruitHub.page*20+20);if(!visible.some(p=>samePlayerId(p.id,recruitHub.player))){recruitHub.player=visible[0]?.id||null;recruitHub.panel='report';}body=`<div class="rh-workspace">${hubFilters(tab)}${hubPlayerTable(list,tab)}${hubInspector(findPlayerAnywhere(recruitHub.player))}</div>`;}
 return `<section class="recruit-hub">${hubHeader()}${r.message?`<p class="rh-notice" role="status">${trainingSafe(r.message)}</p>`:''}${state.loans.message&&['loans','deals'].includes(tab)?`<p class="rh-notice" role="status">${trainingSafe(state.loans.message)}</p>`:''}${body}</section>`;
}

function recruitHubPlayerView(){const p=findPlayerAnywhere(state.selectedMarketPlayer);if(!p)return '<p>Spelaren finns inte längre i databasen.</p>';if(!samePlayerId(recruitHub.player,p.id)){recruitHub.player=p.id;recruitHub.panel=state.transferNegotiation&&samePlayerId(state.transferNegotiation.playerId,p.id)?'transfer':'report';}return `<section class="recruit-hub"><button class="rh-link" onclick="deskBack('transfers')">← Tillbaka till urvalet</button><div class="rh-full-profile">${desktopAttributes(p)}${hubInspector(p)}</div><details class="rh-background"><summary>Fullständig rapport, bakgrund & hälsa</summary>${assessmentPanel(p)}${medicalPlayerPanel(p)}</details></section>`;}
