const assert=require('node:assert/strict');const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;r(`startCareerWithClub('HV71');deskNavigate('transfers','search');
 globalThis.target=findPlayerAnywhere(getTransferMarketPlayers().find(p=>p.pos==='C').id);
 globalThis.other=findPlayerAnywhere(getTransferMarketPlayers().find(p=>p.pos==='C'&&p.id!==target.id).id);
 for(const p of [target,other]){for(const k of Object.keys(p.attributes))p.attributes[k]=p===target?15:5;scoutObserve(p.id,state.calendar.date);}
 target.name='ZZ test';other.name='AA test';hubNeed('Spelfördelare');`);
assert.ok(r("hubCandidates('search').findIndex(p=>p.id===target.id)<hubCandidates('search').findIndex(p=>p.id===other.id)"),'role rank survives hub sorting');
assert.match(r('hubRoleFit(target)'),/Spelfördelare.*\/20/);
r(`setRecruitFilter('attribute','passing');globalThis.a=playerAssessment(target);
 globalThis.bounds=assessmentBounds(a.estimated.passing,a.uncertainty);
 setRecruitFilter('minAttribute',bounds.high);setRecruitFilter('attributeMode','possible');`);
assert.ok(r('recruitCandidates().some(p=>p.id===target.id)'),'upper interval retains candidate');
r("setRecruitFilter('attributeMode','supported')");
assert.ok(!r('recruitCandidates().some(p=>p.id===target.id)'),'lower interval requires support');
r("setRecruitFilter('attributeMode','estimate')");
assert.ok(!r('recruitCandidates().some(p=>p.id===target.id)'),'legacy midpoint differs from possible');
r("setRecruitFilter('minAttribute',bounds.low);setRecruitFilter('attributeMode','supported')");
assert.ok(r('recruitCandidates().some(p=>p.id===target.id)'));
r(`globalThis.before=JSON.stringify(recruitCandidates().map(p=>p.id));
 for(const k of Object.keys(target.attributes))target.attributes[k]=1;`);
assert.equal(r('JSON.stringify(recruitCandidates().map(p=>p.id))'),r('before'),'filters use observed attributes');
r('save()');const loaded=boot(app.storage.value);
assert.equal(loaded.run('recruitFilters().attributeMode'),'supported');
assert.equal(loaded.run('JSON.stringify(recruitCandidates().map(p=>p.id))'),r('before'));
r("setRecruitFilter('attribute','reflexes');setRecruitFilter('attributeMode','possible')");
assert.ok(!r('recruitAttributeMatches(target,recruitFilters())'),'missing position attribute never matches');
r('resetRecruitFilters()');assert.equal(r("recruitFilters().attributeMode||'estimate'"),'estimate');
r("hubNeed('Målvakt')");assert.ok(r("hubCandidates('search').every(p=>p.pos==='MV')"));
assert.doesNotMatch(r('recruitmentView()'),/undefined|NaN/);
console.log('PASS: observed role ranking, interval filters, no attribute leakage, save/reload, reset and goalkeeper compatibility.');
