'use strict';
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r("startCareerWithClub('HV71');globalThis.goalies=managerRoster().filter(p=>p.pos==='MV');globalThis.mv=()=>recruitmentNeeds().find(n=>n.name==='Målvakt')");
assert.equal(r('goalies.length'),3);
assert.equal(r('mv().count'),3,'Glifford, Liv and Sandström all count as ready goalies');
assert.equal(r('mv().need'),0);
assert.equal(r('mv().futureNeed'),0,'both multi-year goalies count even below the role threshold');
assert.equal(r('mv().qualityGap'),1,'quality advice remains separate from headcount');
assert.match(r('scoutingCoverageView()'),/3<\/strong> i truppen · <b>3<\/b> spelklara/);
r('globalThis.levels=goalies.map(p=>({...p.attributes}));for(const p of goalies)for(const k in p.attributes)p.attributes[k]=1');
assert.equal(r('mv().count'),3);assert.equal(r('mv().need'),0);assert.equal(r('mv().futureNeed'),0);
r('goalies.forEach((p,i)=>p.attributes=levels[i]);goalies[0].health.injury={remaining:20};goalies[0].health.clearance="rest"');
assert.equal(r('mv().count'),2);assert.equal(r('mv().need'),0);
r('goalies[1].health.injury={remaining:10};goalies[1].health.clearance="rest"');
assert.equal(r('mv().count'),1);assert.equal(r('mv().need'),1);assert.equal(r('mv().temporary'),true);
assert.match(r('mv().reasons.join(" ")'),/10 dagar/);
r('goalies.forEach(p=>{delete p.health.injury;p.health.clearance="full";p.contractYears=1;})');
assert.equal(r('mv().need'),0);assert.equal(r('mv().futureNeed'),2,'expiring contracts concern next season only');
assert.equal(r('mv().priority'),'Täckt nu');
r("globalThis.arrival=findPlayerAnywhere(getTransferMarketPlayers().find(p=>p.pos==='MV').id);arrival.futureContract={buyer:managerClub(),joinYear:state.season.year+1};");
assert.equal(r('mv().futureNeed'),1);
r('arrival.futureContract.joinYear+=1');assert.equal(r('mv().futureNeed'),2,'later arrivals do not fill next season');
r('delete arrival.futureContract;goalies[1].contractYears=2;goalies[2].contractYears=2;globalThis.out=goalies[1];globalThis.owner=managerClub();state.clubRosters[owner]=managerRoster().filter(p=>p!==out);state.clubRosters["Brynäs IF"].push(out);state.loans.active.push({id:9901,playerId:out.id,owner,borrower:"Brynäs IF"});out.loanId=9901');
assert.equal(r('mv().total'),2);assert.equal(r('mv().need'),0);assert.equal(r('mv().futureNeed'),0,'outgoing loan returns as future depth');
r('out.futureContract={buyer:owner,joinYear:state.season.year+1}');
assert.equal(r('mv().secure'),2,'returning loan plus future arrival cannot double-count one player');
r('goalies[2].loanId=9902;state.loans.active.push({id:9902,playerId:goalies[2].id,owner:"Brynäs IF",borrower:owner})');
assert.equal(r('mv().secure'),1,'incoming loans are not secured next season by the owner contract');
r('goalies[2].futureContract={buyer:owner,joinYear:state.season.year+1}');
assert.equal(r('mv().secure'),2,'a contracted purchase of the current loanee does secure next season');
// A clean saved career remains compatible and the concrete workflow uses real actions.
const b=boot(),q=b.run;q("startCareerWithClub('HV71');globalThis.p=getTransferMarketPlayers().find(p=>medicalReady(p)&&!playerAssessment(p).known);deskNavigate('transfers','search');hubPick(p.id)");
assert.match(q('hubCandidateStep(p).title'),/Lär känna/);
q("scoutingDraft([p.id]);scoutingDraftSet('method','screen');globalThis.cost=scoutingQuote(scoutDesk.draft.players,scoutDesk.draft.method,scoutDesk.draft.person).fee;globalThis.cash=state.money;scoutingStart()");
assert.equal(q('cash-state.money'),q('cost'));assert.match(q('hubCandidateStep(p).title'),/pågår/);
q('globalThis.job=scoutingOffice().jobs[0];state.calendar.date=job.next;scoutingDay()');
assert.equal(q('job.status'),'completed');assert.match(q('hubCandidateStep(p).title'),/Kontrollera villkoren/);
q('scoutingOpenReports(p.id)');assert.equal(q('state.recruitment.tab'),'shortlist');assert.equal(q('scoutDesk.list'),'reports');assert.equal(q('recruitHub.player'),q('p.id'));
q('scoutingContact(p.id)');assert.match(q('hubCandidateStep(p).title'),/Inväntar/);
q('state.calendar.date=scoutingOffice().contacts[String(p.id)].due;scoutingDay()');assert.match(q('hubCandidateStep(p).title'),/Ta ställning/);
q('save()');const loaded=boot(b.storage.value);
assert.equal(loaded.run('recruitmentNeeds().find(n=>n.name==="Målvakt").need'),0);
assert.equal(loaded.run('scoutingOffice().jobs[0].status'),'completed');
for(const tab of ['overview','needs','search','missions','shortlist','deals']){q(`deskNavigate('transfers','${tab}')`);assert.doesNotMatch(q('recruitmentView()'),/undefined|NaN/);}
console.log('PASS: real HV71 depth, quality vs headcount, injuries, expiring contracts, arrivals, loan deduplication, concrete scouting/contact flow and save compatibility.');
