const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');calendarInitialPreseason();globalThis.target=getTransferMarketPlayers()[0];
 globalThis.fee=Math.round(clubMissionFee()/3);globalThis.cash=state.money;
 requestScoutReport(target.id,true);requestScoutReport(target.id,true);`);
assert.equal(r('cash-state.money'),r('fee'),'pending requests charge once');
r('for(let i=0;i<7;i++)calendarStep(true);advanceScoutReports()');
assert.equal(r('state.scoutReports[target.id].visits'),1,'calendar delivers observation');
r(`globalThis.observed=JSON.stringify(playerAssessment(target).estimated);
 for(const key of Object.keys(target.attributes))target.attributes[key]=1;
 save();`);
assert.equal(r('JSON.stringify(playerAssessment(target).estimated)'),r('observed'),'no live attribute leak');
r(`state.calendar.date=calAdd(state.calendar.date,7);scoutObserve(target.id,state.calendar.date);
 state.calendar.date=calAdd(state.calendar.date,7);scoutObserve(target.id,state.calendar.date);
 globalThis.fresh=playerAssessment(target);globalThis.cash=state.money;requestScoutReport(target.id,true);`);
assert.equal(r('state.money'),r('cash'),'fresh full report cannot be charged');
r(`state.calendar.date=calAdd(state.calendar.date,180);
 for(const key of Object.keys(target.attributes))target.attributes[key]=20;`);
assert.equal(r('JSON.stringify(playerAssessment(target).estimated)'),r('JSON.stringify(fresh.estimated)'));
assert.ok(r('playerAssessment(target).uncertainty>fresh.uncertainty'));
assert.ok(r('playerAssessment(target).familiarity<fresh.familiarity'));
r('requestScoutReport(target.id,true);requestScoutReport(target.id,true)');
assert.equal(r('cash-state.money'),r('fee'),'refresh has one fee');
r('state.calendar.date=calAdd(state.calendar.date,6);scoutDay()');
assert.equal(r('JSON.stringify(playerAssessment(target).estimated)'),r('JSON.stringify(fresh.estimated)'));
r('state.calendar.date=calAdd(state.calendar.date,1);scoutDay();save()');
assert.equal(r('state.scoutReports[target.id].visits'),3,'refresh preserves completed progress');
assert.notEqual(r('JSON.stringify(playerAssessment(target).estimated)'),r('JSON.stringify(fresh.estimated)'));
assert.equal(r('playerAssessment(target).familiarity'),r('fresh.familiarity'));
const id=JSON.stringify(r('String(target.id)')),loaded=boot(app.storage.value);
assert.equal(loaded.run(`JSON.stringify(state.scoutReports[${id}])`),r('JSON.stringify(state.scoutReports[target.id])'));
const legacy=JSON.parse(app.storage.value);legacy.assessmentVersion=1;
delete legacy.scoutReports[JSON.parse(id)].snapshot;delete legacy.scoutReports[JSON.parse(id)].origin;
const old=boot(JSON.stringify(legacy));
assert.equal(old.run(`state.scoutReports[${id}].origin`),'legacy');
assert.equal(old.run(`state.scoutReports[${id}].visits`),3);
assert.equal(old.run(`state.scoutReports[${id}].lastObserved`),legacy.scoutReports[JSON.parse(id)].lastObserved);
assert.ok(old.run(`scoutNeedsObservation(findPlayerAnywhere(${id}))`));
r(`globalThis.own=managerRoster()[0];globalThis.remembered=scoutRemember(own);globalThis.key=Object.keys(own.attributes)[0];
 own.attributes[key]=own.attributes[key]===20?1:20;`);
assert.equal(r('playerAssessment(own).estimated[key]'),r('own.attributes[key]'));
assert.notEqual(r('remembered.snapshot[key]'),r('own.attributes[key]'),'departure snapshot is independent');
console.log('PASS: calendar delivery, frozen knowledge, ageing, paid refresh, migration and save/reload.');
