"use strict";
// Scouting is a saved information process. No report reads a development ceiling.
const SCOUT_METHODS={screen:{name:'Första kartläggning',days:7,steps:1,factor:1,quality:.65,text:'Ett första underlag. Bra för att välja vilka spelare som förtjänar mer tid.'},detail:{name:'Fördjupad bevakning',days:7,steps:3,factor:3,quality:1,text:'Tre observationstillfällen. Starkare stöd för aktuell nivå och rollpassning.'},potential:{name:'Utvecklingsbedömning',days:7,steps:3,factor:3.3,quality:.9,text:'Tre tillfällen med fokus på utvecklingsmöjligheter. Potential är alltid en prognos.'}};
const SCOUT_LISTS={now:'Värva nu',next:'Nästa säsong',youth:'Framtidstalanger'};
const scoutDesk={draft:null,compare:[],list:'all',columns:'standard',horizon:0};
let scoutingUIOwner=null;
function ensureScoutingOffice(){
 if(!state.recruitment)return null;
 const o=state.recruitment.scouting??={version:1,jobs:[],nextId:1,lists:{},contacts:{},reviews:[],coverage:{},delegation:{enabled:false,monthly:25000,spent:0,month:''},lastDay:null};
 if(scoutingUIOwner!==state){scoutingUIOwner=state;scoutDesk.draft=null;scoutDesk.list='all';scoutDesk.columns='standard';scoutDesk.horizon=0;o.compare=Array.isArray(o.compare)?o.compare.filter(id=>typeof id==='string'||typeof id==='number').slice(0,4):[];scoutDesk.compare=o.compare;}
 return o;
}
function scoutingOffice(){return state.recruitment?.scouting;}
function scoutingStaff(){return (state.staff||[]).filter(s=>['scout','assistant','goalie'].includes(s.id));}
function scoutingPerson(s){return String(s.personId||s.id);}
function scoutingRegion(p){return recruitCountry(getPlayerClub(p.id));}
function scoutingCoverage(s,region){return Math.min(95,(region==='SWE'?65:20)+(scoutingOffice()?.coverage[scoutingPerson(s)+':'+region]||0)+(state.clubOffice?.priority==='international'?15:0));}
function scoutingBusy(s){return (scoutingOffice()?.jobs||[]).some(j=>j.status==='active'&&j.person===scoutingPerson(s));}
function scoutingPrior(p){const base=leagueOf(getPlayerClub(p.id))==='HA'?10.3:11.3;return Object.fromEntries(Object.keys(p.pos==='MV'?GOALIE_ATTRIBUTES:SKATER_ATTRIBUTES).map(k=>[k,base+(attrSeed(`${p.id}:public-prior:${k}`)-.5)*1.4]));}
function scoutingQuote(ids,method,person){const s=scoutingStaff().find(s=>scoutingPerson(s)===String(person)),m=SCOUT_METHODS[method],ps=ids.map(findPlayerAnywhere).filter(Boolean);if(!s||!m||!ps.length)return null;const regions=[...new Set(ps.map(scoutingRegion))],knowledge=Math.min(...regions.map(r=>scoutingCoverage(s,r))),travel=regions.some(r=>r!=='SWE')?3:0,interval=m.days+travel+Math.floor((100-knowledge)/35),fee=Math.round(clubMissionFee()/3*m.factor*ps.length*(1+travel*.18));return {s,m,regions,knowledge,interval,fee,days:interval*m.steps};}
function scoutingDraft(ids){ensureScoutingOffice();const players=[...new Set(ids.map(String))].map(findPlayerAnywhere).filter(p=>p&&!isOwnPlayer(p)&&!scoutPending(p.id)).slice(0,3).map(p=>p.id);if(!players.length)return recruitMessage('Välj en spelare som inte redan bevakas.');scoutDesk.draft={players,method:'detail',person:scoutingPerson(scoutingStaff().find(s=>!scoutingBusy(s))||scoutingStaff()[0]),profile:recruitFilters().profile,horizon:'now'};deskNavigate('transfers','missions');}
function scoutingDraftSet(key,value){if(!scoutDesk.draft)return;if(key==='method'&&SCOUT_METHODS[value]||key==='person'&&scoutingStaff().some(s=>scoutingPerson(s)===value)||key==='profile'&&(value==='ALL'||RECRUIT_PROFILES[value])||key==='horizon'&&SCOUT_LISTS[value])scoutDesk.draft[key]=value;render();}
function scoutingStart(draft=scoutDesk.draft,automatic=false){
 const o=ensureScoutingOffice();if(!o||!draft||!managerCanPlay()||loanLocked())return false;
 const ids=[...new Set((draft.players||[]).map(String))];if(ids.length<1||ids.length>3)return false;
 const ps=ids.map(findPlayerAnywhere);if(ps.some(p=>!p||isOwnPlayer(p)||scoutPending(p.id)))return false;
 const q=scoutingQuote(ids,draft.method,draft.person);if(!q||scoutingBusy(q.s)||scoutActiveCount()>=clubMissionLimit()||state.money-clubForecast().reserved<q.fee)return automatic?false:recruitMessage('Uppdraget ryms inte i tillgänglig scoutkapacitet eller kassa.');
 const job={id:o.nextId++,club:managerClub(),players:ids,person:scoutingPerson(q.s),observer:{...q.s},method:draft.method,filters:{...recruitFilters()},profile:RECRUIT_PROFILES[draft.profile]?draft.profile:'ALL',horizon:SCOUT_LISTS[draft.horizon]?draft.horizon:'now',fee:q.fee,interval:q.interval,knowledge:q.knowledge,regions:q.regions,start:state.calendar.date,next:calAdd(state.calendar.date,q.interval),steps:0,delays:0,status:'active',automatic};
 clubPost('scouting',-q.fee,`${q.m.name} · ${q.s.name}`);o.jobs.unshift(job);o.jobs=o.jobs.filter(j=>j.status==='active').concat(o.jobs.filter(j=>j.status!=='active').slice(0,60));scoutDesk.draft=null;
 if(!automatic){save();render();}return true;
}
function scoutingClose(j,status,reason){if(j.status!=='active')return;j.status=status;j.ended=state.calendar.date;j.reason=reason;const m=SCOUT_METHODS[j.method];j.refund=j.club===managerClub()?Math.round(j.fee*Math.max(0,m.steps-j.steps)/m.steps*.7):0;if(j.refund)clubPost('scouting',j.refund,'Återstående scoutarbete · '+j.observer.name);}
function scoutingCancel(id){const j=scoutingOffice()?.jobs.find(j=>j.id===Number(id));if(!j||loanLocked())return;scoutingClose(j,'cancelled','Avbrutet av klubben. 70 % av ej utfört arbete återbetalas; planering och resor har kostat.');save();render();}
function scoutingContact(id){const p=findPlayerAnywhere(id),o=ensureScoutingOffice();if(!p||isOwnPlayer(p)||loanLocked()||!managerCanPlay())return false;const c=o.contacts[String(id)];if(c&&(c.status==='pending'||c.club===getPlayerClub(id)&&calGap(c.date,state.calendar.date)<30))return false;o.contacts[String(id)]={owner:managerClub(),status:'pending',due:calAdd(state.calendar.date,2),date:state.calendar.date,club:getPlayerClub(id)};save();render();return true;}
function scoutingContactKnown(p){const c=scoutingOffice()?.contacts[String(p.id)];return c&&(!c.owner||c.owner===managerClub())&&c.status==='answered'&&c.club===getPlayerClub(p.id)&&calGap(c.date,state.calendar.date)<30?c:null;}
function scoutingCost(p){if(isOwnPlayer(p))return {low:p.salary,high:p.salary,feeLow:recruitFee(p),feeHigh:recruitFee(p),known:true,interest:'Egen spelare'};const c=scoutingContactKnown(p);if(c)return {low:c.salary,high:c.salary,feeLow:c.fee,feeHigh:c.fee,known:true,interest:c.interest};const a=playerAssessment(p),level=attributeWeighted(a.estimated,p.pos==='MV'?PLAYER_ROLES.Målvakt:PLAYER_ROLES[roleWeights(p)[0]]),base=Math.round(Math.max(250000,(level-6)*150000)/50000)*50000;return {low:Math.round(base*.65),high:Math.round(base*1.55),feeLow:worldIsFree(p.id)?0:Math.round(base*.5),feeHigh:worldIsFree(p.id)?0:Math.round(base*3.5),known:false,interest:scoutingOffice()?.contacts[String(p.id)]?.status==='pending'?'Inväntar kontaktbesked':'Ej kontaktad'};}
function scoutingList(id,value){const p=findPlayerAnywhere(id),o=ensureScoutingOffice();if(!p||!SCOUT_LISTS[value])return;o.lists[String(id)]={purpose:value,club:getPlayerClub(id),contract:p.contractYears,date:state.calendar.date};if(!state.recruitment.shortlist.some(x=>samePlayerId(x,id)))state.recruitment.shortlist.push(p.id);save();render();}
function scoutingCompare(id){ensureScoutingOffice();const p=findPlayerAnywhere(id);if(!p)return;const i=scoutDesk.compare.findIndex(x=>samePlayerId(x,id));if(i>=0)scoutDesk.compare.splice(i,1);else if(scoutDesk.compare.length<4)scoutDesk.compare.push(p.id);queueInterfaceSave();render();}
function scoutingDelegate(enabled,budget){const o=ensureScoutingOffice(),n=Number(budget);if(!Number.isFinite(n)||n<0||n>200000||loanLocked())return;o.delegation.enabled=Boolean(enabled);o.delegation.monthly=Math.round(n);save();render();}
function scoutingArrival(p,fee,salary,years,role){const o=ensureScoutingOffice();if(!o)return;const a=playerAssessment(p);o.reviews.unshift({id:p.id,name:p.name,date:state.calendar.date,club:managerClub(),fee,salary,years,known:a.known,estimated:a.known?{...a.estimated}:{},uncertainty:a.uncertainty,observer:a.known?a.staff.name:'Ingen tidigare observation',role:role||p.promisedRole||'Rotation',plan:squadPlacementPlan(p)||null,done:false});o.reviews=o.reviews.slice(0,40);}
function scoutingDay(){
 const o=ensureScoutingOffice(),date=state.calendar?.date;if(!o||!date||loanLocked()||o.lastDay===date)return;o.lastDay=date;
 for(const j of o.jobs.filter(j=>j.status==='active'&&j.next<=date)){
  if(j.club!==managerClub()||!scoutingStaff().some(s=>scoutingPerson(s)===j.person)){scoutingClose(j,'cancelled','Ansvarig scout eller klubb har ändrats. Ett nytt uppdrag behövs.');continue;}
  const ps=j.players.map(findPlayerAnywhere).filter(p=>p&&!isOwnPlayer(p));if(!ps.length){scoutingClose(j,'cancelled','Spelarna är inte längre aktuella på marknaden.');continue;}
  if(ps.some(p=>!medicalReady(p)||internationalAway(p,date))){j.delays++;j.next=calAdd(date,7);j.note='Observationen flyttas: skada eller landslagsuppdrag begränsar underlaget.';if(j.delays>=3)scoutingClose(j,'limited','Otillräcklig tillgång till spelarna. Tidigare observationer finns kvar.');continue;}
  const m=SCOUT_METHODS[j.method];let observed=0;
  for(const p of ps){const r=state.scoutReports[String(p.id)];if(r?.lastObserved&&calGap(r.lastObserved,date)<7)continue;
   if(scoutObserve(p.id,date,{observer:j.observer,quality:m.quality*(.8+j.knowledge/500),focus:j.method,force:true,job:j.id}))observed++;
  }
  if(!observed){j.next=calAdd(date,7);continue;}j.steps++;j.note='Daterat observationsunderlag levererat.';j.next=calAdd(date,j.interval);
  for(const region of j.regions){const key=j.person+':'+region;o.coverage[key]=Math.min(30,(o.coverage[key]||0)+2);}
  if(j.steps>=m.steps){j.status='completed';j.ended=date;for(const p of ps)if(!o.lists[String(p.id)])scoutingListQuiet(p,j.horizon);}
 }
 for(const [id,c] of Object.entries(o.contacts))if(c.status==='pending'&&c.due<=date){const p=findPlayerAnywhere(id);if(!p||isOwnPlayer(p)||c.owner&&c.owner!==managerClub()||getPlayerClub(id)!==c.club){c.status='unavailable';c.interest='Klubbläget har ändrats';c.salary=0;c.fee=0;c.date=date;continue;}const w=recruitPlayerWishes(p);Object.assign(c,{status:'answered',date,salary:w.salary,fee:recruitFee(p),role:w.role,minYears:w.minYears,maxYears:w.maxYears,interest:w.stretch?'Tveksam till nivån':'Öppen för diskussion'});managerMessage(`sc-contact:${id}:${date}`,`Kontakt: ${p.name}`,`${c.interest}. Indikerad årslön ${careerMoney(c.salary)}. Detta är ett förhandlingsläge, inget accepterat avtal.`,'Sportchefen',{link:'transfers'});}
 for(const [id,l] of Object.entries(o.lists)){const p=findPlayerAnywhere(id);if(!p)continue;const club=getPlayerClub(id);if(club!==l.club||p.contractYears!==l.contract){managerMessage(`sc-watch:${id}:${date}`,`Bevakning: ${p.name}`,`${SCOUT_LISTS[l.purpose]}: klubbläget eller kontraktet har ändrats. ${club} · ${p.contractYears} kontraktsår. Se över din plan.`,'Chefsscout',{link:'transfers'});l.club=club;l.contract=p.contractYears;}}
 for(const v of o.reviews)if(!v.done&&calGap(v.date,date)>=42){const p=v.club===managerClub()&&managerRoster().find(p=>samePlayerId(p.id,v.id));if(!p){v.done=true;v.outcome='Spelaren finns inte längre i truppen.';continue;}const games=(p.roleGames||[]).filter(g=>g.club===v.club&&g.date>=v.date),minutes=games.length?games.reduce((n,g)=>n+g.seconds,0)/60/games.length:0;v.done=true;v.checked=date;v.games=games.length;v.minutes=minutes;v.error=Object.keys(v.estimated).reduce((n,k)=>n+Math.abs(v.estimated[k]-(p.attributes[k]||v.estimated[k])),0)/Math.max(1,Object.keys(v.estimated).length);v.outcome=`${games.length} registrerade tillgängliga matcher, ${minutes.toFixed(1)} min/match. ${p.recruitmentPromise?'Rollöfte: '+(p.recruitmentPromise.result||'uppföljning pågår')+'.':'Inget särskilt introduktionslöfte.'} ${p.health?.injury?'Skada har begränsat förutsättningarna.':''} ${v.known===false?'Ingen scoutbedömning fanns vid värvningen, så någon jämförelse av scoutens träffsäkerhet görs inte.':`Skillnaden mot dagens träningsbedömning är ${v.error.toFixed(1)} attributsteg i snitt; både utveckling och tidigare osäkerhet kan bidra.`}`;managerMessage(`sc-review:${v.id}:${v.date}`,`Värvningsuppföljning: ${p.name}`,v.outcome,'Sportchefen',{link:'transfers'});}
 const d=o.delegation,month=date.slice(0,7);if(d.month!==month){d.month=month;d.spent=0;}
 if(d.enabled&&date.slice(8)==='01'){const s=scoutingStaff().find(s=>s.id==='scout'&&!scoutingBusy(s)),need=recruitmentNeeds().find(n=>n.need||n.futureNeed);if(s&&need){const p=recruitCandidates({...recruitFilters(),query:'',country:'ALL',profile:need.name,maxAge:30,maxFee:50000000,attribute:''}).find(p=>!scoutPending(p.id)&&scoutNeedsObservation(p)),draft=p&&{players:[p.id],person:scoutingPerson(s),method:'screen',profile:need.name,horizon:need.need?'now':'next'},q=draft&&scoutingQuote(draft.players,draft.method,draft.person);if(q&&d.spent+q.fee<=d.monthly&&scoutingStart(draft,true))d.spent+=q.fee;}}
 // Contacts are temporary information; reports and completed work have their own bounded histories.
 for(const [id,c] of Object.entries(o.contacts))if(c.status!=='pending'&&calGap(c.date,date)>180)delete o.contacts[id];
}
function scoutingListQuiet(p,purpose){const o=scoutingOffice();o.lists[String(p.id)]={purpose,club:getPlayerClub(p.id),contract:p.contractYears,date:state.calendar.date};if(!state.recruitment.shortlist.some(id=>samePlayerId(id,p.id)))state.recruitment.shortlist.push(p.id);}

function scoutingFilterMatches(p,f){const a=playerAssessment(p),c=scoutingContactKnown(p);return (!f.position||f.position==='ALL'||p.pos===f.position)&&(!f.hand||f.hand==='ALL'||scoutingHand(p)===f.hand)&&(!f.league||f.league==='ALL'||scoutingLeague(p)===f.league)&&(!f.knowledge||f.knowledge==='all'||(f.knowledge==='observed'?a.known:!a.known))&&(!f.interest||f.interest==='all'||(f.interest==='contacted'?Boolean(c):!c))&&p.age>=Number(f.minAge||0);}
function scoutingPlanOptions(){const o=scoutingOffice(),ids=[...managerRoster(),...(state.juniors?.roster||[]),...state.recruitment.shortlist.map(findPlayerAnywhere).filter(Boolean),...Object.values(state.clubRosters).flat().filter(p=>p.futureContract?.buyer===managerClub())];return [...new Map(ids.map(p=>[String(p.id),p])).values()];}
function scoutingPlanSave(year,slot,id){year=Number(year);const o=ensureScoutingOffice(),valid=/^(forwards:(?:[0-9]|1[01])|defense:[0-5]|goalie:[01]|(?:pp[12]):[0-4]|(?:pk[12]):[0-3])$/.test(slot),p=id?scoutingPlanOptions().find(p=>samePlayerId(p.id,id)):null;if(!o||loanLocked()||![state.season.year,state.season.year+1].includes(year)||!valid||id&&!p)return false;const type=slot.split(':')[0];if(p&&(type==='goalie'?p.pos!=='MV':p.pos==='MV'||type==='defense'&&p.pos!=='B'||type==='forwards'&&p.pos==='B'))return false;o.lineupPlans??={};const plan=o.lineupPlans[year]??={};if(id){const types=['forwards','defense'].includes(type)?['forwards','defense']:[type];for(const t of types){const defaults=t==='goalie'?[state.lines.goalie,managerRoster().find(p=>p.pos==='MV'&&!samePlayerId(p.id,state.lines.goalie))?.id]:['forwards','defense'].includes(t)?state.lines[t]:state.specialTeams[t];for(let i=0;i<(defaults||[]).length;i++){const key=t+':'+i;if(!Object.hasOwn(plan,key)&&samePlayerId(defaults[i],id))plan[key]='';}}}if(id){const group=type==='forwards'||type==='defense'?'skater':type;for(const [key,value] of Object.entries(plan))if(samePlayerId(value,id)&&((group==='skater'&&/^(forwards|defense):/.test(key))||key.startsWith(type+':')))plan[key]='';}plan[slot]=id||'';for(const k of Object.keys(o.lineupPlans))if(Number(k)<state.season.year-1)delete o.lineupPlans[k];save();render();return true;}

function scoutingHand(p){return p.shoots||p.research?.shoots||'';}
function scoutingLeague(p){return state.world?.membership?.[getPlayerClub(p.id)]||(worldIsFree(p.id)?'FREE':'OTHER');}
