'use strict';
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const {run,storage}=boot();
run("startCareerWithClub('HV71');ensurePlayerWorld();state.money=150000000");
function snapshot(){return JSON.parse(run(`(()=>{const rosters=Object.entries(state.clubRosters).filter(([club])=>club!==managerClub()).map(([,roster])=>roster),players=rosters.flat(),skaters=players.filter(p=>p.pos!=='MV'),attrs=skaters.flatMap(p=>Object.values(p.attributes||{}));return JSON.stringify({year:state.season.year,minRoster:Math.min(...rosters.map(r=>r.length)),maxRoster:Math.max(...rosters.map(r=>r.length)),minGoalies:Math.min(...rosters.map(r=>r.filter(p=>p.pos==='MV').length)),minDefense:Math.min(...rosters.map(r=>r.filter(p=>p.pos==='B').length)),minForwards:Math.min(...rosters.map(r=>r.filter(p=>worldGroup(p)==='F').length)),avgAge:players.reduce((n,p)=>n+p.age,0)/players.length,maxAge:Math.max(...players.map(p=>p.age)),avgAttribute:attrs.reduce((n,x)=>n+x,0)/attrs.length,eliteShare:attrs.filter(x=>x>=18).length/attrs.length,freeAgents:state.playerWorld.freeAgents.length,transfers:state.recruitment.history.length,retired:state.playerWorld.summaries.reduce((n,s)=>n+s.retired,0),historyEvents:ensureCareerHistory().events.length,managerCash:state.money,aiCashMin:Math.min(...Object.values(state.recruitment.ai).map(x=>x.cash)),duplicateIds:players.length-new Set(players.map(p=>String(p.id))).size})})()`));}
// AI clubs rebuild via beginPreseason; the human club still requires manager decisions.
const years=[];
for(let i=0;i<10;i++){run("state.season.phase='review';state.season.boardResult=[];beginPreseason();ensurePlayerWorld();ensureRecruitment()");const s=snapshot();years.push(s);assert.equal(s.duplicateIds,0);assert.ok(s.minRoster>=20&&s.maxRoster<=30);assert.ok(s.minGoalies>=2);assert.ok(s.minDefense>=6);assert.ok(s.minForwards>=12);assert.ok(s.avgAge>=22&&s.avgAge<=30);assert.ok(s.maxAge<44);assert.ok(s.avgAttribute>=7&&s.avgAttribute<=16);assert.ok(s.eliteShare<.18);assert.ok(s.freeAgents<500);assert.ok(s.historyEvents<=1200);assert.ok(Number.isFinite(s.managerCash)&&Number.isFinite(s.aiCashMin));}
assert.ok(years.at(-1).retired>years[0].retired);assert.ok(years.at(-1).transfers>=years[0].transfers);assert.ok(Math.abs(years.at(-1).avgAttribute-years[0].avgAttribute)<2);
run('save()');const reload=boot(storage.value);assert.equal(reload.run('state.season.year'),run('state.season.year'));assert.equal(reload.run('Object.values(state.clubRosters).flat().length'),run('Object.values(state.clubRosters).flat().length'));
console.log('PASS: 10-season soak keeps ownership, roster depth, goalies, age, attributes, free agents, economy and history bounded.');
