'use strict';
const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r(`startCareerWithClub('HV71');medicalRoll=()=>.999;
globalThis.p=managerRoster().find(p=>p.pos==='C');
globalThis.rest=managerRoster().find(q=>q.id!==p.id&&q.pos!=='MV');
globalThis.away=managerRoster().find(q=>q.id!==p.id&&q.id!==rest.id&&q.pos!=='MV');
p.fatigue=50;p.health.load=20;rest.fatigue=70;rest.health.load=20;rest.name=p.name;
away.fatigue=43;away.internationalDuty={year:2027,nation:'SWE',from:'2026-09-01',until:'2026-10-01',returned:false};
setRecoveryOwner('staff');calendarSetSession(state.calendar.date,'type','powerplay');calendarSetSession(state.calendar.date,'intensity','hard');
globalThis.preview=trainingTeamProjection(calendarSession(state.calendar.date));globalThis.date=state.calendar.date;`);
const before=r('JSON.stringify(state)');
r('trainingCalendarDecision(date,calendarSession(date));managerDayPreview();trainingTeamProjection(calendarSession(date))');
assert.equal(r('JSON.stringify(state)'),before,'projections never perform decisions or draw randomness');
assert.equal(r('managerDayPreview().trained'),r('preview.trained'));
assert.equal(r('managerDayPreview().absent'),1);
assert.equal(r('preview.rows.some(row=>row.player.id===away.id)'),false);
assert.match(r('calendarAgenda(date)'),/Samma innehåll, lätt/);
assert.match(r('calendarAgenda(date)'),/matcher kommande sju dagar/);
assert.equal(r('trainingCalendarDecision(calAdd(date,1),calendarSession(date))'),'','no precise future-load fiction');
// Inspect the correct one of two identically named players, then restore the calendar context.
r("deskNavigate('calendar');calendarPick(date);globalThis.id=rest.id");
app.get('#content').scrollTop=237;
r('deskOpenPlayer(id);deskBack()');
assert.equal(r('state.page'),'calendar');assert.equal(r('calendarUI.date'),r('date'));
assert.equal(app.get('#content').scrollTop,237);
r('dayTransitionStart();dayTransitionRun(dayTransition)');
assert.equal(r('dayTransition'),null,'no additional required pause');
assert.equal(r('p.fatigue'),62);
assert.equal(r('p.health.load'),28,'hard pass stays hard after crossing staff-rest fatigue threshold');
assert.equal(r('rest.fatigue'),45);assert.equal(r('rest.health.load'),16);
assert.equal(r('away.fatigue'),43,'away player did not receive imaginary recovery');
assert.equal(r('state.training.history[0].trained'),r('preview.trained'));
assert.equal(r('state.training.history[0].resting'),r('preview.resting'));
assert.equal(r('state.training.powerplay'),r('preview.after.powerplay'));
assert.equal(r('currentTrainingFamiliarity()'),r('preview.after.familiarity'));
assert.equal(r('state.training.history[0].after'),r('preview.fatigueAfter'));
assert.equal(r('state.training.messages.filter(m=>m.key.startsWith("training-return:")).length'),0,'routine delegated rest sends no per-player expiry messages');
assert.equal(r('state.training.messages.filter(m=>m.key.startsWith("session:")).length'),1);
r('globalThis.log=state.training.history[0];globalThis.report=state.training.messages.find(m=>m.trainingDate===date);messageOpenContext(report.id)');
assert.equal(r('calendarUI.date'),r('date'));assert.equal(r('state.page'),'calendar');
assert.equal(r('log.evidence.players.find(row=>row.id===rest.id).delegated'),true);
assert.equal(r('log.evidence.players.find(row=>row.id===p.id).delegated'),false);
assert.match(r('trainingDecisionReport(log)'),/#player\//);
assert.match(r('trainingDecisionReport({})'),/saknas i den äldre rapporten/);
const snapshot=r('JSON.stringify(log.evidence)');
r('p.fatigue=20;rest.name="Ändrat senare";save()');
assert.equal(r('JSON.stringify(log.evidence)'),snapshot,'historical measurements and names never follow later changes');
const restored=boot(app.storage.value),s=restored.run;
assert.equal(s('JSON.stringify(state.training.history[0].evidence)'),snapshot);
assert.equal(s('JSON.stringify(validateSaveText(saveExportText()).training.history[0].evidence)'),snapshot);
// Old saves need no made-up evidence or destructive migration.
const legacy=JSON.parse(app.storage.value);legacy.training.history.forEach(l=>delete l.evidence);
const old=boot(JSON.stringify(legacy));assert.match(old.run('trainingDecisionReport(state.training.history[0])'),/saknas/);
assert.equal(old.run('state.training.history[0].trained'),r('log.trained'));
// Planned expiry and manual choices have the same authority in preview and execution.
s(`resumeCareer();medicalRoll=()=>.999;globalThis.p=managerRoster().find(p=>p.pos==='C');p.fatigue=70;
p.trainingLoad='rest';p.trainingReturn={club:managerClub(),load:'rest',date:state.calendar.date,start:calAdd(state.calendar.date,-1),before:70,trained:0,rested:1};
globalThis.effect=trainingSessionEffect(p,{type:'skills',intensity:'hard'});`);
assert.equal(s('effect.rest'),true,'expired plan is followed by delegated recovery');
s('setIndividualLoad(p.id,"normal")');assert.equal(s('trainingSessionEffect(p,{type:"skills",intensity:"hard"}).hard'),true,'today manual override wins');
// Complete the production preparation → match → report → next training day chain.
s(`globalThis.days=0;while(state.calendar.date<calendarTarget()&&days++<10)calendarContinue();startMatch();pauseMatch();
globalThis.expected=attrClamp(trainingMatchBonus()+lockerMatchBonus()+rivalPreparationBonus(),-6,6);
startMatch();studioStep();pauseMatch();`);
assert.equal(s('studioEngine().teamBonus'),s('expected'),'actual preparation reaches the production engine');
const noPass=s('JSON.stringify(state.training.history)');s('runTrainingSession()');assert.equal(s('JSON.stringify(state.training.history)'),noPass);
s(`globalThis.steps=0;while(!state.live.finished&&steps++<65000){if(!state.live.running){while(medicalPending())medicalDecisionAccept();startMatch();}studioStep();}`);
assert.equal(s('state.live.finished'),true);assert.equal(s('state.live.analysis.saved'),true);
s('calendarContinue();calendarContinue();save()');
assert.equal(s('state.calendar.date'),'2026-09-28');
assert.equal(s('state.training.history.length'),4);
const final=boot(restored.storage.value);
assert.equal(final.run('JSON.stringify(state.training.history)'),s('JSON.stringify(state.training.history)'));
assert.equal(final.run('JSON.stringify(state.analysis.matches[0])'),s('JSON.stringify(state.analysis.matches[0])'));
console.log('PASS: real pass projections and medical exposure, absent players, manual/delegated authority, no expiry spam, ID navigation, immutable evidence, old saves, full production week and archived match. Automated workflow; not visual playtesting.');
