const assert=require('node:assert/strict');
const {boot}=require('./scripts/career-test-fixture.cjs');
const app=boot(),r=app.run;
r("startCareerWithClub('HV71');deskNavigate('finance');clubSetPolicy('ticket',280)");
assert.match(r('state.clubOffice.message'),/uppdaterad/);
r('render()');assert.ok(r('state.clubOffice.message'),'normal rerender retains action feedback');
r("deskNavigate('staff')");assert.equal(r('state.clubOffice.message'),'','finance message must not appear on staff');
assert.equal(r('state.clubOffice.ticket'),280,'clearing feedback never reverses policy');
r("deskNavigate('transfers','search');createScoutMission(hubScoutIds())");
assert.ok(r('state.recruitment.message'));const missions=r('state.recruitment.missions.length');
r("deskNavigate('transfers','needs')");assert.equal(r('state.recruitment.message'),'');assert.equal(r('state.recruitment.missions.length'),missions);
assert.match(r('recruitmentHubView()'),/Spelare kan passa flera roller/);
const firstNeed=r('recruitmentNeeds()[0].name');r(`hubNeed(${JSON.stringify(firstNeed)})`);assert.equal(r('recruitFilters().profile'),firstNeed);assert.equal(r('state.recruitment.tab'),'search');
r("deskNavigate('juniors');juniorNotice('Äldre besked');juniorSelect(juniorPlayers()[1].id)");assert.equal(r('state.juniors.message'),'');
r("deskNavigate('staffReview');staffReviewTab('coaching');deskNavigate('statistics');deskBack()");assert.equal(r('staffReviewUI.tab'),'coaching');
assert.match(r('staffReviewView()'),/<section hidden><button class="btn"/,'planning is not displayed in coaching workspace');
r("deskNavigate('match');matchOrder('tempo','high');matchOrder('shiftLength','short');save()");
assert.equal(r('state.tacticalPlan.tempo'),'high');assert.equal(r('state.tacticalPlan.shiftLength'),'short');
const saved=boot(app.storage.value);assert.equal(saved.run('state.tacticalPlan.tempo'),'high');assert.equal(saved.run('state.clubOffice.ticket'),280);assert.equal(saved.run('state.recruitment.missions.length'),missions);
assert.equal((r('matchOrdersView()').match(/<fieldset/g)||[]).length,4);
assert.equal((r('matchOrdersView()').match(/<select/g)||[]).length,8);
console.log('PASS: scoped feedback, real recruitment search/scout mission, junior selection, staff context back navigation, grouped tactical changes and save/reload.');

r("deskNavigate('transfers','needs');deskNavigate('staffReview')");assert.equal(r('staffReviewUI.tab'),'planning','new planning entry must not land on the previous coaching tab');
r("state.clubOffice.message='Besked från föregående session';save()");
const resumed=boot(app.storage.value);resumed.run('resumeCareer()');assert.equal(resumed.run('state.clubOffice.message'),'');assert.equal(resumed.run('state.clubOffice.ticket'),280);
