"use strict";
// Presentation state stays separate from the career's tournaments, rights and contracts.
const worldUI={international:'club',person:null,draftPerson:null,position:'all',draftPage:0,draftYear:'latest',games:'all',drawer:null,actionId:null,plan:'open'};
const worldDeskView={};
function worldDeskContext(){return state.page+':'+(state.page==='international'?worldUI.international:state.page==='nhl'?nhlUI.tab+':'+naUI.tab+':'+nasUI.tab:'overview');}
function worldDeskCapture(){const root=document.querySelector('.world-desk');if(!root?.dataset)return;worldDeskView.context=root.dataset.context;worldDeskView.scroll=Array.from(root.querySelectorAll('[data-scroll-key]')).map(e=>[e.dataset.scrollKey,e.scrollTop,e.scrollLeft]);const d=document.getElementById('world-dialog');worldDeskView.dialog=d?.open?d.dataset.context:null;if(d?.open){worldDeskView.top=d.scrollTop;worldDeskView.focus=Array.from(d.querySelectorAll('button,input,select')).indexOf(document.activeElement);}}
function worldDeskRestore(){const root=document.querySelector('.world-desk');if(!root?.dataset)return;if(root.dataset.context===worldDeskView.context)for(const [key,top,left] of worldDeskView.scroll||[]){const el=root.querySelector(`[data-scroll-key="${key}"]`);if(el){el.scrollTop=top;el.scrollLeft=left;}}const d=document.getElementById('world-dialog');if(d){d.showModal();if(d.dataset.context===worldDeskView.dialog){d.scrollTop=worldDeskView.top||0;d.querySelectorAll('button,input,select')[worldDeskView.focus]?.focus({preventScroll:true});}}}
function worldDeskSet(key,value){if(!Object.hasOwn(worldUI,key))return;worldUI[key]=value;worldUI.drawer=null;if(['position','international'].includes(key))worldUI.draftPage=0;render();queueInterfaceSave();}
function worldDeskSearch(form){nhlUI.query=form.elements.query.value.trim().slice(0,80);worldUI.draftPage=0;render();}
function worldDeskNation(value){if(!INT_NATIONS[value])return;state.international.selected=value;render();queueInterfaceSave();}
function worldDeskGo(page,tab){deskNavigate(page);if(page==='international'&&tab)worldUI.international=tab;if(page==='nhl'&&tab)nhlUI.tab=tab;render();queueInterfaceSave();}
function worldDeskOpen(kind,id=null){worldDeskView.returnText=document.activeElement?.textContent;worldUI.drawer=kind;worldUI.actionId=id;worldUI.plan='open';render();}
function worldDeskClose(){worldUI.drawer=null;worldUI.actionId=null;if(state.page==='nhl'&&nhlUI.tab==='leagues')nasUI.game=null;render();const bs=Array.from(document.querySelectorAll('button'));(bs.find(b=>b.textContent===worldDeskView.returnText)||document.querySelector('.wd-selected button'))?.focus?.();}
function worldDeskConfirm(){const kind=worldUI.drawer,id=worldUI.actionId,path=worldUI.plan;worldUI.drawer=null;worldUI.actionId=null;if(kind==='plan')nhlSetPlan(id,path);else if(kind==='recovery')internationalRecovery(id);else if(kind==='move'||kind==='loanback'||kind==='reject')naAnswer(id,kind);else if(kind==='borrow')naBorrow(id);else if(kind==='recall')loanRecall(id);render();}
function worldDeskPlayer(id){return internationalPlayers().find(r=>samePlayerId(r.p.id,id))?.p;}
function worldDeskPickButton(key,id,label){return `<button aria-pressed="${String(worldUI[key])===String(id)}" onclick="${trainingSafe('worldDeskSet('+JSON.stringify(key)+','+JSON.stringify(id)+')')}">${trainingSafe(label)}</button>`;}
function worldDeskProfileButton(p){return `<button class="wd-outline" onclick="${trainingSafe('deskOpenPlayer('+JSON.stringify(p.id)+')')}">Öppna spelarprofil →</button>`;}
function worldDeskTabs(label,key,values){return `<nav class="wd-tabs" aria-label="${label}">${Object.entries(values).map(([v,text])=>`<button aria-pressed="${(key==='nhl'?nhlUI.tab:worldUI[key])===v}" onclick="${key==='nhl'?`nhlSetFilter('tab','${v}')`:`worldDeskSet('${key}','${v}')`}">${text}</button>`).join('')}</nav>`;}
function worldDeskMetrics(items){return `<div class="wd-metrics">${items.map(([label,value,note])=>`<div><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('')}</div>`;}
function worldDeskFrame(title,subtitle,metrics,body){return `<section class="world-desk" data-context="${worldDeskContext()}"><header class="wd-heading"><div><span class="wd-eyebrow">HOCKEYVÄRLDEN · ${calText(state.calendar.date)}</span><h1>${title}</h1><p>${subtitle}</p></div><span class="wd-globe" aria-hidden="true">${deskIcon('globe')}</span></header>${worldDeskMetrics(metrics)}${body}${worldDeskDialog()}</section>`;}
function worldDeskPanel(title,body,note='',controls='',footer=''){return `<section class="wd-panel"><header><div><h2>${title}</h2>${note?`<p>${note}</p>`:''}</div>${controls}</header><div class="wd-scroll" data-scroll-key="${state.page}-${title.replace(/[^a-zA-Z]/g,'')}">${body}</div>${footer?`<footer>${footer}</footer>`:''}</section>`;}
function worldDeskEmpty(text,columns=1){return `<tr><td class="wd-empty" colspan="${columns}">${text}</td></tr>`;}
function worldDeskStatus(t){return t.skipped?'Ej bevakad':t.returned?'Avslutad':t.medals.length?'Avgjord':t.status==='playing'?'Pågår':t.departed?'Samling':t.announced?'Trupper uttagna':'Inför uttagning';}
function worldDeskOwnInternational(){const t=state.international.tournament;return internationalPlayers().filter(r=>r.club===managerClub()&&(internationalEligible(r.p,t.year)||r.p.internationalDuty?.year===t.year||r.p.internationalHistory?.[0]?.year===t.year));}
function worldDeskOwnDraft(){const d=state.nhl.draft;return internationalPlayers().filter(r=>nhlOwned(r.p)&&(r.p.nhlDraft||nhlEligible(r.p,d.year)));}
function worldDeskMilestones(){
 const t=state.international?.tournament,d=state.nhl?.draft,today=state.calendar.date,rows=[];
 const add=(date,title,detail,page,tab)=>{if(date>=today)rows.push({date,title,detail,page,tab});};
 if(t&&!t.skipped&&!t.returned){if(!t.announced)add(`${t.year-1}-12-15`,'JVM-trupperna tas ut','Följ vilka talanger som blir uttagna.','international','club');if(!t.departed)add(`${t.year-1}-12-20`,'JVM-samling','Uttagna spelare lämnar klubblagets verksamhet.','international','club');const next=t.games.filter(g=>!g.played&&g.date>=today).sort((a,b)=>a.date.localeCompare(b.date))[0];if(next)add(next.date,'Nästa JVM-matchdag',t.games.filter(g=>!g.played&&g.date===next.date).length+' schemalagda matcher.','international','tournament');else if(!t.departed)add(`${t.year-1}-12-26`,'JVM:s matchperiod börjar','Matcher till 5 januari. Schema publiceras vid samlingen.','international','tournament');add(`${t.year}-01-06`,'Landslagsspelarna återvänder','Följ upp belastning och träning.','international','club');}
 if(d?.status==='upcoming')add(d.date,'NHL-draft '+d.year,'Draftval ger rättigheter; klubbavtalen består.','nhl','board');
 for(const league of ['NHL','AHL']){const games=state.naLeagues?.season.leagues[league].games||[],next=games.filter(g=>!g.played&&g.date>=today).sort((a,b)=>a.date.localeCompare(b.date))[0];if(next)rows.push({date:next.date,title:league+' · nästa matchdag',detail:games.filter(g=>!g.played&&g.date===next.date).length+' matcher i karriärens spelschema.',league});}
 return rows.sort((a,b)=>a.date.localeCompare(b.date)||a.title.localeCompare(b.title));
}
function worldDeskClubAside(){const own=internationalPlayers().filter(r=>r.club===managerClub()),away=own.filter(r=>internationalAway(r.p)),offers=(state.northAmerica?.offers||[]).filter(o=>o.origin===managerClub()&&o.status==='pending'),plans=own.filter(r=>r.p.nhlPlan?.status==='active'),recovery=own.filter(r=>worldDeskCanRecover(r.p));return `<aside class="wd-aside"><header><h2>Det berör din klubb</h2><small>${trainingSafe(managerClub())}</small></header><div data-scroll-key="world-club"><article><span class="wd-kicker">LANDSLAGSUPPDRAG</span><h3>${away.length} spelare borta</h3><p>${away.length?away.map(r=>playerReference(r.p.id,r.p.name)).join(', '):'Ingen spelare saknas på grund av JVM just nu.'}</p>${away.length?'<button class="wd-link" onclick="deskNavigate(\'lines\')">Planera ersättare →</button>':'<button class="wd-link" onclick="worldDeskGo(\'international\',\'club\')">Följ klubbens talanger →</button>'}</article>${recovery.length?`<article><h3>${recovery.length} återvändare att följa upp</h3><p>Granska belastningen efter landslagsuppdraget.</p><button class="wd-link" onclick="worldDeskGo('international','club')">Bedöm återhämtningen →</button></article>`:''}<article><span class="wd-kicker">NHL-ERBJUDANDEN</span><h3>${offers.length} väntar på beslut</h3><p>${offers.length?offers.map(o=>trainingSafe(o.name)+' · svar '+calText(o.expires)).join('<br>'):'Inga obesvarade erbjudanden till klubben.'}</p><button class="wd-link" onclick="naUI.tab='offers';worldDeskGo('nhl','contracts')">Avtal & utlandsflyttar →</button></article><article><span class="wd-kicker">UTVECKLINGSLÖFTEN</span><h3>${plans.length} pågående</h3><p>${plans.length?plans.map(({p})=>playerReference(p.id,p.name)+' · '+p.nhlPlan.met+'/'+p.nhlPlan.targetGames+' istidsmål').join('<br>'):'Inga aktiva istidslöften efter draften.'}</p><button class="wd-link" onclick="worldDeskGo('nhl','club')">Följ klubbens draftspelare →</button></article></div><footer>Uppgifterna följer händelser i din sparade karriär.</footer></aside>`;}
function worldHockeyNews(){
 ensureRivals();const rival=(state.rivals?.events||[]).map(e=>({date:e.date,kind:e.kind,club:e.club,title:e.titleParts||e.title,text:e.textParts||e.text,source:'Liga'}));
 const feedback=(ensureManagerFeedback()?.news||[]).map(e=>({date:e.date,kind:e.kind,club:e.club,title:e.title,text:e.text,source:'Hockeyvärlden'}));
 return [...rival,...feedback].filter(e=>e.date<=state.calendar.date).sort((a,b)=>b.date.localeCompare(a.date)).filter((e,i,a)=>a.findIndex(x=>x.date===e.date&&String(x.title)===String(e.title)&&x.club===e.club)===i).slice(0,20);
}
function worldHockeyNewsView(){
 const rows=worldHockeyNews();return worldDeskPanel('Senaste från hockeyvärlden',rows.map(e=>`<article class="wd-news"><span class="wd-kicker">${calText(e.date)} · ${trainingSafe(e.club||e.source)}</span><h3>${playerReferenceText(e.title)}</h3><p>${playerReferenceText(e.text||'')}</p></article>`).join('')||'<p>Inga nya händelser har registrerats ännu. Tränarbyten, transfers, utvecklingshändelser och liganyheter samlas här när de sker.','Händelser ur den simulerade karriären – inte förgenererade rubriker.');
}
function worldDeskOverview(){
 const own=internationalPlayers().filter(r=>r.club===managerClub()),milestones=worldDeskMilestones(),d=state.nhl?.draft;
 const table=`<table class="wd-table wd-agenda"><thead><tr><th>Datum</th><th>Händelse</th><th>Följ upp</th></tr></thead><tbody>${milestones.map(m=>`<tr><td>${calText(m.date)}</td><th>${m.title}<small>${m.detail}</small></th><td><button class="wd-link" onclick="${m.league?`worldOpenLeague('${m.league}')`:`worldDeskGo('${m.page}','${m.tab}')`}">Öppna →</button></td></tr>`).join('')||worldDeskEmpty('Inga kommande internationella händelser är schemalagda.',3)}</tbody></table>`;
 const directory=`<footer class="wd-directory"><div><span class="wd-eyebrow">TÄVLINGAR & SPELARVÄGAR</span><h2>Följ hockeyvärlden</h2></div><button onclick="worldOpenLeague('NHL')"><b>NHL</b><small>${nasClubs('NHL').length} klubbar · tabell & matcher</small></button><button onclick="worldOpenLeague('AHL')"><b>AHL</b><small>${nasClubs('AHL').length} klubbar · tabell & matcher</small></button><button onclick="worldDeskGo('international','tournament')"><b>JVM ${state.international.tournament.year}</b><small>${Object.keys(INT_NATIONS).length} landslag · ${worldDeskStatus(state.international.tournament)}</small></button><button onclick="deskNavigate('leagues')"><b>Ligorna</b><small>Klubbar, tabeller & säsonger</small></button></footer>`;
 return worldDeskFrame('Världen','Internationell hockey med din klubbs spelare i fokus.',[['På landslagsuppdrag',own.filter(r=>internationalAway(r.p)).length,'Spelare från din klubb'],['Inför draften '+d.year,own.filter(r=>nhlEligible(r.p,d.year)).length,'Spelare i aktuell draftålder'],['NHL-erbjudanden',(state.northAmerica?.offers||[]).filter(o=>o.origin===managerClub()&&o.status==='pending').length,'Inväntar ditt beslut'],['Utvecklingslöften',own.filter(r=>r.p.nhlPlan?.status==='active').length,'Pågående löften efter draften']],`<div class="wd-main">${worldHockeyNewsView()}${worldDeskPanel('På den internationella kalendern',table,'Nästa steg i karriärens turneringar och ligor','','Datum och resultat gäller spelvärlden.')}${worldDeskClubAside()}</div>${directory}`);
}
function worldDeskCanRecover(p){const h=p.internationalHistory?.[0];return Boolean(managerRoster().some(q=>samePlayerId(q.id,p.id))&&h&&h.club===managerClub()&&!h.followup&&h.returnDate<=state.calendar.date&&calGap(h.returnDate,state.calendar.date)<=7&&!internationalAway(p));}
function worldDeskInternationalState(p,t){const e=Object.values(t.rosters).flat().find(e=>samePlayerId(e.id,p.id));return internationalAway(p)?'På JVM':e?.withdrawn?'Återbud':p.internationalHistory?.[0]?.year===t.year&&t.returned?'Åter i klubben':e?'Uttagen':t.skipped?'Ej bevakad':t.announced?'Utanför truppen':'Aktuell årskull';}
function worldDeskInternationalClub(){const t=state.international.tournament,rows=worldDeskOwnInternational(),selected=rows.find(r=>samePlayerId(r.p.id,worldUI.person))||rows[0],p=selected?.p,e=p&&Object.values(t.rosters).flat().find(e=>samePlayerId(e.id,p.id));
 worldUI.person=p?.id||null;
 const table=`<table class="wd-table wd-people"><thead><tr><th>Spelare</th><th>Land / position</th><th>Landslagsstatus</th><th>Ork</th><th>JVM-insats</th></tr></thead><tbody>${rows.map(({p})=>{const s=Object.values(t.rosters).flat().find(e=>samePlayerId(e.id,p.id));return `<tr class="${selected?.p===p?'wd-selected':''}"><th>${worldDeskPickButton('person',p.id,p.name)}<small>${p.age} år${internationalIdentity(p).estimated?' · uppskattat födelseår':''}</small></th><td>${INT_NATIONS[internationalIdentity(p).nation]||trainingSafe(p.nationality)}<small>${p.pos}</small></td><td>${worldDeskInternationalState(p,t)}</td><td>${Math.round(100-(p.fatigue||0))} %</td><td>${s?`${s.games} M · ${s.goals}+${s.assists}<small>${Math.round(s.seconds/60)} minuter</small>`:'Ingen registrerad insats'}</td></tr>`;}).join('')||worldDeskEmpty('Ingen spelare i aktuell JVM-årskull i din klubb.',5)}</tbody></table>`;
 const detail=p?`<footer class="wd-inspector"><div><span class="wd-eyebrow">VALD SPELARE</span><h2>${playerReference(p.id,p.name)}</h2><p>${INT_NATIONS[internationalIdentity(p).nation]} · ${p.pos} · ${worldDeskInternationalState(p,t)}</p></div><div><h3>UTTAGNING & KLUBBROLL</h3><p>${e?trainingSafe(e.reason):'Nuvarande egenskaper, position, konkurrens, form och belastning avgör uttagningen.'}</p><small>${internationalAway(p)?'Tillbaka '+calText(p.internationalDuty.until)+'. Planera ersättare under frånvaron.':'Uttagning 15 december · samling 20 december · återkomst 6 januari.'}</small></div><div><h3>NÄSTA STEG</h3>${worldDeskCanRecover(p)?`<button class="wd-outline" onclick="${trainingSafe('worldDeskOpen(\'recovery\','+JSON.stringify(p.id)+')')}">Granska återhämtning</button>`:worldDeskProfileButton(p)}<button class="wd-link" onclick="deskNavigate('lines')">Planera laguttagningen →</button></div></footer>`:'';
 return `<div class="wd-main">${worldDeskPanel('Klubbens landslagstalanger',table,'Markera en spelare för status och uppföljning.','','Landslagsmatcher, belastning och frånvaro registreras separat från klubblagets resultat.')}${worldDeskInternationalAside()}</div>${detail}`;
}
function worldDeskInternationalAside(){const t=state.international.tournament;return `<aside class="wd-aside"><header><h2>JVM ${t.year}</h2><small>${worldDeskStatus(t)}</small></header><div data-scroll-key="international-dates"><dl class="wd-facts"><dt>Uttagning</dt><dd>15 december</dd><dt>Samling</dt><dd>20 december</dd><dt>Matcher</dt><dd>26 dec–5 jan</dd><dt>Återkomst</dt><dd>6 januari</dd></dl>${t.medals.length?`<article><h3>Medaljer</h3>${t.medals.map((n,i)=>`<p>${['Guld','Silver','Brons'][i]} · ${INT_NATIONS[n]}</p>`).join('')}</article>`:''}<p>${t.skipped?'Den här karriären började bevaka JVM efter uttagningen. Ingen turnering eller frånvaro skapas i efterhand.':'Uttagna spelare deltar inte i klubbträning eller klubblagsmatcher under uppdraget. Avtalen består.'}</p><button class="wd-link" onclick="deskNavigate('training')">Träning & återhämtning →</button></div><footer><button class="wd-link" onclick="worldDeskOpen('internationalScope')">Om turneringen & underlaget →</button></footer></aside>`;}
function worldDeskNationalRoster(){const t=state.international.tournament,nation=state.international.selected,rows=t.rosters[nation]||[];return `<div class="wd-main">${worldDeskPanel(INT_NATIONS[nation]+' · landslagstrupp',`<table class="wd-table"><thead><tr><th>Spelare</th><th>Klubb</th><th>Pos</th><th>M</th><th>Min</th><th>Mål</th><th>Ass</th></tr></thead><tbody>${rows.map(e=>`<tr><th>${playerReference(e.id,e.name)}<small>${e.withdrawn?'Återbud':e.fictional?'Fiktiv spelare':''}</small></th><td>${clubReference(e.club)}</td><td>${e.pos}</td><td>${e.games}</td><td>${Math.round(e.seconds/60)}</td><td>${e.goals}</td><td>${e.assists}</td></tr>`).join('')||worldDeskEmpty(t.skipped?'Ingen trupp finns registrerad för denna turnering.':'Truppen publiceras vid uttagningen den 15 december.',7)}</tbody></table>`,rows.length+' registrerade spelare',worldDeskNationSelect(),'Statistiken avser denna JVM-turnering.')}${worldDeskInternationalAside()}</div>`;}
function worldDeskNationSelect(){return `<label class="wd-filter">Landslag<select onchange="worldDeskNation(this.value)">${recruitOptions(INT_NATIONS,state.international.selected)}</select></label>`;}
function worldDeskTournament(){const t=state.international.tournament,rows=t.games.filter(g=>worldUI.games==='all'||g.home===state.international.selected||g.away===state.international.selected);return `<div class="wd-main wd-tournament">${worldDeskPanel('Matcher & rapporter',`<table class="wd-table wd-fixtures"><thead><tr><th>Datum / fas</th><th>Hemma</th><th>Resultat</th><th>Borta</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${calText(g.date)}<small>${g.stage}</small></td><td>${INT_NATIONS[g.home]}</td><td>${g.played?`<button class="wd-score" onclick="${trainingSafe('worldDeskOpen(\'internationalGame\','+JSON.stringify(g.id)+')')}">${g.hg}–${g.ag}${g.shootout?' STR':g.overtime?' ÖT':''}</button>`:'–'}</td><td>${INT_NATIONS[g.away]}</td></tr>`).join('')||worldDeskEmpty(t.skipped?'Ingen turnering registrerad.':'Spelschemat publiceras vid samlingen den 20 december.',4)}</tbody></table>`,'Välj ett spelat resultat för matchrapport.',`<label class="wd-filter">Visa<select onchange="worldDeskSet('games',this.value)">${recruitOptions({all:'Alla matcher',nation:INT_NATIONS[state.international.selected]},worldUI.games)}</select></label>${worldDeskNationSelect()}`,'Resultat, skott och spelarinsatser hämtas från samma registrerade match.')}<aside class="wd-aside"><header><h2>Grupper & medaljer</h2></header><div data-scroll-key="groups">${t.medals.length?`<p class="wd-champion">${INT_NATIONS[t.medals[0]]} vinner JVM</p>`:''}${t.groups.map((group,i)=>`<h3>Grupp ${i?'B':'A'}</h3><table class="wd-table wd-group"><thead><tr><th>Land</th><th>M</th><th>+/−</th><th>P</th></tr></thead><tbody>${internationalStandings(t,group).map(r=>`<tr><th>${INT_NATIONS[r.nation]}</th><td>${r.gp}</td><td>${r.gf-r.ga}</td><td>${r.pts}</td></tr>`).join('')}</tbody></table>`).join('')||'<p>Grupperna publiceras när landslagen samlas.</p>'}</div><footer>Tre poäng för ordinarie seger, två efter förlängning eller straffar, en för övertidsförlust.</footer></aside></div>`;}
function worldDeskInternationalHistory(){const w=state.international;return `<div class="wd-main">${worldDeskPanel('Tidigare JVM-turneringar',w.archive.map(a=>`<details class="wd-archive"><summary>JVM ${a.year} · ${a.medals?.length?INT_NATIONS[a.medals[0]]+' vann':'Ingen komplett turnering'}</summary><p>${(a.medals||[]).map((n,i)=>['Guld','Silver','Brons'][i]+': '+INT_NATIONS[n]).join(' · ')}</p><table class="wd-table"><thead><tr><th>Datum</th><th>Match</th><th>Fas</th></tr></thead><tbody>${(a.results||[]).map(g=>`<tr><td>${calText(g.date)}</td><td>${INT_NATIONS[g.home]} ${g.hg}–${g.ag} ${INT_NATIONS[g.away]}</td><td>${g.stage}</td></tr>`).join('')||worldDeskEmpty('Inga resultat registrerade.',3)}</tbody></table></details>`).join('')||'<p class="wd-empty">Turneringen arkiveras när karriären går vidare till nästa säsong.</p>','Upp till sex tidigare turneringar sparas.','','Historiska arkiv innehåller resultat; fullständiga matchrapporter visas för aktuell turnering.')}${worldDeskInternationalAside()}</div>`;}
function worldDeskInternational(){const w=ensureInternational();if(!w)return '';const t=w.tournament,own=worldDeskOwnInternational(),entries=Object.values(t.rosters).flat();return worldDeskFrame('Landslag & JVM','Följ talangerna före, under och efter landslagsuppdraget.',[['JVM '+t.year,worldDeskStatus(t),'Karriärens turnering'],['Uttagna från klubben',entries.filter(e=>e.club===managerClub()&&!e.withdrawn).length,'Aktuell landslagsuttagning'],['Spelare borta',own.filter(r=>internationalAway(r.p)).length,'Återkomst 6 januari'],['Spelade matcher',t.games.filter(g=>g.played).length+' / '+t.games.length,'Registrerade turneringsmatcher']],`${worldDeskTabs('Landslagsbevakning','international',{club:'Din klubb',nation:'Landslagstrupper',tournament:'Turneringen',history:'Historik'})}${worldUI.international==='nation'?worldDeskNationalRoster():worldUI.international==='tournament'?worldDeskTournament():worldUI.international==='history'?worldDeskInternationalHistory():worldDeskInternationalClub()}`);}
function worldDeskDraftBoard(){const d=state.nhl.draft;return d.board.length?d.board:nhlBoard(d.year);}
function worldDeskDraftRows(){const query=nhlUI.query.toLocaleLowerCase('sv');return worldDeskDraftBoard().filter(r=>(worldUI.position==='all'||r.pos===worldUI.position)&&`${r.name} ${r.club}`.toLocaleLowerCase('sv').includes(query));}
function worldDeskDraftAside(){const d=state.nhl.draft;return `<aside class="wd-aside"><header><h2>Draftåret ${d.year}</h2><small>${d.status==='completed'?'Genomförd':d.skipped?'Ej bevakad':calText(d.date)}</small></header><div data-scroll-key="draft-info"><h3>Scoutprognos</h3><p>${d.boardDate?'Senaste rapport: '+calText(d.boardDate)+'.':'Inledande bedömning, ännu ingen periodisk rapport.'} Prognosen uppdateras under hösten, efter JVM och inför draften.</p><h3>Vad betyder intervallet?</h3><p>Det visar ett osäkert spann av draftrundor. Placeringen kan ändras när underlaget växer; den är ingen garanti för ett draftval.</p><h3>Efter ett draftval</h3><p>Spelaren stannar i sin klubb. NHL-rättigheter, utlandsavtal och löften om istid är separata steg.</p><button class="wd-link" onclick="nhlSetFilter('tab','rights')">Granska rättigheter →</button></div><footer><button class="wd-link" onclick="worldDeskOpen('draftScope')">Om draften & spelarunderlaget →</button></footer></aside>`;}
function worldDeskDraftInspector(p,row){if(!p)return '';const a=p.nhlPlan,active=nhlRightsActive(p)&&!naActive(p),status={active:'Pågående istidslöfte',open:'Öppen dialog',met:'Löftet uppfyllt',missed:'Löftet missat',neutral:'Avslutat utan påföljd'};return `<footer class="wd-inspector"><div><span class="wd-eyebrow">VALD SPELARE</span><h2>${playerReference(p.id,p.name)}</h2><p>${p.pos} · ${trainingSafe(playerIdentity(p.id)?.club||p.club||'Klubb saknas')}</p></div><div><h3>${p.nhlDraft?'REGISTRERAT DRAFTVAL':'SCOUTERNAS BEDÖMNING'}</h3><p>${p.nhlDraft?`${trainingSafe(p.nhlDraft.club)} · ${p.nhlDraft.year} · val ${p.nhlDraft.overall}`:row?nhlRange(row.rank):'Utanför prognosen'}</p><small>${a?.season===state.season.year?`${status[a.status]}${a.path!=='open'?' · '+a.met+'/'+a.targetGames+' istidsmål':''}`:p.nhlDraft?active?'NHL-rättigheter till '+calText(p.nhlDraft.expires):'Rättigheter och klubbavtal är separata.':`${row?.jvm||0} registrerade JVM-matcher i draftunderlaget.`}</small></div><div><h3>NÄSTA STEG</h3>${nhlOwned(p)&&active?`<button class="wd-outline" onclick="${trainingSafe('worldDeskOpen(\'plan\','+JSON.stringify(p.id)+')')}">${a?.season===state.season.year?'Följ utvecklingsdialogen':'Granska utvecklingsväg'}</button>`:worldDeskProfileButton(p)}${nhlOwned(p)?`<button class="wd-link" onclick="${trainingSafe((p.academy?'juniorSelect(':'developmentOpenPlan(')+JSON.stringify(p.id)+')')}">Spelarens utveckling →</button>`:''}</div></footer>`;}
function worldDeskNHLClub(){const rows=worldDeskOwnDraft(),board=worldDeskDraftBoard(),selected=rows.find(r=>samePlayerId(r.p.id,worldUI.draftPerson))||rows[0];worldUI.draftPerson=selected?.p.id||null;const table=`<table class="wd-table wd-people"><thead><tr><th>Spelare</th><th>Pos / ålder</th><th>Draftläge</th><th>Utvecklingsdialog</th></tr></thead><tbody>${rows.map(({p})=>{const row=board.find(r=>samePlayerId(r.id,p.id)),a=p.nhlPlan;return `<tr class="${selected?.p===p?'wd-selected':''}"><th>${worldDeskPickButton('draftPerson',p.id,p.name)}<small>${p.academy?'Juniorverksamheten':'A-truppen'}</small></th><td>${p.pos} · ${p.age} år</td><td>${p.nhlDraft?trainingSafe(p.nhlDraft.club)+'<small>'+p.nhlDraft.year+' · val '+p.nhlDraft.overall+'</small>':row?nhlRange(row.rank):'Utanför prognosen'}</td><td>${a?.season===state.season.year?({active:'Pågående löfte',open:'Öppen dialog',met:'Uppfyllt',missed:'Missat',neutral:'Avslutat'})[a.status]+(a.path!=='open'?`<small>${a.met}/${a.targetGames} istidsmål · ${a.games}/6 matcher</small>`:''):p.nhlDraft?'Ingen dialog denna säsong':'Efter ett draftval'}</td></tr>`;}).join('')||worldDeskEmpty('Inga draftaktuella talanger eller registrerade draftval i klubben just nu.',4)}</tbody></table>`;return `<div class="wd-main">${worldDeskPanel('Klubbens väg mot NHL',table,'Markera en spelare för underlag, rättigheter och utvecklingsbeslut.','','Ett löfte ger effekt först när faktisk matchtid har följts upp.')}${worldDeskDraftAside()}</div>${selected?worldDeskDraftInspector(selected.p,board.find(r=>samePlayerId(r.id,selected.p.id))):''}`;}
function worldDeskBoardFilters(){return `<form class="wd-search" onsubmit="event.preventDefault();worldDeskSearch(this)"><input name="query" type="search" aria-label="Sök draftspelare eller klubb" placeholder="Sök spelare eller klubb…" value="${trainingSafe(nhlUI.query)}"><button>Sök</button></form><label class="wd-filter">Position<select onchange="worldDeskSet('position',this.value)">${recruitOptions({all:'Alla',MV:'Målvakt',B:'Back',C:'Center',VF:'Vänsterforward',HF:'Högerforward'},worldUI.position)}</select></label>`;}
function worldDeskNHLBoard(){const rows=worldDeskDraftRows(),pages=Math.max(1,Math.ceil(rows.length/40)),page=Math.min(Math.max(0,Number(worldUI.draftPage)||0),pages-1),shown=rows.slice(page*40,page*40+40),selected=shown.find(r=>samePlayerId(r.id,worldUI.draftPerson))||shown[0],p=selected&&worldDeskPlayer(selected.id);worldUI.draftPerson=selected?.id||null;const table=`<table class="wd-table wd-board"><thead><tr><th>Bedömd plats</th><th>Spelare</th><th>Klubb</th><th>Prognos</th><th>Förändring</th><th>JVM</th></tr></thead><tbody>${shown.map(r=>`<tr class="${selected===r?'wd-selected':''}"><td>${r.rank}</td><th>${worldDeskPickButton('draftPerson',r.id,r.name)}<small>${r.pos}${r.fictional?' · Fiktiv':''}${r.estimated?' · Födelseår uppskattat':''}</small></th><td>${clubReference(r.club)}</td><td>${nhlRange(r.rank)}</td><td>${r.previous?`${r.previous-r.rank>0?'+':''}${r.previous-r.rank}`:'–'}</td><td>${r.jvm||0} M</td></tr>`).join('')||worldDeskEmpty('Inga spelare matchar urvalet.',6)}</tbody></table>`;const paging=`<span>${rows.length} spelare · sida ${page+1} av ${pages}</span><div class="wd-paging"><button onclick="worldDeskSet('draftPage',${page-1})" ${page===0?'disabled':''}>Föregående</button><button onclick="worldDeskSet('draftPage',${page+1})" ${page+1>=pages?'disabled':''}>Nästa</button></div>`;return `<div class="wd-main">${worldDeskPanel('Scoutprognos inför '+state.nhl.draft.year,table,'Förändring avser placering sedan förra rapporten, inte potential.',worldDeskBoardFilters(),paging)}${worldDeskDraftAside()}</div>${worldDeskDraftInspector(p,selected)}`;}
function worldDeskNHLFilter(round=false,editions=[]){return `<div class="wd-filters">${editions.length?`<label class="wd-filter">Draftår<select onchange="worldDeskSet('draftYear',this.value)">${editions.map((e,i)=>`<option value="${e.year}" ${(worldUI.draftYear==='latest'?i===0:String(e.year)===worldUI.draftYear)?'selected':''}>${e.year}</option>`).join('')}</select></label>`:''}<label class="wd-filter">NHL-klubb<select onchange="nhlSetFilter('club',this.value)">${recruitOptions(Object.fromEntries([['all','Alla klubbar'],...NHL_CLUBS.map(c=>[c,c])]),nhlUI.club)}</select></label>${round?`<label class="wd-filter">Runda<select onchange="nhlSetFilter('round',this.value)">${recruitOptions({all:'Alla rundor',1:'1',2:'2',3:'3',4:'4',5:'5',6:'6',7:'7'},nhlUI.round)}</select></label>`:''}</div>`;}
function worldDeskNHLResults(){const w=state.nhl,editions=[w.draft,...w.history].filter(e=>e.status==='completed'),e=editions.find(e=>String(e.year)===worldUI.draftYear)||editions[0],rows=(e?.picks||[]).filter(r=>(nhlUI.club==='all'||r.club===nhlUI.club)&&(nhlUI.round==='all'||r.round===Number(nhlUI.round)));return `${worldDeskNHLFilter(true,editions)}<div class="wd-main">${worldDeskPanel(e?'Draftresultat '+e.year:'Draftresultat',`<table class="wd-table"><thead><tr><th>Val</th><th>NHL-klubb</th><th>Spelare</th><th>Från</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.overall}<small>Runda ${r.round}</small></td><td>${clubReference(r.club)}</td><th>${playerReference(r.id,r.name)}<small>${r.pos}${r.fictional?' · Fiktiv':''}</small></th><td>${clubReference(r.origin,{year:e.year})}</td></tr>`).join('')||worldDeskEmpty(editions.length?'Inga draftval matchar filtren.':'Första draften genomförs '+calText(w.draft.date)+'. Inga resultat skapas i förväg.',4)}</tbody></table>`,rows.length+' registrerade val i urvalet','','Ordningen och valen kommer från din karriärs draft. Spelarens klubbavtal ändras inte av ett draftval.')}${worldDeskDraftAside()}</div>`;}
function worldDeskNHLRights(){const all=internationalPlayers().filter(({p})=>p.nhlDraft&&(nhlUI.club==='all'||p.nhlDraft.club===nhlUI.club));return `${worldDeskNHLFilter()}<div class="wd-main">${worldDeskPanel('NHL-rättigheter & klubbavtal',`<table class="wd-table"><thead><tr><th>Spelare</th><th>Nuvarande klubb</th><th>NHL-klubb</th><th>Draft</th><th>Rättigheter</th></tr></thead><tbody>${all.map(({p,club})=>`<tr><th>${playerReference(p.id,p.name)}<small>${p.pos}</small></th><td>${clubReference(club)}</td><td>${clubReference(p.nhlDraft.club)}</td><td>${p.nhlDraft.year} · #${p.nhlDraft.overall}</td><td>${nhlRightsActive(p)?'Till '+calText(p.nhlDraft.expires):'Utgångna'}</td></tr>`).join('')||worldDeskEmpty('Inga registrerade rättigheter i urvalet.',5)}</tbody></table>`,all.length+' spelare i urvalet','','NHL-rättigheter ger exklusiv förhandlingsrätt inom NHL i modellen. Flytt och lön kräver ett separat avtal.')}${worldDeskDraftAside()}</div>`;}
function worldDeskNHL(){const w=ensureNHL();if(!w)return '';const own=worldDeskOwnDraft(),d=w.draft;let body=nhlUI.tab==='board'?worldDeskNHLBoard():nhlUI.tab==='results'?worldDeskNHLResults():nhlUI.tab==='rights'?worldDeskNHLRights():nhlUI.tab==='contracts'?`<div class="wd-embedded" data-scroll-key="na-contracts">${naView()}</div>`:nhlUI.tab==='leagues'?`<div class="wd-embedded" data-scroll-key="na-leagues">${nasView()}</div>`:worldDeskNHLClub();return worldDeskFrame('NHL & draft','Från scoutintresse till draftval, utvecklingsbeslut och utlandsavtal.',[['Draft '+d.year,calText(d.date),d.status==='completed'?'Genomförd draft':'Datum i spelvärlden'],['Klubbens draftspelare',own.length,'Aktuell årskull & registrerade val'],['Aktiva rättigheter',own.filter(({p})=>nhlRightsActive(p)).length,'Spelare i din klubb'],['Pågående löften',own.filter(({p})=>p.nhlPlan?.status==='active').length,'Uppföljning genom verklig istid']],`${worldDeskTabs('NHL och draft','nhl',{club:'Din klubb',board:'Scoutprognos',results:'Draftresultat',rights:'NHL-rättigheter',contracts:'Avtal & lån',leagues:'NHL / AHL'})}${w.notice?`<p class="wd-notice" role="status">${trainingSafe(w.notice)}</p>`:''}${body}`);}
function worldDeskInternationalReport(g){return `<p class="wd-report-score">${INT_NATIONS[g.home]} <strong>${g.hg}–${g.ag}</strong> ${INT_NATIONS[g.away]}</p><p>${calText(g.date)} · ${g.stage} · ${g.shootout?'Straffavgörande':g.overtime?'Förlängning':'Ordinarie tid'}</p>${g.administrative?'<p>Administrativt resultat: otillräcklig matchtrupp.</p>':`<p>Skott på mål: ${g.shots.join('–')}. Straffavgörandet ingår inte i spelarpoängen.</p>`}<h3>Målhändelser</h3>${(g.events||[]).map(e=>`<p>${Math.floor(e.time/60)}:${String(e.time%60).padStart(2,'0')} · ${playerReference(e.scorerId,e.scorer)}${e.assists.length?' ('+e.assists.map(trainingSafe).join(', ')+')':''}</p>`).join('')||'<p>Inga registrerade målhändelser.</p>'}${(g.players||[]).map((rows,side)=>`<h3>${INT_NATIONS[side?g.away:g.home]}</h3><div class="wd-report-table"><table class="wd-table"><thead><tr><th>Spelare</th><th>Istid</th><th>Mål</th><th>Ass</th><th>Skott / räddningar</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${playerReference(r.id,r.name)}</th><td>${analysisTime(r.seconds)}</td><td>${r.goals}</td><td>${r.assists}</td><td>${r.pos==='MV'?r.saves+' räddningar':r.shots+' skott'}</td></tr>`).join('')}</tbody></table></div>`).join('')}${(g.injuries||[]).map(p=>`<p>${playerReference(p.id,p.name)} · skada, bedömd frånvaro ${p.days} dagar vid matchtillfället.</p>`).join('')}`;}
function worldDeskDialog(){
 const chosen=state.page==='nhl'&&nhlUI.tab==='leagues'&&nasUI.tab==='games'&&nasUI.game?nasSelectedSeason()?.leagues[nasUI.league].games.find(g=>g.id===nasUI.game&&g.played):null;
 const kind=worldUI.drawer||(chosen?'nasGame':null),id=worldUI.actionId;if(!kind)return '';let title='',body='',confirm=false,disabled=false;
 if(kind==='internationalGame'){const g=state.international.tournament.games.find(g=>g.id===id&&g.played);if(!g)return '';title='JVM · matchrapport';body=worldDeskInternationalReport(g);}
 else if(kind==='nasGame'){title=nasUI.league+' · matchrapport';body=nasGameView(chosen);}
 else if(kind==='plan'){const p=worldDeskPlayer(id);if(!p||!nhlOwned(p)||!nhlRightsActive(p)||naActive(p))return '';title='Utvecklingsdialog · '+p.name;if(p.nhlPlan?.season===state.season.year)body=nhlPlanView(p);else{const junior=p.academy&&p.age<=20,options={open:'Håll dialogen öppen',senior:'Lova A-lagsistid',...(junior?{junior:'Lova J20-istid'}:{})};confirm=true;disabled=!!playerLoan(p)||!!p.academy?.loan||!managerEmployed()||!!(state.live&&!state.live.finished);body=`<p>Välj ett besked för säsongen. Du ansvarar för laguttagningen; valet flyttar inte spelaren och ändrar inte kedjorna.</p><label>Utvecklingsväg<select onchange="worldUI.plan=this.value;render()">${recruitOptions(options,worldUI.plan)}</select></label><div class="wd-callout">${worldUI.plan==='open'?'<h3>Öppen dialog</h3><p>Inget istidslöfte. Ingen bonus eller påföljd.</p>':`<h3>${worldUI.plan==='senior'?'Löfte om A-lagsistid':'Löfte om J20-istid'}</h3><p>${p.pos==='MV'?'Två matcher med minst 30 minuter':worldUI.plan==='senior'?'Fyra matcher med minst 8 minuter':'Fyra matcher med minst 15 minuter'} under sex bedömbara lagmatcher. Skada, medicinsk begränsning och JVM-frånvaro undantas.</p><p>Uppfyllt löfte ger +3 moral och befintligt tränarförtroende. Missat löfte ger −4. För få bedömbara matcher ger ingen påföljd.</p>`}</div><p>Beskedet kan bara lämnas en gång per säsong.</p>`;}}
 else if(kind==='recovery'){const p=worldDeskPlayer(id);if(!p||!worldDeskCanRecover(p))return '';title='Återhämtning · '+p.name;confirm=true;disabled=!!(state.live&&!state.live.finished);body=`<p>${Math.round(100-(p.fatigue||0))} % ork efter landslagsuppdraget.</p><p>Den individuella träningsplanen ersätts med tre dagars vila, med automatisk återgång. Granska spelarens medicinska status vid skada.</p>`;}
 else if(['move','loanback','reject'].includes(kind)){const o=state.northAmerica.offers.find(o=>o.id===id&&o.origin===managerClub()&&o.status==='pending');if(!o)return '';title={move:'Granska utlandsflytt',loanback:'Granska flytt med återlån',reject:'Avböj NHL-erbjudandet'}[kind];confirm=true;disabled=naLocked();body=`<h3>${trainingSafe(o.name)} → ${trainingSafe(o.team)}</h3><dl class="wd-facts"><dt>Ersättning till klubben</dt><dd>${money(o.fee)}</dd><dt>Avtal till</dt><dd>${calText(o.end)}</dd><dt>Svar senast</dt><dd>${calText(o.expires)}</dd></dl><p>${kind==='reject'?'Erbjudandet avböjs. Spelaren behåller sin nuvarande klubbtillhörighet.':kind==='loanback'?`NHL-klubben tar över kontraktet. Spelaren stannar genom återlån i A-truppen till ${calText(naSeasonEnd())}; klubben betalar ${money(o.ahlSalary*o.share)}/år under lånet.`:'NHL-klubben tar över kontraktet och spelaren lämnar din trupp. Se över kedjor och special teams efter flytten.'}</p>`;}
 else if(kind==='borrow'){const p=worldDeskPlayer(id);if(!p?.naContract)return '';title='Granska säsongslån · '+p.name;confirm=true;disabled=naLocked();body=`<p>Lön för din klubb: ${money(p.naContract.ahlSalary*.5)}/år. Minst 28 dagar före frivillig återgång.</p><p>${trainingSafe(loanFit(p,managerClub()).text)}. Tillgänglighet, övergångsfönster och lönebudget kontrolleras när du bekräftar.</p>`;}
 else if(kind==='recall'){title='Avsluta lånet';confirm=true;disabled=naLocked();body='<p>Begär att lånet avslutas enligt det gällande avtalet. Spelaren återgår till kontraktsägaren när återgången kan genomföras.</p>';}
 else if(kind==='internationalScope'){title='JVM · underlag & spelregler';body='<p>Karriärens JVM har tio landslag. Grupper, matchdagar och skiljeregler är spelmodellens upplägg. Seniorlandslag simuleras inte här.</p><p>Aktiva spelaridentiteter återanvänds. Saknade spelare kompletteras med en tydligt märkt fiktiv juniorpool. Födelseår uppskattas när födelsedatum saknas.</p><p>Uttagning bygger på rollbalans, nuvarande egenskaper, registrerad form och belastning. Potential garanterar ingen plats. Lika grupppoäng skiljs på målskillnad, gjorda mål och landskod. Plats 9–10 avgörs utan divisionsbyte.</p><p>Matchrapporterna kommer från registrerade händelser i landslagssimuleringen. Landslagets statistik räknas inte in i klubbens poängliga.</p>';}
 else if(kind==='draftScope'){title='NHL-draft · underlag & spelregler';body='<p>Sju rundor och högst 224 val ur karriärens bevakade spelarvärld. Draftdatumet 28 juni, spelgenererad ordning och fyra års rättighetstid är förenklade spelregler. Lotteri och handel med draftval ingår inte.</p><p>Scoutprognosen använder observerad utveckling, spelstyrka och JVM-underlag. Den läser inte dolda potentialtak. En spelare väljs bara en gång.</p><p>Äldre verkliga spelares tidigare draft och rättigheter saknas i startunderlaget och gissas inte fram. Framtida årskullar och fiktiva talanger kan väljas. Verkliga NHL/AHL-spelarlistor finns separat under ligabevakningen som källunderlag; de är inte automatiskt aktiverade karriärspelare.</p><p><a href="NHL-DRAFT.md" target="_blank" rel="noopener noreferrer">Spelmodell och källunderlag</a></p>';}
 else return '';
 return `<dialog id="world-dialog" class="wd-dialog" data-context="${kind}:${trainingSafe(String(id||chosen?.id||''))}" aria-labelledby="wd-dialog-title" oncancel="event.preventDefault();worldDeskClose()"><header><h2 id="wd-dialog-title">${trainingSafe(title)}</h2><button aria-label="Stäng dialog" onclick="worldDeskClose()">×</button></header><div class="wd-dialog-body">${body}${confirm?`<footer class="wd-dialog-actions"><button class="wd-outline" onclick="worldDeskClose()">Avbryt</button><button class="wd-primary" onclick="worldDeskConfirm()" ${disabled?'disabled':''}>Bekräfta beslutet</button></footer>`:''}</div></dialog>`;
}
