'use strict';
const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async function recruitmentUIReview(page,out){
  await page.getByRole('navigation',{name:'Spelets huvudområden'}).getByRole('button',{name:'Rekrytering',exact:true}).click();
  const recruitmentNav=page.getByRole('navigation',{name:'Rekrytering',exact:true});
  await recruitmentNav.getByRole('button',{name:'Översikt',exact:true}).click();
  assert.match(await page.locator('.rd-priorities').innerText(),/Målvakter: 3 spelklara · täckt/);
  await page.screenshot({path:path.join(out,'05-rekrytering.png'),fullPage:true});
  await recruitmentNav.getByRole('button',{name:'Truppplanering',exact:true}).click();
  const goalieCard=page.locator('.sc-coverage [data-position="Målvakt"]');
  assert.match(await goalieCard.innerText(),/3 i truppen · 3 spelklara/);
  assert.match(await goalieCard.innerText(),/Ingen antalsbrist/);
  await goalieCard.getByText('Visa spelare och avtal',{exact:true}).click();
  assert.match(await goalieCard.innerText(),/Olof Glifford/);
  assert.match(await goalieCard.innerText(),/Herman Liv/);
  assert.match(await goalieCard.innerText(),/Felix Sandström/);
  await page.getByRole('button',{name:'Se truppens kontrakt',exact:true}).first().click();
  assert.equal(await page.evaluate(()=>squadUI.tab),'contracts');
  assert.equal(await page.locator('.sw-filters input[name="query"]').inputValue(),'');
  assert.equal(await page.evaluate(()=>squadUI.position),'B');
  await page.getByRole('navigation',{name:'Spelets huvudområden'}).getByRole('button',{name:'Rekrytering',exact:true}).click();
  await recruitmentNav.getByRole('button',{name:'Spelarsök & scouting',exact:true}).click();
  await page.getByRole('button',{name:/^Filter/}).click();
  assert.equal(await page.locator('.rh-advanced').evaluate(el=>el.open),false);
  await page.getByRole('button',{name:'Visa kandidater',exact:true}).click();
  const candidateId=await page.evaluate(()=>String(recruitHub.player));
  await page.locator('.rd-inspector').getByRole('button',{name:'Beställ scouting',exact:true}).click();
  await page.locator('.sc-brief').waitFor();
  await page.locator('.sc-brief select[onchange*="method"]').selectOption('screen');
  const scoutingBefore=await page.evaluate(()=>({cash:state.money,fee:scoutingQuote(scoutDesk.draft.players,scoutDesk.draft.method,scoutDesk.draft.person).fee}));
  await page.locator('.sc-brief').getByRole('button',{name:/Starta uppdrag/}).click();
  assert.equal(await page.evaluate(()=>state.money),scoutingBefore.cash-scoutingBefore.fee);
  assert.equal(await page.evaluate(id=>scoutPending(id),candidateId),true);
  await page.locator('.sc-fields select[name="profile"]').selectOption('Målskytt');
  await page.locator('.sc-fields select[name="league"]').selectOption('SHL');
  await page.locator('.sc-fields select[name="placement"]').selectOption('Andra kedjan');
  await page.locator('.sc-fields select[name="targetRole"]').selectOption('key');
  await page.locator('.sc-fields input[name="maxSalary"]').fill('5000000');
  await page.getByRole('button',{name:'Ta fram uppdrag',exact:true}).click();
  assert.equal(await page.evaluate(()=>scoutDesk.draft.criteria.targetRole),'key');
  assert.equal(await page.evaluate(()=>scoutDesk.draft.criteria.league),'SHL');
  assert.equal(await page.locator('.sc-fields select[name="targetRole"]').inputValue(),'key');
  await page.screenshot({path:path.join(out,'06-scouting.png'),fullPage:true});
  await recruitmentNav.getByRole('button',{name:'Spelarsök & scouting',exact:true}).click();
  await page.screenshot({path:path.join(out,'07-spelarsokning.png'),fullPage:true});
  const searchLayout=await page.locator('.recruit-hub').evaluate(el=>({width:el.scrollWidth,client:el.clientWidth}));
  assert.ok(searchLayout.width<=searchLayout.client+1,'recruitment does not overflow horizontally');
  await require('../scripts/recruitment-browser-checks.cjs').checkRecruitment(page);
  await require('../scripts/recruitment-browser-checks.cjs').checkRecruitmentNegotiation(page,out);
};
